### ISSUE TITLE
Is it possible to use the coll.Has function with a variable instead of a string?

### ISSUE THREAD

**Issue by dbluxo** [hairyhenderson/gomplate#1006]
Hi, is it possible to use the [coll.Has](https://docs.gomplate.ca/functions/coll/#coll-has) function with a variable instead of a string?

This is working (with a string):

```yaml
{{ if has (datasource "config").aws "dev" }}
{{ $awsEnvKey := "$envName" }}
{{ else }}
{{ $awsEnvKey := "default" }}
{{ end }}
```

This does not work (with a variable):

```yaml
{{ if has (datasource "config").aws "$envName" }}
{{ $awsEnvKey := "$envName" }}
{{ else }}
{{ $awsEnvKey := "default" }}
{{ end }}
```

Where `$envName` is "dev".

**Comment by hairyhenderson** [comment]
Hi @dbluxo, thanks for posting this!

Unlike shell scripting languages like bash, gomplate doesn't resolve variables inside quoted strings.

So, this should work:

```go
{{ if has (datasource "config").aws $envName }}
{{ $awsEnvKey := $envName }}
{{ else }}
{{ $awsEnvKey := "default" }}
{{ end }}
```

However, this assumes `$envName` is a previously-defined template variable. If you mean to actually use an environment variable, use the [`getenv`](https://docs.gomplate.ca/functions/env/#env-getenv) function.

In addition, the `:=` token both declares and defines a variable, and it can't be referenced outside of the scope where it was declared. So what you _probably_ want is something like this:

```go
{{ $envName := getenv "envName" }}
{{ $awsEnvKey := "default" }}
{{ if has (datasource "config").aws $envName }}
{{ $awsEnvKey = $envName }}
{{ end }}
```

**Comment by dbluxo** [comment]
Wow, thanks for your quick reply, that worked great!

One question left, I would like to use the set variable `$awsEnvKey`as follows:

`{{ (datasource "config").aws.$awsEnvKey.subnets | data.ToYAML | indent 6 }}`

Unfortunately I get this error message:

`FTL  error="template: cluster.template.yaml:22: bad character U+0024 '$'"`

Is there a way to use the variable `$awsEnvKey` at this point?

**Comment by hairyhenderson** [comment]
> Is there a way to use the variable `$awsEnvKey` at this point?

Yes, for this you need the `index` keyword. There's some documentation that covers its usage here: https://docs.gomplate.ca/syntax/#indexing-arrays-and-maps

In short, you _should_ be able to do something like:

```go
{{ (index ((datasource "config").aws) $awsEnvKey).subnets | data.ToYAML | indent 6 }}
```

It's a bit awkward, but it could be deconstructed to something like:

```
{{ $aws := (ds "config").aws }}
{{ $env := index $aws $awsEnvKey }}
{{ $env.subnets | data.ToYAML | indent 6 }}
```

**Comment by dbluxo** [comment]
You are my hero for today, thank you! 💯
