### ISSUE TITLE
Possible to have a leaner list of dependencies?

### ISSUE THREAD

**Issue by dacodas** [hairyhenderson/gomplate#1032]
Hello, 

Let me preface this by saying I am a novice

I was curious if it is possible to lean out the list of dependencies, and perhaps provide some of the additional data source functionality in separate packages or as features. It would be nice if this package installed lickety-split for simple cases involving simple environment variable substitution

Thank you

**Comment by hairyhenderson** [comment]
Hi @dacodas, thanks for logging this!

Can I ask about your reasoning? What exactly is your use-case, and why is gomplate too big for you? What does "lickety-split" mean to you? And, how are you installing gomplate today? Perhaps there's a different way to install gomplate that may be more acceptable.

Also I should mention that if your use-case is actually _just_ variable substitution, you may want to take a look at the `envsubst` command - part of the `gettext` suite (see https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html for details).

**Comment by dacodas** [comment]
@hairyhenderson, incredible response time, thank you so much for your response

I think I was a bit trigger happy in making this issue. I was surprised by how long `go get -v github.com/hairyhenderson/gomplate` was taking for me, but I am not looking to develop on this project, so really I should have used one of the releases

You addressed this brilliantly, I was definitely using the wrong installation method. Thank you for your kindness and for  the `envsubst` reference as well

Please accept both my apologies for this issue eating up your time and my gratitude for your having made this package

I am closing now

**Comment by hairyhenderson** [comment]
No worries @dacodas, happy I could help! 🙂
