### ISSUE TITLE
YAML Files with KQL Code

### ISSUE THREAD

**Issue by kay07949** [hairyhenderson/gomplate#1033]
Hi, 

Apologies for the bold text, it doesn't allow me to revert to normal text...

Please let me know if the following is possible with gomplate. 

I have a main template called alert001.yaml with the following KQL Query:

-----------------------------------------------
//MasterTemplate

query: |
  AzureActivity
  | where TimeGenerated between (startofday(ago(starttime)) .. startofday(ago(endtime)))
  | where OperationName in~ (szOperationNames)
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), 
 ActivityTimeStamp = makelist(TimeGenerated), ActivityStatus = makelist(ActivityStatus), 

--------------------------------------------------------------------------------------------
Based on the above template, I need to create customer yaml files, example alert001-customer001.yaml. On the customer YAML file I need to add few additional lines of code on the KQL and this line of code has to be on the specific line it cannot be and the end of the code, etc.
------------------------------------------------------------------------------------------
//Customer YAML Files

AzureActivity
  | where callerIPAddress != "192.168.1.1"
  | where TimeGenerated between (startofday(ago(starttime)) .. startofday(ago(endtime)))
  | where OperationName in~ (szOperationNames)
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), 
 ActivityTimeStamp = makelist(TimeGenerated), ActivityStatus = makelist(ActivityStatus)
--------------------------------------------------------------------------------------------

Whenever we update the main template we will like it to reflect on the alert001-customer001.yaml, alert001-customer002.yaml, alert001-customer003.yaml files. In other words to append these files..

Any changes on the customer files will a trigger a CI/CD deployment to the Azure Sentinel environments...

Is that possible via gomplate? To have a main YAML template that will cascade any changes to the customer YAML files?

**Comment by hairyhenderson** [comment]
Hi @kay07949 - since you've closed this I'll assume you figured it out, but on a quick read it sounds like the merge datasource may be useful for this: https://docs.gomplate.ca/datasources/#using-merge-datasources

**Comment by kay07949** [comment]
Apologies I closed by accident

**Comment by kay07949** [comment]
Thank you i will check this and give it try..

**Comment by kay07949** [comment]
i have run this command for the merge and i am getting errors:

gomplate -d "merge:./CC-SNC-PRX-08.yaml | /Customer001/Customer001.yaml"  

FTL  error="invalid datasource (merge:./CC-SNC-PRX-08.yaml | Customer001/Customer001.yaml): must provide an alias with files not in working directory"

below is my folder structure:

-rw-r--r--@ 1 kd  O\corp  1090 12 Jan 01:12 CC-SNC-PRX-08.yaml
drwxr-xr-x  4 kd  O\corp   128 12 Jan 00:16 Customer001
drwxr-xr-x  4 kd  O\corp   128 12 Jan 00:25 Customer002
drwxr-xr-x  3 kd  O\corp    96 12 Jan 00:32 Customer003

**Comment by kay07949** [comment]
i think i've found the right command for this:
gomplate -d "query=merge:./CC-SNC-PRX-08.yaml | /Customer001/Customer001.yaml"

**Comment by hairyhenderson** [comment]
@kay07949 one issue is probably that there shouldn't be spaces around the `|`

Let me know if you have further issues

**Comment by kay07949** [comment]
i've removed the space:

gomplate -d "query=merge:./CC-SNC-PRX-08.yaml|/Customer001/Customer001.yaml" in keeps running but it don't produce any results..

![image](https://user-images.githubusercontent.com/41331053/104327702-f550fe00-54e2-11eb-95fb-3f64aa5aac43.png)

**Comment by kay07949** [comment]
i've removed the space:

gomplate -d "query=merge:./CC-SNC-PRX-08.yaml|/Customer001/Customer001.yaml" in keeps running but it don't produce any results..

![image](https://user-images.githubusercontent.com/41331053/104327770-0a2d9180-54e3-11eb-818c-83d215f09dc3.png)

**Comment by hairyhenderson** [comment]
Ah - sorry, I assumed there was more to the command you were running! The `-d` flag defines a datasource, but you need to refer to that datasource in a template. Have a look at the examples in the documentation to get started (https://docs.gomplate.ca/).

**Comment by kay07949** [comment]
do you mean template as a .tmpl file? so instead for merge i need to run 

gomplate -d "query=merge:./CC-SNC-PRX-08.tmpl|/Customer001/Customer001.yaml" 

Apologies if I am asking silly questions - please do let me know if you prefer me to raise it as a different issue. I am totally new to bash as well as templating. 

on my yaml files i have:
------------------------
query: |
  Proxy
  | Generic Code Added Here...
  | Generic Code Added Here...
  {{ print "World" }}!
  {{ $w := "world" }}
  Hello, {{ print $w }}!
  Goodbye, {{ print $w }}.
------------------------
when I run gomplate -d config=./CC-SNC-PRX-08.yaml -i 'the value we want is: {{ (datasource "config").query }}' it doesnt return the interpreted data that is in the {{ }}

**Comment by kay07949** [comment]
just found the way to do it gomplate -f CC-SNC-PRX-08.tmpl
