### ISSUE TITLE
Thanks For This Project

### ISSUE THREAD

**Issue by rossedman** [hairyhenderson/gomplate#1034]
Wanted to say thanks for building this. Its designed well and has been useful to me so many times. I also wanted to tell you all of Github's Kubernetes configuration runs on this. I left recently but helped build it and wanted you to know how much this little project keeps GitHub operational.

✌️ ❤️

**Comment by hairyhenderson** [comment]
Wow! Thanks for reaching out @rossedman! That's awesome to hear 😂 I never imagined this little tool would be useful to so many people, but I'm glad it is! 😊

**Comment by rossedman** [comment]
@hairyhenderson Thanks for the awesome work, I meant to reach out along time ago but if you can see this comment its still working I guess. 🙃

**Comment by hairyhenderson** [comment]
Closing this issue now since there's not really any action to take, other than to be inspired!
