### ISSUE TITLE
gomplate always seems to produce an extra newline in output to STDERR - again

### ISSUE THREAD

**Issue by pmorch** [hairyhenderson/gomplate#1075]
Hi Dave,

I've just tested master (8363d443055c92edab544bdaaf5d38f0450165dd) and `touch empty.yaml; gomplate -f empty.yaml` still produces an empty line on STDERR. In #1074 you said to

>  @pmorch & @zacheryph, if you try out what's currently in master and that doesn't suit your needs, feel free to open a new issue

I agree with you that this isn't a deal-breaker issue. But when used as part of a script it forces me to choose between having a newline on STDERR from my script too or to redirect with `2>/dev/null` which squelches valuable clues if things go south, so it is not entirely rediculous.

I only opened this issue because I think you meant that you thought it *was* fixed on master. If you think that, my testing shows that is not the case.

If you know it isn't fixed on master, and closed it for whatever reason, feel free to close this issue too.

**Comment by hairyhenderson** [comment]
@pmorch thanks for logging this. I think I will need to revisit the logic for this (yet again!)

**Comment by zacheryph** [comment]
To continue the discussion from #1074, what _is_ the purpose of this? You noted its to take care of a frustrating output issue, but what exactly is that issue? The link relates to a ticket referring to `.gomplate.yaml` configuration file but I didn't see any real notes in that ticket on the purpose of this?

**Comment by lazdmx** [comment]
This is also annoying when using gomplate from Bazel

**Comment by hairyhenderson** [comment]
If I recall correctly, the original issue (not tracked in an issue, unfortunately) was effectively that it's annoying (surprising, even) to not have a newline when output is written to the console in an interactive shell.

It's like when `echo -n` is used - here's a sample in bash:

```console
$ echo -n "foo"
foo$
```

In zsh it's slightly better, but can be confusing:

```console
$ echo -n "foo"
foo%
$
```

The `%` is inserted by the shell to indicate the lack of newline at the end of the output, so at least it's an indication...

In gomplate, my thought was that if I simply print a newline to stderr, the stdout is unaffected while improving the experience for shell users.

Of course, this clearly wasn't very well thought-out, so I apologize for all the confusion. I will remove the feature entirely.

**Comment by hairyhenderson** [comment]
And - just to be clear, the intent was only ever to have the newline printed in interactive shells, never in non-interactive uses.
