### ISSUE TITLE
Allow using multiple input files after --input-file

### ISSUE THREAD

**Issue by tdemin** [hairyhenderson/gomplate#1081]
The idea is that you might want to recursively process files selected by shell masks. e.g with this input tree:
```
- cmd/
  - something/
    - input.go.tmpl
    - another_file.go
  - another_input.go.tmpl
- unrelated_dir/
  - something.txt
```

running `gomplate --output-map '{{ .in | strings.ReplaceAll ".go.tmpl" ".tmpl.go" }}' --input-file ./**/*.go.tmpl` with bash (bash would expand the glob to two `.go.tmpl` files) would result in the following tree:

```
- cmd/
  - something/
    - input.go.tmpl
    - input.tmpl.go
    - another_file.go
  - another_input.go.tmpl
  - another_input.tmpl.go
- unrelated_dir/
  - something.txt
```

This would help a lot when trying to utilize gomplate for processing multiple files in different directories. I'm currently doing this with multiple gomplate invocations with separate config files after having searched for a simpler solution for a while.

This would mean two breaking changes:

* `{{ .in }}` in `outputMap` would mean the full path to the file processed;
* the command you might want to run with gomplate would only be able to be specified after `--`, separating input files from the command.

**Comment by hairyhenderson** [comment]
@tdemin I think what you want might work with a combination of [`--input-dir`](https://docs.gomplate.ca/usage/#input-dir-and-output-dir) and [`--include`](https://docs.gomplate.ca/usage/#exclude-and-include).

Here's one example of how it works:

```console
$ tree in/
in
├── first
│   ├── bar.in
│   ├── quux
│   └── second
│       ├── baz.in
│       └── corgle
├── foo.in
└── qux

2 directories, 6 files
$ gomplate --input-dir in/ --include '*.in' --output-map 'out/{{ .in | strings.ReplaceAll ".in" ".out" }}'
$ tree out/
out
├── first
│   ├── bar.out
│   └── second
│       └── baz.out
└── foo.out

2 directories, 3 files
```

In that example the output is rendered into a new directory `out/`, but if you want to use the same directory you could specify `in/` as well.

I tried using `.` as the input-dir and there seems to be a bug with that (yikes!) so I'm working on fixing it. But hopefully this should be enough to get you started.

Let me know if that helps.

**Comment by tdemin** [comment]
@hairyhenderson still not perfect when working from shell but it does what I wanted, thanks. :+1:

**Comment by hairyhenderson** [comment]
@tdemin np - I understand what you mean, but it's important that gomplate remains shell-agnostic. Many users use gomplate outside of shells, and also on Windows where shell expansions aren't really a thing.

I'm going to close this, but feel free to re-open if you feel the need. Also feel free to [open a new discussion](https://github.com/hairyhenderson/gomplate/discussions) if you simply have questions about how to best approach your use-case 🙂
