### ISSUE TITLE
The Go config is deprecated while the new config.Config is unexported 

### ISSUE THREAD

**Issue by SimSmith** [hairyhenderson/gomplate#1097]
## Context
I wanted to bake in _gomplate_ into my existing Go program instead of relying on the command-line tool.
My plan was to simply use [gomplate.Run](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3@v3.9.0#Run) to take the path to a TOML config that is using some _getenv_ templates.
Unfortunately, it seems like I can't use that function because the second argument is an [internal type](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3@v3.9.0/internal/config#Config) that is not exposed in some way.

## Problem
`gomplate.RunTemplates` is deprecated alongside the `gomplate.Config` in favour of `gomplate.Run` but that function can't be used because `config.Config` is not exported in the library.

## Expected behaviour
The new Config could be somewhere else, have exported construct functions, or have an exported alias.

**Comment by hairyhenderson** [comment]
Thanks for logging this @SimSmith - I did a bit of digging into whether I can simply expose the internal `internal/config.Config` struct now, and I'm working on some refactoring that will likely need the `Config` struct to change, so I'd rather not expose it until it's in a state that I'm ready to fully support.

For now you'll need to use the deprecated [`gomplate.RunTemplates`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3#RunTemplates) function. I've documented a [deprecation policy](https://github.com/hairyhenderson/gomplate/blob/master/CONTRIBUTING.md#versioning-api-and-deprecation), but the upshot is that my goal is to preserve deprecated API until the next major version (v4 in this case). So, you can confidently continue to use `gomplate.RunTemplates` until at least v4, and I definitely won't remove `gomplate.RunTemplates` until there's a fully-workable replacement.

My goal is to expose [`config.Config`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3@v3.9.0/internal/config#Config) before v4, so it shouldn't be too long.

I'll leave this issue open for now, if for no other purpose to serve as a reminder for myself 😉

**Comment by hairyhenderson** [comment]
Rather than simply exposing the existing internal `Config` struct I've opted to create a new [`gomplate.Renderer`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3@v3.10.1-0.20220612205600-13b0d86d7630#Renderer) API in #1422.

I think this effectively fixes this issue - please let me know if there are any issues with the new API!
