### ISSUE TITLE
🎁 Package Gomplate as a windows Chocolatey package 🎁 

### ISSUE THREAD

**Issue by adriens** [hairyhenderson/gomplate#1119]
# :point_right: Context

A lot of software, and especially  `cli` are packaged as chocolatey packages so install and upgrade process are easier to manage. For windows, [Chocolatey](https://docs.chocolatey.org/en-us/faqs), ie : 

> Chocolatey is kind of like apt-get, but for Windows (with Windows comes limitations). It is a machine level package manager that is built on top of nuget command line and the nuget infrastructure. 

For example [jq](https://community.chocolatey.org/packages/jq) is packaged this way.

# :rocket: Action

Create and maintain a chocolatey package for Gomplate so install actions process on windows will be as simple as : 

- Install : `choco install gomplate`
- Upgrade : `choco upgrade gomplate`
- Uninstall : `choco uninstall gomplate`

**Comment by adriens** [comment]
Done with https://github.com/adriens/chocolatey-gomplate/issues/1

Find badges below : 

[![Chocolatey](https://img.shields.io/chocolatey/v/gomplate.svg)](https://chocolatey.org/packages/gomplate)
[![Chocolatey](https://img.shields.io/chocolatey/dt/gomplate.svg)](https://chocolatey.org/packages/gomplate)

**Comment by hairyhenderson** [comment]
wow, thanks @adriens! I looked at doing a chocolatey package a while back and decided it was too complex for someone who doesn't use Windows like me 😉

Would you be willing to transfer the repo into the https://github.com/gomplate organization to make it more official? You can retain owner/maintainership 🙂

**Comment by hairyhenderson** [comment]
@adriens also - would you be willing to add some documentation to explain how to install gomplate with chocolatey? I'm thinking somewhere on this page: https://github.com/hairyhenderson/gomplate/blob/master/docs/content/installing.md

**Comment by adriens** [comment]
OK, PR done for documentation see https://github.com/hairyhenderson/gomplate/pull/1121

**Comment by adriens** [comment]
> Would you be willing to transfer the repo into the https://github.com/gomplate organization to make it more official? You can retain owner/maintainership

Yep, that would make sense. First, I have to automate the process as the release pipe for now is manual. Once this done, the while process should be as easy as : 

1. Upgrade version in a properties files (`gomplate.properties`)
2. Let the windows build validate `main` branch
3. Create a release
4. Let the windows build release on central repo

Some constraints :

- I'll stay in charge and responsible on chocolatey so we'll both be responsible for package quality.
- You'll have to create the link with AppVeyor and provide me (or make me a PR) [secret key hash](https://www.appveyor.com/docs/build-configuration/#secure-variables)

First step is to automate it on my personal repo, and once running the good way, perform the ownership transfer : what do you think about this approach ?

https://github.com/adriens/chocolatey-gomplate/issues/2

You'll have

**Comment by hairyhenderson** [comment]
> First step is to automate it on my personal repo, and once running the good way, perform the ownership transfer : what do you think about this approach ?

That sounds OK - though (and I mentioned it on https://github.com/adriens/chocolatey-gomplate/issues/2 too) - it might be good to consider using GHA instead of AppVeyor.

**Comment by hairyhenderson** [comment]
Ok, I've opened https://github.com/adriens/chocolatey-gomplate/issues/3 to track migrating the repo, and that can happen at your leisure @adriens. I'm going to close this issue now that the badges & docs are merged.

Thanks again for this, I really appreciate it!

**Comment by adriens** [comment]
I use AppVeyor as I need a windows runtime 😆 to pass the `choco build & push` commands
