### ISSUE TITLE
Chocolatey release automation > request for asset `gomplate_windows-amd64.zip`

### ISSUE THREAD

**Issue by adriens** [hairyhenderson/gomplate#1122]
# Context

I'm currenlty working on Full Choco build automation and would like to make it cleaner. Actually the choco package embeds the binary, which is not a good practice, yet it was useful get a first release as fast as I could. The drawbacks of this approach are : 

- this is a bad practice
- the choco review process needs a human (causes longer delay during release review process)
- the download stats are not linked to the Github ones (GH release download score) as the binary is itself embedded in the choco package)

Actually, on the release page, ther only is the `exe` version, which does not not allow me to use native chocolatey functions.

The purpose of this ticket is to be able to switch to this much cleaner (and safer) mode.

# Request for change

As part of the released assets, could you please add that kind of resource for windows. Making it look like the following would be perfect : 

Drop a file `gomplate_windows-amd64.zip` or `gomplate_windows-amd64-choco.zip` that would contain the following file at its root : `gomplate.exe`

Making the zip structure look like this : 
 
```
gomplate_windows-amd64.zip
|_ gomplate.exe
```
# Benefits

Once this done, each choco install will target the Gomplate release page, making your download stats up-to-date. Maybe this request will seem a bit weird to you. Hopefully you'll be ok to implement it.

# Related Chocolatey issue

https://github.com/adriens/chocolatey-gomplate/issues/4

**Comment by hairyhenderson** [comment]
In general this sounds OK to me, but I'm not sure I fully understand the reasoning.

Is the idea that the chocolatey package can reference a `.zip` file directly from GitHub releases? And - it doesn't support `.exe` files?

**Comment by adriens** [comment]
yep, there are existing out of the box functions for zip and msi, exe (but for installers), that embed checksum checking.

**Comment by adriens** [comment]
https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage

**Comment by hairyhenderson** [comment]
ah, that makes sense... I suppose it's not that common to install single-binary apps 😉

Ok, I can look at adding a `.zip` as part of my release process.

**Comment by adriens** [comment]
Indeed LOOOL

**Comment by hairyhenderson** [comment]
@adriens I'm finally back to working on this 😅... #1198 adds the make target I'll need, and then for gomplate 3.10.0 the zip archive will be published. I'm hoping to ship it over the next few days.

**Comment by adriens** [comment]
WOW, looks really great.
So I'll implement the new releaase pipe that uses that asset; That will be much cleaner. That will be great 🚀
