### ISSUE TITLE
Error in doc example

### ISSUE THREAD

**Issue by kpym** [hairyhenderson/gomplate#1133]
I tried to run the following example of the documentation
```bash 
> gomplate -d homedir=env:///HOME -i '{{ files.IsDir (ds "homedir") }}'
12:05:58 ERR  error="template: <arg>:1: function \"files\" not defined"
```
and as you can see it looks like the `files` functions are not available.
It looks like `files.` should be replaced by `file.` everywhere in the documentation:
```bash 
> gomplate -d homedir=env:///HOME -i '{{ file.IsDir (ds "homedir") }}'
true
```

I'm using `gomplate_windows-amd64-slim.exe`:
```bash 
> gomplate -v
gomplate version 3.9.0
```

**Comment by hairyhenderson** [comment]
Thanks for reporting this, @kpym - I'll fix this up.
