### ISSUE TITLE
Support Kubernetes ConfigMaps as datasources

### ISSUE THREAD

**Issue by rhuss** [hairyhenderson/gomplate#116]
It would be awesome if Kubernetes [ConfigMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configmap/) could be used as datasources. This would be a perfect fit when gomplate is used as an [init-container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) which can be used to prepare configuration files for an application (like a `standalone.xml` for Wildfly app server).

Currently this can be done via ConfigMap backed volumes but a direct K8s support would be nicer, of course as it reduces the configuration overhead within Kubernetes.

**Comment by rhuss** [comment]
The would make sense for [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) probably, too.

**Comment by hairyhenderson** [comment]
Thanks @rhuss - I'm not very familiar with Kubernetes, but looking at the API, this could be fairly easy to implement using an HTTP(S) `datasource` (see https://kubernetes.io/docs/api-reference/v1.5/#read-199 for example).

One thing I'm not sure about is authentication, though #115 went in recently which allows arbitrary headers to be sent (mostly for auth purposes).

I think a good start would be to try to see if something like this works:

_(in.tmpl)_
```go
{{ (datasource "myconfigmap").data | toJSON }}
```

```console
$ gomplate --datasource myconfigmap=http://my.kube.api.address/api/v1/namespaces/{namespace}/configmaps/myconfigmap -f in.tmpl
```

It'd probably be nicer to have simplified support, but hopefully this is a start! Can you try this out and let me know if it works? Or let me know if I'm way off and this makes no sense 😉

**Comment by rhuss** [comment]
Kubernetes comes with a full client API which you can use directly without going over HTTP. As this datasource is probably supposed to be used within a Kubernetes cluster, the API server can be easily used with a so called `ServiceAccount`, so there is not to worry much about authentication. 

The use case I have in mind is agnostic of the API server's address as it is running from within the cluster (not from outside where it doesn't make much sense imo). 

As seen also in the [SO answer](http://stackoverflow.com/a/33109739/207604) all connection parameters can be directly fetched from files which are installed by Kubernetes at fixed file locations within the container (so gomplate could simply pick them up there). The namespace can also be picked up directly (would have to check how, though). The only parameters left is then configmap name.

It''s not urgent, just wanted to open the issue more as reminder for a cool, unique feature  ;-)

**Comment by hairyhenderson** [comment]
Ok thanks for the tips -- looks like https://github.com/kubernetes/client-go is what I want. I'll dabble with this when I get some time.

**Comment by 2color** [comment]
That'd be great!

**Comment by josledp** [comment]
I'll work on this if you don't mind

**Comment by hairyhenderson** [comment]
@josledp thank you! That would be fantastic!

**Comment by kevin1991acosta** [comment]
Good man

**Comment by hairyhenderson** [comment]
More than a year since there's been any activity, I'm going to close this issue for now.

While it would be _interesting_ for gomplate to support ConfigMaps and Secrets directly, the usual pattern that I've seen is to mount the ConfigMap as a file inside the pod, and gomplate can read these files with no issue. I've seen gomplate used like this in a few cases.

If there is renewed interest, feel free to re-open the issue! Mostly I'm trying to clean up stale issues and PRs 😉
