### ISSUE TITLE
Suppress missing environment error with empty or default value

### ISSUE THREAD

**Issue by josephlim75** [hairyhenderson/gomplate#1211]
Version: **3.9.0**

```
gomplate -i '{{.Env.MYVAR}}'
ERR  error="template: <arg>:1:6: executing \"<arg>\" at <.Env.MYVAR>: map has no entry for key \"MYVAR\""
```
I do see there is a `default` function, but I couldn't get it to work with the environment variable

This works
```
gomplate -i '{{ "" | default "foo"}}'
foo
```

This is not working
```
gomplate -i '{{ .Env.MYVAR | default "foo"}}'
 ERR  error="template: <arg>:1:7: executing \"<arg>\" at <.Env.MYVAR>: map has no entry for key \"MYVAR\""
```
For environment variable, can `gomplate` throw empty string if default value is not provided, instead of throwing error ?  Just like bash, if  nounset is configure `set -o nounset`, then environment variables are mandatory, otherwise, it always return empty string if not set.  Maybe a new argument for gomplate like below will help:

 ```
gomplate -i --nounset '{{ .Env.MYVAR | default "foo"}}'
foo
```
Without argument `--nounset`, then it will throw error

**Comment by josephlim75** [comment]
I actually found a workaround.  I am closing the issue now.
```
gomplate -i '{{if eq (getenv "MYVAR" | default "true") "true"}}foo{{end}}'
foo
```

**Comment by hairyhenderson** [comment]
@josephlim75 just FYI, this is by design - see [the docs](https://docs.gomplate.ca/syntax/#env)

**Comment by hairyhenderson** [comment]
Also, see the [`getenv`](https://docs.gomplate.ca/functions/env/#env-getenv) docs - you don't need to use the `default` function, you can provide the default as the second arg:

```console
$ gomplate -i '{{if eq (getenv "MYVAR" "true") "true"}}foo{{end}}'
foo
```

**Comment by josephlim75** [comment]
Nice, thanks for the doc pointer and your solution which is better to omit `default`.
