### ISSUE TITLE
net.ParseIPPrefix is broken in the current build (3.9.0)

### ISSUE THREAD

**Issue by brokenjacobs** [hairyhenderson/gomplate#1212]
```
$ docker run -it hairyhenderson/gomplate:stable --version
gomplate version 3.9.0

$ docker run -it hairyhenderson/gomplate:stable
{{ net.ParseIPPrefix "10.123.208.50/28" }}

22:16:24 ERR  error="template: -:1:3: executing \"-\" at <net>: can't evaluate field ParseIPPrefix in type *funcs.NetFuncs"
```

This also fails on other net examples from the documentation:
```
 docker run -it hairyhenderson/gomplate:stable
{{ (net.ParseIP "192.168.0.1").IsPrivate }}

22:17:47 ERR  error="template: -:1:4: executing \"-\" at <net>: can't evaluate field ParseIP in type *funcs.NetFuncs"
```

**Comment by brokenjacobs** [comment]
I think I'm seeing that this isn't in a released version as of yet... Looks like it was merged back in August but there hasn't been a release since January. Any word on a new release? :)

**Comment by hairyhenderson** [comment]
> I think I'm seeing that this isn't in a released version as of yet

Right! Unfortunately I don't have a good way (yet) of documenting which version a given function is available in. Sorry for the confusion.

> Any word on a new release? :)

Yep! I'll be releasing 3.10.0 soon - was planning on tomorrow or this weekend, depending on when I can dedicate the time.

**Comment by hairyhenderson** [comment]
Since this isn't a bug _per se_, I'll close this now - please feel free to follow up if you have any questions, or post them to the [discussions forum](https://github.com/hairyhenderson/gomplate/discussions)
