### ISSUE TITLE
AWS timeouts since 3.10.0

### ISSUE THREAD

**Issue by mikehdt** [hairyhenderson/gomplate#1234]
This is more of an "FYI" than anything, but it seems the AWS SDK that `3.10.0` has included is a bit more sensitive about things than `3.9.0` was. In `3.9.0` this worked just fine (I've anonymised this a little, in our case we were reading a value for a domain name to be substituted):

`AWS_REGION=us-east-1 gomplate -d domainName="aws+smp://testDomainName" ...some other args`

But in `3.10.0` this started to throw a timeout error. The following fixed it, although it's also a bit of an "eh, increase it till it works" situation:

`AWS_TIMEOUT=2000 AWS_REGION=us-east-1 gomplate -d domainName="aws+smp://testDomainName" ...some other args`

Hope that may help anyone who also encounters this. It took a bit of head scratching, as in my case using a different region (say, `ap-southeast-1`) worked just fine in `3.10.0` with exactly the same AWS+SMP setup there.

**Comment by hairyhenderson** [comment]
> When no `AWS_TIMEOUT` is specified gomplate will let the AWS SDK use the default `http.DefaultClient`, which effectively has a 30s timeout [...]

Not sure what I was thinking here - the [default is 500ms](https://github.com/hairyhenderson/gomplate/blob/main/aws/ec2info.go#L50).

Either way, I'm not sure what else can be done here - 500ms is usually plenty of time (for me). If I hear more reports I could change the default, though I expect it won't be as necessary in v4.

Feel free to re-open if this is still a significant problem.

**Comment by zaafar** [comment]
Just an FYI, this thing happened where I worked. We were connecting from AWS us-east-1 to ap-southeast-1 and it took 2000ms. Reading this issue saved the day, so thank you for that.

**Comment by CheyiLin** [comment]
>  If I hear more reports I could change the default, though I expect it won't be as necessary in v4.

We got the same timeout error when using `source_profile` which will assume roles multiple times. With env `AWS_TIMEOUT=1000` solves this.

It would be great if the next patch release has a longer default timeout. Thank you.

**Comment by daleksic-godaddy** [comment]
Got hit by this, and can confirm that short `AWS_TIMEOUT` is culprit. 

Same `gomplate` command works on 3.9, everything 3.10+ timeouts (just like in https://github.com/hairyhenderson/gomplate/issues/1227) unless `AWS_TIMEOUT` is increased to second or two.
