### ISSUE TITLE
Add ppc64le support

### ISSUE THREAD

**Issue by mayurwaghmode** [hairyhenderson/gomplate#1253]

**Comment by hairyhenderson** [comment]
@mayurwaghmode can you provide more details? What's your use-case? What OS? Do you just want binaries, or do you need a ppc64le Docker image too?

There's also already a ppc64le build available in Alpine: https://pkgs.alpinelinux.org/packages?name=gomplate&branch=edge&arch=ppc64le

**Comment by hairyhenderson** [comment]
Closing due to no response
