### ISSUE TITLE
Add examples on access split strings

### ISSUE THREAD

**Issue by karlschriek** [hairyhenderson/gomplate#1278]
It took me a while to figure out how to do a simple split string followed by accessing a specific item in the resulting array. This comes across as a very typical use case but I haven't found any explicit examples on how you would actually do this with gomplate!

To be clear, let's take this example:

`echo '{{ "foo:bar" | strings.Split ":"}}' | gomplate` which produces `[foo bar]`. 

In order to access a specific item in this list, you would do

`echo '{{ index ("foo:bar" | strings.Split ":") 0 }}' | gomplate` which produces `foo`. 

It was somewhat difficult to figure this out as a new user.

**Comment by hairyhenderson** [comment]
Hi @karlschriek - thanks for filing this! Your PR is excellent - I'll merge it ASAP.
