### ISSUE TITLE
Gomplate failing with  "invalid memory address" on AWS SM if secret was uploaded as SecretBinary

### ISSUE THREAD

**Issue by samm-git** [hairyhenderson/gomplate#1295]
I decided to put (as a binary objects) certificate and key to aws sm and use them from gomplate. However it is now failing

```
$ gomplate -d sm=aws+sm:tls/certificate  -i '{{ (ds "sm" ) }}'
11:03:29 ERR  error="failed to render template <arg>: template: <arg>:1:4: executing \"<arg>\" at <ds \"sm\">: error calling ds: runtime error: invalid memory address or nil pointer dereference"
```
I cant share certificate, but i can later try to emulate this if needed.

**Comment by samm-git** [comment]
Likely the root cause is that secret is put as `"SecretBinary"`

**Comment by samm-git** [comment]
Okay, confirmed. If secret uploaded as SecretBinary gomplate crashing, if as SecretString it works fine. I think it should be at least documented.

**Comment by hairyhenderson** [comment]
Hi @samm-git - thanks for filing this.

This is vaguely documented here: https://docs.gomplate.ca/datasources/#output-1, but I don't think the behaviour is at all reasonable - gomplate should give a reasonable error message rather than crash.

**Comment by hairyhenderson** [comment]
> gomplate should give a reasonable error message rather than crash.

On second thought, I don't see why gomplate shouldn't return the `SecretBinary` when `SecretString` is nil. In gomplate v4 I'll be replacing much of the code with [`go-fsimpl`](https://github.com/hairyhenderson/go-fsimpl), and it takes [this approach](https://github.com/hairyhenderson/go-fsimpl/blob/857ee891b38d4a1496fdc99bed8745abbf0e70af/awssmfs/awssm.go#L220).

**Comment by samm-git** [comment]
Yep, fallback approach is better. While i am here - thank you very much for the tool, it is just amazing. I been using consul-template before, but now have a project w/o consul, so had to find some alternative and found your project. And it is just perfect :)

**Comment by hairyhenderson** [comment]
Thanks for the kind words, @samm-git! I'm glad you're finding gomplate useful 🙇‍♂️
