### ISSUE TITLE
npx gomplate "could not determine executable to run"

### ISSUE THREAD

**Issue by devthejo** [hairyhenderson/gomplate#1297]
the bin is not at the good path in npm package:
here is my current workaround, I had to link it manually
```json
{
  "scripts": {
    "postinstall": "ln -s ../gomplate/node_modules/.bin/gomplate node_modules/.bin/gomplate"
  }
}

**Comment by hairyhenderson** [comment]
Thanks for filing this @devthejo. The npm packaging is actually in a different repo - https://github.com/gomplate/gomplate-npm. I'll see if I can transfer the issue there.

**Comment by hairyhenderson** [comment]
Ah, sorry I can't transfer because it's a different org. @devthejo do you think you could re-file the issue in that repo?

@RecuencoJones helped get that set up, and perhaps could be of greater use in helping to troubleshoot this 🙂

**Comment by devthejo** [comment]
it's done here https://github.com/gomplate/gomplate-npm/issues/8

also many thanks for this great tool you built !!!

**Comment by hairyhenderson** [comment]
Thanks so much @devthejo 🙇‍♂️
