### ISSUE TITLE
Feature request: Ability to do AES-256 CBC encryption

### ISSUE THREAD

**Issue by caleb15** [hairyhenderson/gomplate#1299]
It would be cool if one could use the encryptAES function from [sprig](http://masterminds.github.io/sprig/crypto.html) so that one could encrypt a file in such a way that it can be read in by helm's [decryptAES](https://helm.sh/docs/chart_template_guide/function_list/#decryptaes).

**Comment by caleb15** [comment]
Related issue: https://github.com/hairyhenderson/gomplate/issues/283

**Comment by hairyhenderson** [comment]
Thanks for filing this, @caleb15! This seems like a good idea, and shouldn't be too complex. I expect it'll fit in the [`crypto`](https://docs.gomplate.ca/functions/crypto) function namespace.
