### ISSUE TITLE
Call an external binary when rendering a template to multiple outputs

### ISSUE THREAD

**Issue by mihaitodor** [hairyhenderson/gomplate#1311]
I have a use case where I need to render multiple files from one template, which works great as described in #485. However, I found myself in the awkward situation where the rendered files need to be passed through another templating engine, namely [pug](https://pugjs.org/), which isn't possible currently. What I'm thinking of is to have a function called `os.Exec` like this:

```
{{- range $region := slice "AP" "EU" "US" -}}
{{- $ctx := dict "region" $region }}
{{- $outPath := printf "%s.html" $region }}
{{- tmpl.Exec "mytemplate" $ctx | os.Exec "pug" | file.Write $outPath }}
{{- end -}}
```

I looked at `--exec-pipe`, but it doesn't seem intended for such a use case.

While I can use gomplate to render the `.pug` files and then use bash to walk the directory which contains them recursively, it feels less elegant and I'll need to create a temp folder somewhere...

I can try and put together a PR if you're interested in this addition.

PS: Thank you for this wonderful utility!

**Comment by hairyhenderson** [comment]
Hi @mihaitodor, thanks for filing this. I think the [`--plugin`](https://docs.gomplate.ca/usage/#plugin) functionality will work for you here.

I added plugin functionality as a safer alternative to `os.Exec`, as the ability to execute arbitrary commands in a template is potentially quite dangerous - think of situations where untrusted (or not completely trusted) templates are rendered remotely. With plugins, you can pre-define executables you want to be allowed.

Hopefully this solves the issue for you - let me know if there's anything missing and we can work from there!

**Comment by mihaitodor** [comment]
@hairyhenderson Thank you for the quick reply and for pointing me in the right direction. Can't believe I somehow glossed over the `--plugin` flag 🤦‍♂️ That works perfectly for me! Since you're passing the rendered template to the plugin as a string argument instead of [stdin](https://github.com/hairyhenderson/gomplate/blob/d8f35a0aff0021682ef81a1fbb548f9c5c56a8a9/plugins.go#L83), I ended up writing the following `pug_wrapper.sh` script:

```shell
#!/bin/sh

pug <<EOF
${@}
EOF
```

and I'm using it as the plugin (`--plugin pug="./pug_wrapper.sh"`) which seems to do the trick, but I'll need to do more testing.

Just wondering, is it more common for programs to take their input via a long string arg like `echo` does rather than stdin? I think it might be worth documenting this somehow, because I ended up digging through the code to figure out why `--plugin pug=pug` wasn't working.

**Comment by hairyhenderson** [comment]
Hi @mihaitodor - thanks for the good feedback. When I wrote the plugin support originally the goal was simplicity, and it wasn't immediately obvious how to handle `stdin` in a way that flows well 😉

In code, template pipelines just set the last argument to a function, so both `{{ foo "bar" "baz" }}` and `{{ "baz" | foo "bar" }}` are executed in the same way internally.

One way around this could be to modify the plugin support to optionally set the last argument as `stdin` instead of a positional argument. It shouldn't be the default behaviour (since that breaks backwards compatibility), but it probably wouldn't be _too_ awkward to add another flag... Something like `--plugin-pipe`? Not sure... any ideas?

Either way, I'll definitely update the docs.

**Comment by mihaitodor** [comment]
Thank you for the extra background and clarifications! That makes a lot of sense to me and the documentation changes for `--plugin` make things clear now.

I think having `--plugin-pipe` is worth considering and then people can pick between this and `--plugin` for the programs they wish to use. I think something like `echo` wouldn't work any more if you make the last argument stdin instead of positional.

**Comment by hairyhenderson** [comment]
I'm also realizing that if a template makes use of multiple separate plugins, it may not be desired for all of the plugins to be configured in the same way. For this, I think I can change the plugin configuration (in the YAML config file) to something like:

```
plugins:
  pug:
    cmd: /usr/bin/pug
    pipe: true
    timeout: 400ms
```

Whereas right now the value is a simple string...

Setting a map on the command-line is somewhat tricky, but there's an established pattern for that (with `--datasource` and `--datasource-header`), so I could make `--plugin-pipe` accept a `key=value` format. Oddly, I never added a command-line flag for the timeout parameter. I think I will continue to avoid that unless it's totally necessary 😉

**Comment by mihaitodor** [comment]
Yep, that makes a lot of sense to me :) Once the command line becomes too long, it's great to be able to dump some of the parameters in the config file.
