### ISSUE TITLE
Problem with datasource reading yaml files with directory semantics

### ISSUE THREAD

**Issue by Northburns** [hairyhenderson/gomplate#1333]
I have a template with a datasource which is a directory of yaml files. I followed [the example from documentation "Datasources / Directory datasources"](https://docs.gomplate.ca/datasources/#directory-datasources). I have a problem getting this to work. 

Minimal example to demonstrate, maybe it'll help in helping me understand what's going on 😊

```yaml
# .gomplate.yaml
in: |-
  ** file.read **
  {{ file.Read "data/foo.yaml" | yaml }}
  ** ds **
  {{ ds "data" "foo.yaml" }}
  ** range ds **
  {{ range (ds "data") }}{{ ds "data" . }}
  {{ end }}
datasources:
  data: { url: data/ }
---
# data/foo.yaml
a: 1
b: "c"
```

```sh
 ✨ > gomplate
** file.read **
map[a:1 b:c]
** ds **
map[a:1 b:c]
** range ds **
09:46:54 ERR  error="failed to render template <arg>: template: <arg>:6:26: executing \"<arg>\" at <ds \"data\" .>: error calling ds: Unable to unmarshal array a: 1\r\nb: \"c\"\r\n: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!map into []interface {}"
```

I trust that you can see what is confusing me 😊 My Go is _really_ rusty, but considering that the file is being unmarshalled to `[]interface {}`, I guess this in file `datasource.go` ([link to relevant line in tag `v3.10.0`](https://github.com/hairyhenderson/gomplate/blob/v3.10.0/data/datasource.go#L329)) could be a place of interest:

```go
func parseData(mimeType, s string) (out interface{}, err error) {
	// snip
	case yamlMimetype:
		out, err = YAML(s)
		if err != nil {
			// maybe it's a YAML array
			out, err = YAMLArray(s)
		}
	// snip
}
```

But I'm not very confident in this finding, I didn't take too much time to dig into this yet. I do have a small concern on this snippet ignoring the YAML function's `err`, though 🤷‍♂️

Please let me know if I can help in this issue in any way. I'll circumvent this for now using the file functions. Cheers!

**Comment by hairyhenderson** [comment]
Hmm... this seems to be a bug that's always existed... I'm a bit confused about why, but I'll dig into it.

> I do have a small concern on this snippet ignoring the YAML function's `err`, though 🤷‍♂️

that's a fallback that's only hit if it fails to parse as YAML - from some quick debugging it doesn't seem it's hitting that code at all though... I'll update this issue when I find more.

**Comment by hairyhenderson** [comment]
Ok, I think I have a handle on the issue, and a potential fix. _Coming soon..._
