### ISSUE TITLE
bug: arm64-slim version broken on AWS graviton processors

### ISSUE THREAD

**Issue by janosmiko** [hairyhenderson/gomplate#1348]
Hi,

The arm64-slim version seems to be broken on arm64 processors like AWS Graviton and M1 Mac using an arm64 Docker Container.

I tested it using t4g.large instance with Ubuntu 20.04 ARM64 build. Interestingly it seems to run using armv6-slim and armv7-slim builds.
```
ubuntu@ip-172-31-21-101:~$ uname -a
Linux ip-172-31-21-101 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:04:48 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@ip-172-31-21-101:~$ ./gomplate_linux-arm64-slim --version
PROTubuntu@ip-172-31-21-101:~$ ./gomplate_linux-armv6-slim --version
gomplate version 3.10.0
ubuntu@ip-172-31-21-101:~$ ./gomplate_linux-armv7-slim --version
gomplate version 3.10.0
ubuntu@ip-172-31-21-101:~$ ./gomplate_linux-arm64 --version
gomplate version 3.10.0
```

I can reproduce this issue with the official docker image as well:
```
ubuntu@ip-172-31-21-101:~$ docker run --rm -it hairyhenderson/gomplate:slim -- --version
Unable to find image 'hairyhenderson/gomplate:slim' locally
slim: Pulling from hairyhenderson/gomplate
8cbc5770bfa4: Pull complete
51702981c031: Pull complete
Digest: sha256:f0aeb2f2a17f98b3dde0f77e747bb935a90bee17b71be0bb9b3a10c78814d38c
Status: Downloaded newer image for hairyhenderson/gomplate:slim
PROT_EXEC|PROT_WRITE failed.
```

Related Issue:
https://github.com/rewardenv/reward/issues/17

**Comment by hairyhenderson** [comment]
@janosmiko thanks for reporting this - I think you're saying that the non-slim version works correctly, right?

In v4, I'll no longer be shipping a slim version of the image - too many issues like this for practically no gain... These days the added binary size isn't a big issue, while the slim binary adds a fairly significant performance hit.

**Comment by janosmiko** [comment]
@hairyhenderson yes, the non-slim version worked.

**Comment by hairyhenderson** [comment]
Ok - I think we'll have to leave it at that. This seems like a UPX bug (among many others). Best to just use the regular binaries instead.

**Comment by hairyhenderson** [comment]
Closing as the non-slim binaries work fine and slim are deprecated
