### ISSUE TITLE
yaml.Unmarshal does not support optional string escapes for JSON

### ISSUE THREAD

**Issue by kerma** [hairyhenderson/gomplate#1349]
JSON spec allows optional escape characters for slashes in strings. Some serialize implementations even insert those by default. gomplate is using yaml.Unmarshal for decoding JSON:
https://github.com/hairyhenderson/gomplate/blob/34a4cde1f14e67269171d598717e4f3c36e80cd9/data/data.go#L46-L49

Unfortunately it does not support optional escapes in string: https://github.com/go-yaml/yaml/issues/797

This is causing a confusing error message for the user when json data source is used:
```
yaml: found unknown escape character
```

Simple fix is to replace yaml.Unmarshal with json.Unmarshal. 

Can be reproduced with:

```
$ gomplate -V -d cf=https://api.cloudflare.com/client/v4/ips -i '{{ (ds "cf") }}'                                                                                                                                                               
15:07:28 DBG starting gomplate
15:07:28 DBG config is:
---
in: '{{ (ds "...'
outputFiles: ['-']
leftDelim: '{{'
rightDelim: '}}'
datasources:
  cf:
    header: {}
    url: https://api.cloudflare.com/client/v4/ips
pluginTimeout: 5s
 build=HEAD version=0.0.0
15:07:28 DBG created data from config data="&{ctx:0x14000212ea0 Sources:map[cf:cf=https://api.cloudflare.com/client/v4/ips ()] sourceReaders:map[] cache:map[] extraHeaders:map[]}"
15:07:29 DBG completed rendering duration=1.049753791 errors=1 templatesRendered=0
15:07:29 ERR  error="failed to render template <arg>: template: <arg>:1:4: executing \"<arg>\" at <ds \"cf\">: error calling ds: 
Unable to unmarshal array {\"result\":{\"ipv4_cidrs\":[\"173.245.48.0\\/20\",\"103.21.244.0\\/22\",\"103.22.200.0\\/22\",\"103.31.4.0\\/22\",\"141.101.64.0\\/18\",\"108.162.192.0\\/18\",\"190.93.240.0\\/20\",\"188.114.96.0\\/20\",\"197.234.240.0\\/22\",\"198.41.128.0\\/17\",\"162.158.0.0\\/15\",\"104.16.0.0\\/13\",\"104.24.0.0\\/14\",\"172.64.0.0\\/13\",\"131.0.72.0\\/22\"],\"ipv6_cidrs\":[\"2400:cb00::\\/32\",\"2606:4700::\\/32\",\"2803:f800::\\/32\",\"2405:b500::\\/32\",\"2405:8100::\\/32\",\"2a06:98c0::\\/29\",\"2c0f:f248::\\/32\"],\"etag\":\"38f79d050aa027e3be3865e495dcc9bc\"},\"success\":true,\"errors\":[],\"messages\":[]}: 
yaml: found unknown escape character"
```

**Comment by hairyhenderson** [comment]
Hi @kerma, thanks for filing this. There was a reason that I decided to use `yaml.Unmarshal` to unmarshal both YAML and JSON, though it escapes me now (😅).

Even if JSON data was parsed by `json.Unmarshal` instead, the bug would still exist for YAML which, as a JSON superset, needs to also properly handle `"\/"`.

As an aside, `yq` (also written in Go, but which uses a different YAML library) suffers from the same bug:

```console
$ echo '"hi\/"' | yq .
Error: bad file '-': yaml: found unknown escape character
```

I think the right way to fix this is to fix it upstream in `go-yaml/yaml`.

**Comment by hairyhenderson** [comment]
I've issued a PR to fix this upstream: https://github.com/go-yaml/yaml/pull/862

**Comment by hairyhenderson** [comment]
In #1418 I'm temporarily overriding the `gopkg.in/yaml.v3` module with my commit from https://github.com/go-yaml/yaml/pull/862 - that'll fix this issue in gomplate.
