### ISSUE TITLE
Go1.18 panic due to `assume-no-moving-gc`

### ISSUE THREAD

**Issue by networkop** [hairyhenderson/gomplate#1387]
Hey 👋 ,
There's a problem when I use `github.com/hairyhenderson/gomplate/v3` with Go1.18 that manifests itself like this:
```
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.18 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.18 set. Notably, if go1.18 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /home/user/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20201222180813-1025295fd063/untested.go:24 +0x1f4
exit status 2
```

It looks like the culprit is `inet.af/netaddr`: 

```
go mod why go4.org/unsafe/assume-no-moving-gc
# go4.org/unsafe/assume-no-moving-gc
gnmi
github.com/karimra/gnmic/api
github.com/karimra/gnmic/utils
github.com/hairyhenderson/gomplate/v3
github.com/hairyhenderson/gomplate/v3/funcs
inet.af/netaddr
go4.org/intern
go4.org/unsafe/assume-no-moving-gc
```

I'm not sure if this is the right solution but would you consider moving from  `inet.af/netaddr` to `net/netip`?

**Comment by hairyhenderson** [comment]
Hmm... are you sure you're up-to-date? The `go.mod` in `main` specifies `v0.0.0-20211027215541-db492cf91b37` of that package, which treats 1.18 as safe...

> I'm not sure if this is the right solution but would you consider moving from `inet.af/netaddr` to `net/netip`?

That is the eventual plan, yes. There's a bit of discussion about that in #1342. What's a bit awkward is the API changed a bit so it's a breaking change that may affect people using the gomplate `net.ParseIP*` functions.

**Comment by networkop** [comment]
haha, now I'm sure I'm not. sorry about that, I must've missed that. I'll ask to update the dependencies in the package I use (gnmic).

**Comment by networkop** [comment]
btw, @hairyhenderson were you planning to do a new release any time soon?

**Comment by hairyhenderson** [comment]
@networkop I'm _planning_ on it, but unfortunately I haven't had a lot of free time lately 😞
