### ISSUE TITLE
Make random functions seedable

### ISSUE THREAD

**Issue by jbro** [hairyhenderson/gomplate#1389]
It would be a neat feature to be able to supply a seed for functions using `rand.Reader` (and maybe `math/rand`?).

This would give the option to deterministically generate the same crypto keys and passwords for testing and staging environments, but not having them in the template. This would not add security, but I just think that `{{ crypto.RSAGenerateKey }}` looks nicer than the PEM string written out.

**Comment by hairyhenderson** [comment]
The `crypto` functions use `crypto/rand`, which provides no way to set a seed; it's really just an interface to the system's `/dev/urandom` (or equivalent).

> This would not add security,[...]

Indeed, it would greatly _reduce_ security! I'm not really comfortable with adding any capability to gomplate that would deliberately cripple its security like this. I could definitely imagine someone accidentally leaving this turned on in production.

**Comment by jbro** [comment]
> The `crypto` functions use `crypto/rand`, which provides no way to set a seed; it's really just an interface to the system's `/dev/urandom` (or equivalent).
> 

The functionality could be implemented with by making i custom `rand.Reader`, probably by wrapping a function from `math/rand`, and when a flag is set this would be used instead of the `rand.Reader` from the `crypto` package. 

> > This would not add security,[...]
> 
> Indeed, it would greatly _reduce_ security! I'm not really comfortable with adding any capability to gomplate that would deliberately cripple its security like this. I could definitely imagine someone accidentally leaving this turned on in production.

So I'm thinking it would be enabled with a command line switch ala `--deterministic-random` (a bit of an oxymoron, I know) making it pretty obvious that it is on.

Alternatively, the functionality could be added through a separate package, so that at least it would always that way you wouldn't be in doubt if you chose to use it?

I still think this could be really useful in more than a few cases where you don't need really need the strong property of random, but just the weaker property of unique.

**Comment by hairyhenderson** [comment]
> [...] you don't need really need the strong property of random [...]

All of the cases where gomplate uses `crypto/rand` are cases where people _do_ need cryptographically random input. Generating keys, for example, is exactly one such case.

> So I'm thinking it would be enabled with a command line switch ala `--deterministic-random` (a bit of an oxymoron, I know) making it pretty obvious that it is on.

It may _seem_ that it's obvious, but I've seen enough to know that people will blindly copy/paste things between files without hardly reading them. If it's _possible_ to generate broken keys with gomplate, it will happen, and someone will end up having a very bad day (probably me 😅). The best way to protect people against creating broken keys is to simply not do it in the first place.

> I still think this could be really useful in more than a few cases where you don't need really need the strong property of random, but just the weaker property of unique.

It's not like `math/rand` is significantly faster than `crypto/rand`, so why would you sacrifice security unnecessarily?

**Comment by jbro** [comment]
> It may _seem_ that it's obvious, but I've seen enough to know that people will blindly copy/paste things between files without hardly reading them. If it's _possible_ to generate broken keys with gomplate, it will happen, and someone will end up having a very bad day (probably me sweat_smile). The best way to protect people against creating broken keys is to simply not do it in the first place.
> 

That's true and a very valid point.

> > I still think this could be really useful in more than a few cases where you don't need really need the strong property of random, but just the weaker property of unique.
> 
> It's not like `math/rand` is significantly faster than `crypto/rand`, so why would you sacrifice security unnecessarily?

Oh, I'd still use `rand.Reader` from the crypto package in the default mode. I just meant that since `math/rand` is seedable, it could be a good basis for a deterministic `rand.Reader`.

The use case for this could go something like this. I have some VMs (or and embeded system) and use a gomplate to generate a private key and an initial seed for `/dev/random`. Now I want the key and the seed to be unique per system, and that's currently easy to a high degree of certainty as it is now because we use `rand.Reader` from the crypto package. However, I also have a test deployment which I'd like to deploy using the same tools as in production, but I would like it to come up with the same keys every time I redeploy it. This is of course possible, as it is now, by just generating the key and seed once  and putting that into a development gomplate in place of the functions used to generate the same things in production. I just think it would be neat if I could say `gomplate --super-unsafe-deterministic-random-do-not-use-in-production-ever-even-if-you-think-you-know-what-you-are-doing --seed 42` and have the result be the same every time, even if the template contains a call to something that should be random under normal circumstances.

**Comment by hairyhenderson** [comment]
Thanks for the elaboration - the use case sounds interesting, but IMO not really the right way around the issue.
