### ISSUE TITLE
slice

### ISSUE THREAD

**Issue by kellerza** [hairyhenderson/gomplate#1461]
Maybe I'm missing something fundamental, but how do we do text\template's `slice` in gomplate?

Global [functions](https://pkg.go.dev/text/template#hdr-Functions)
```
slice
	slice returns the result of slicing its first argument by the
	remaining arguments. Thus "slice x 1 2" is, in Go syntax, x[1:2],
	while "slice x" is x[:], "slice x 1" is x[1:], and "slice x 1 2 3"
	is x[1:2:3]. The first argument must be a string, slice, or array
```

[col.Slice](https://docs.gomplate.ca/functions/coll/#coll-slice) seems fundamentally different

**Comment by kellerza** [comment]
We use for network config templates in containerlab (pick octets from IP addresses, pick characters in a string, split strings etc). 

For now we’ll remove the slice shortcut from gomplates functions. Then we can still use Coll.Slice if I understand it correctly?

https://github.com/srl-labs/containerlab/pull/949

**Comment by kellerza** [comment]
Fair point about gomplate being first 😁

**Comment by hairyhenderson** [comment]
> [...] pick octets from IP addresses, 

I wonder if some functions in [the `net` namespace](https://docs.gomplate.ca/functions/net/) would be more useful for dealing with IP addresses?

> [...] pick characters in a string,

This probably needs Go's `slice`!

> [...] split strings etc

For splitting, you'd probably want to use [`strings.Split`](https://docs.gomplate.ca/functions/strings/#strings-split) anyway, wouldn't you?

I think the best course of action for gomplate would be to deprecate the `slice` alias, and add a new function (maybe `coll.GoSlice`?) to expose Go's `slice` function. The goal would then be to remove the `slice` alias in a [future major release](https://github.com/hairyhenderson/gomplate/blob/main/CONTRIBUTING.md#versioning-api-and-deprecation).

**Comment by tewfik-ghariani** [comment]
Hello, thanks for adding support for the `coll.GoSlice` feature! ^^

Is there a plan to release a new version?

**Comment by hairyhenderson** [comment]
@tewfik-ghariani my original plan was to just include it in gomplate 4.0, but it's taking a lot longer than anticipated to get that release ready. The current state of the `main` branch makes it a bit difficult to release another 3.x version with this new feature, and I simply don't have a lot of spare time right now to dedicate to this.

For now, if you really need that function, you could compile gomplate yourself from source.

**Comment by hairyhenderson** [comment]
I'm also going to close this issue since #1464 fixed it.
