### ISSUE TITLE
Support Go 1.19

### ISSUE THREAD

**Issue by andig** [hairyhenderson/gomplate#1467]
https://github.com/Homebrew/homebrew-core/pull/107165 fails due to 

    panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.

This can be fixed by upgrading go4.org/unsafe/assume-no-moving-gc according to https://github.com/lucas-clemente/quic-go/issues/3491

**Comment by hairyhenderson** [comment]
Thanks for the heads-up @andig 🙇‍♂️

I'll fix this soon.

**Comment by hairyhenderson** [comment]
Fix coming up in https://github.com/hairyhenderson/gomplate/pull/1468

**Comment by hairyhenderson** [comment]
3.11.x backport in #1469. Will try to get a 3.11.2 release out soon so the hack in https://github.com/Homebrew/homebrew-core/pull/107165 isn't necessary.
