### ISSUE TITLE
Consider breaking the gomplate cmd into a sub-package

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#147]
As suggested by @sean- originally in https://github.com/hairyhenderson/gomplate/issues/145#issuecomment-303430012:

> Have you thought about breaking `gomplate` into a sub-package like `github.com/hairyhenderson/gomplate/cmd/gomplate` so that the "gomplate" template library could be the meta-library used to aggregate a bunch of different APIs and helper functions? It's pretty easy for me to see that this would be useful to embed in standalone programs. "Dear `gomplate`, please render my string." Either `gomplate(1)` or the library `github.com/hairyhenderson/gomplate`.

🤔

**Comment by nickjackson** [comment]
Yeah, this would be really helpful. I'm looking to create a cmd line scaffolding tool for my team, and leveraging gomplate would take a lot of the heavy lifting away.
