### ISSUE TITLE
microbadger.com links are dead.

### ISSUE THREAD

**Issue by dngray** [hairyhenderson/gomplate#1479]
https://github.com/hairyhenderson/gomplate/blob/8301be940cf50648ae3ed16beb2ec350d19298d8/README.md?plain=1#L126-L129

These don't appear to go anywhere.

**Comment by hairyhenderson** [comment]
Ah, thanks @dngray - seems that site shut down a long time ago and now points ...somewhere else... 🤦‍♂️

I'll remove these.
