### ISSUE TITLE
HTTP datasource subpath

### ISSUE THREAD

**Issue by tuukkaanttila** [hairyhenderson/gomplate#1492]
Similar to how Vault data source works, it would be nice if you could specify a "subpath" for HTTP datasources.

e.g. {{ (ds "my_secret_server" "/just/this/secret").Value }}

Perhaps the "subpath" inside the template could simply be concatenated to the configured datasource.

**Comment by hairyhenderson** [comment]
@tuukkaanttila that should already work...

Have you tried this out? Do you get any errors?

Here's an example I just tried out:

```console
$ gomplate -d data=https://httpbin.org -i '{{ $resp := ds "data" "get" }}The URL was: {{ $resp.url }}'
The URL was: https://httpbin.org/get
```

Given that this is already supported, I'm going to close this. Feel free to start a [discussion](https://github.com/hairyhenderson/gomplate/discussions) if you need more help with it, or re-open if you're seeing bugs with it.

**Comment by tuukkaanttila** [comment]
`gomplate -d data=https://httpbin.org -i '{{ $resp := ds "data" "get" }}'`

This indeed seems to work on linux. With powershell there is some (quoting/escaping related?) weirdness that made it not work for me, but can be solved by reading from file.
