### ISSUE TITLE
External command datasource

### ISSUE THREAD

**Issue by tuukkaanttila** [hairyhenderson/gomplate#1493]
Idea: Using the command line to get config values.

e.g.
{{ (ds "script" "/sub/path") }}

gomplate -d script="gopass show --password \$subpath"

**Comment by hairyhenderson** [comment]
Hi @tuukkaanttila, I think [plugins](https://docs.gomplate.ca/usage/#plugin) are what you're looking for?

**Comment by tuukkaanttila** [comment]
Yes, it works perfectly!

Thank you!
