### ISSUE TITLE
is there a way to check mutiple level of "if has key" at once?

### ISSUE THREAD

**Issue by WalkerWalker** [hairyhenderson/gomplate#1497]
currently i have the following and it works.
```
    {{- if has .A "B" }}
    {{- if has .A.B "C" }}
    {{- if has .A.B.C "D" }}
      hello: {{ .A.B.C.D }}
    {{- end}}
    {{- end}}
    {{- end}}
```

is there a way to check just once if `.A.B.C.D` is valid or not?

**Comment by hairyhenderson** [comment]
Hi @WalkerWalker, no, currently this isn't possible. You could shorten this however by using `and`:

```go
{{- if and (has .A "B") (has .A.B "C") (has .A.B.C "D") }}
  hello: {{ .A.B.C.D }}
{{- end }}
```

From the [doc for `and`](https://pkg.go.dev/text/template#hdr-Functions):

```
        Returns the boolean AND of its arguments by returning the
	first empty argument or the last argument. That is,
	"and x y" behaves as "if x then y else x."
	Evaluation proceeds through the arguments left to right
	and returns when the result is determined.
```

Another potential approach could be to use [`coll.JSONPath`](https://docs.gomplate.ca/functions/coll/#coll-jsonpath) - perhaps there's a JSONPath expression that could be used to do this? I'm not very experienced with JSONPath itself though so I won't be able to help on this... Besides, that'll probably end up more complicated than just using `and` and `has` 😉

**Comment by hairyhenderson** [comment]
I'm going to close this for now. If there's any followup please feel free to start a [discussion](https://github.com/hairyhenderson/gomplate/discussions)!

**Comment by thesuperzapper** [comment]
@hairyhenderson we can probably implement a feature like [helm's `dig`](https://helm.sh/docs/chart_template_guide/function_list/#dig), which I think comes from [sprig](https://masterminds.github.io/sprig/).

This would allow people to un-nest objects/dicts using: 

```
dig "user" "role" "humanName" "guest" $dict
```

For a `$dict` that looks like:

```
{
  user: {
    role: {
      humanName: "curator"
    }
  }
}
```

**Comment by hairyhenderson** [comment]
@thesuperzapper Interesting! That seems like a good idea. Would you mind filing a separate issue for that?

**Comment by thesuperzapper** [comment]
@hairyhenderson I have raised an issue in https://github.com/hairyhenderson/gomplate/issues/1775
