### ISSUE TITLE
Invalid documentation for `coll.GoSlice`

### ISSUE THREAD

**Issue by vitoyucepi** [hairyhenderson/gomplate#1517]
## Summary
In #1464 `coll.GoSlice` was introduced, but example for that function uses `coll.Slice` instead.

https://github.com/hairyhenderson/gomplate/blob/a796a2531311833f8203379ccef380ecabc129c7/docs/content/functions/coll.md?plain=1#L112-L127

**Comment by hairyhenderson** [comment]
Thanks for filing this @vitoyucepi!

This is indeed a bug. I'll fix the docs soon.

Note that this is a new function that hasn't made its way into a release yet, so you'll have to compile gomplate yourself to be able to use it.

**Comment by vitoyucepi** [comment]
I have no plans to use this feature yet.
I came here because the `slice` function was deprecated in #1464. I use it in `{{ tmpl.Exec "sometemplate" (slice "val1" "val2") }}`.
Though I think it'll be acceptable to use `coll.Slice` instead.

**Comment by hairyhenderson** [comment]
> Though I think it'll be acceptable to use `coll.Slice` instead.

Yup, exactly. `coll.Slice` is what you want where you used to use `slice`
