### ISSUE TITLE
Accept arguments for command in plugin definition

### ISSUE THREAD

**Issue by danielkza** [hairyhenderson/gomplate#1552]
Currently plugin definitions only accept an executable, so there is no way to pass some pre-defined arguments to precede the ones from the template invocation.

As a (somewhat contrived) example, If i want a plugin to evaluate a python expression, I should be able to do:

```yaml
plugins:
  py: ["python3", "-c"]
```

```tmpl
{{ py "print('Hello, world')" }}
``` 

So that I don't need to have `"-c"` in every invocation.

**Comment by danielkza** [comment]
Other ways to define it in the config could also work nicely:

```yaml
plugins:
  py:
    cmd: python3
    args: ["-c"]
```

**Comment by hairyhenderson** [comment]
Thanks for filing this @danielkza (and sorry for the delay!).

The `args` option seems reasonable.
