### ISSUE TITLE
`jsonpath` "deep scan" differs from jsonpath specification

### ISSUE THREAD

**Issue by djmcgreal-cc** [hairyhenderson/gomplate#1558]
https://support.smartbear.com/readyapi/docs/testing/jsonpath-reference.html though the ietf spec was harder to parse, and may not agree.

> `..property` Performs a deep scan for the specified property in all available objects. **Always returns a list, even for a single match.**

But, in gomplate, `{{ dict "foo" (dict "bar" "baz") | jsonpath "..bar" }}` returns a string, "baz".

Whereas, `{{ dict "foo" (dict "bar" "baz") "xyz" (dict "bar" "qwe") | jsonpath "..bar" }}` correctly returns a list.

The behaviour where a list is always returned is much easier to work with.

**Comment by hairyhenderson** [comment]
Thanks for filing this, @djmcgreal-cc

gomplate just defers to the https://pkg.go.dev/k8s.io/client-go/util/jsonpath library, which is the same used by the Kubernetes client. According to its docs, it follows the syntax specified at https://goessner.net/articles/JsonPath/. Unfortunately I can't find much about how the descendant operator (`..`) _should_ work, only that it's equivalent to the XPath `//` operator.

**Comment by djmcgreal-cc** [comment]
You're welcome. Thanks for the tool :)

I'll bear this in mind while working with `kubectl --output jsonpath`.

Thanks again

**Comment by hairyhenderson** [comment]
Given I don't think there's any action to be taken here, I'm going to close this! Feel free to re-open if that changes.
