### ISSUE TITLE
Suggestion: add directory support for loading environment

### ISSUE THREAD

**Issue by reddec** [hairyhenderson/gomplate#159]
Good day!

I kindly ask you to think about feature, that will help many people use this excellent tool for big projects with huge count of separated configuration files: load in one alias all supported files in specified dir.

I mean will be a great idea to have something like this `--datasource base=base.yaml conf=path/to/prod/dir/` where in `path/to/prod/dir/` there are configuration files like `servers.yaml`, `connections.toml` and `users.csv` (Just for examples)

**Comment by hairyhenderson** [comment]
Thanks for logging this, @reddec! I'm not sure I fully understand the use-case - would #124 meet your needs?

**Comment by reddec** [comment]
Yes, it's looks the same. Sorry
