### ISSUE TITLE
panic: template: template:19:25: executing "template" at <.Env>: map has no entry for key "Env"

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#160]
Using `.Env` within range produces the following error:

```
panic: template: template:19:25: executing "template" at <.Env>: map has no entry for key "Env"
```

Example:
```
{{ range (datasource "gomplate").foobar }}
{{ .Env.FOOBAR }}
{{ end }}
```

**Comment by hairyhenderson** [comment]
Ah. yep. This is because the meaning of `.` changes within `range`. Probably the simplest way to resolve this is by using `getenv` instead of `.Env`:

```
{{ range (datasource "gomplate").foobar }}
{{ getenv "FOOBAR" }}
{{ end }}
```

**Comment by estahn** [comment]
Yes, that's what I've done. But I would have liked the fail-feature in case a variable is not set :)

**Comment by hairyhenderson** [comment]
@estahn ah - well another option could be something like:

```golang
{{ $root := . }}
{{ range (datasource "gomplate").foobar }}
{{ $root.Env.FOOBAR }}
{{ end }}
```

Hope that helps!
