### ISSUE TITLE
please add cue as a native format

### ISSUE THREAD

**Issue by kghenderson** [hairyhenderson/gomplate#1601]
[CUE](https://cuelang.org) is an intelligent configuration language and is a Go package.
We have many CUE files which are very clean and simple to manage, as well as some gomplate templates.
It would be really great if we could import these files directly without needing a cue to json pre-processing step.
thank you for considering.

**Comment by hairyhenderson** [comment]
Hey @kghenderson, thanks for filing this!

I'm totally on board with CUE support.

**Comment by kghenderson** [comment]
nice! you know I got free tickets to see harry & the henderson's movie when I was a little kid. I think they knew that if I was going to be tormented at school for it, I might as well get to see it for free 🤷

**Comment by hairyhenderson** [comment]
😂

**Comment by kghenderson** [comment]
haha, yeah, good times :-) 

fyi, i also created a companion issue over here: 
https://github.com/cue-lang/cue/issues/2212

**Comment by hairyhenderson** [comment]
I'm guessing this is still desired? I don't have any objection, but I don't personally have time to do this any time soon.

**Comment by kghenderson** [comment]
yes, it's still desired, no worries about the time - i can try this myself at some point but don't have time now either :-/

**Comment by kghenderson** [comment]
bump to keep alive, still an avid gomplate user :-)

**Comment by hairyhenderson** [comment]
@kghenderson I see the https://github.com/cue-lang/cue/issues/2212 issue - does that need to exist? I'm not sure how it's relevant to the CUE-lang project itself...

**Comment by hairyhenderson** [comment]
Oh, also - @kghenderson would you be able to share some examples (anonymized if you need) of your current workflow? Specifically I'm interested in what you're doing now as your cue-to-json preprocessing step.

**Comment by adriens** [comment]
I had never heard about `cue` but I'm also very interested in this tool. As we use `gomplate` I think this could be add significant benefits to our toolchain :thinking: :star_struck:

**Comment by hairyhenderson** [comment]
I've been toying around with what CUE support could look like in https://github.com/hairyhenderson/gomplate/pull/1781. There are a few things that CUE supports that might be a bit challenging to implement (most notably the ability to import from other files), but otherwise it's relatively straightforward.
