### ISSUE TITLE
Add ability to disable or rename the special `type` query parameter

### ISSUE THREAD

**Issue by dbluxo** [hairyhenderson/gomplate#1606]
Hey :wave:,

I'm trying to set a query parameter for an http datasource:

What works:

`gomplate -d repos=https://<redacted>/api/repositories`

What does not work:

`gomplate -d repos=https://<redacted>/api/repositories?type=local `

How to set `?type=local` for the http datasource?

Thanks!

**Comment by hairyhenderson** [comment]
@dbluxo can you clarify what "does not work" means here?

The `type` parameter is interpreted by gomplate to act as a media type hint for processing the result, so setting it to a non-MIME-type will probably break parsing.

This definitely feels like an unexpected edge-case, but it was bound to hit someone eventually 😓

**Comment by hairyhenderson** [comment]
I guess one workaround would be to use `include` instead of `datasource`/`ds` in your template to avoid parsing the data, and then parse it later specifically as the expected format with the appropriate [`data`](https://docs.gomplate.ca/functions/data/) function.

For example:

```
{{ $parsed := include "repos" | data.JSON }}
```
