### ISSUE TITLE
JSON formatting

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#163]
The following will not pass YAML lint at the moment:

```
foo:
  bar: {{ `["foo", "bar"]` | json | toJSON }}
```

**Expected Result:**
```
foo:
  bar: ["foo", "bar"]
```

**Actual Result:**
```
foo:
  bar: ["foo","bar"]
```

**Comment by hairyhenderson** [comment]
I'm not sure what the issue is here - your listed "Actual" is valid YAML.

**Comment by estahn** [comment]
Yes, it's valid YAML according to the standard. We use YAML lint to check outputs and it complaints about the whitespace not existing:

http://yamllint.readthedocs.io/en/latest/rules.html#module-yamllint.rules.commas

**Comment by hairyhenderson** [comment]
Ok, I see. The purpose of the `toJSON` function is to marshal as JSON, and more specifically, as _compact_ JSON (i.e. without any separating whitespace). The other option is to use `toJSONPretty`, but it would render the array across multiple lines:

```console
$ gomplate -i '{{ `["foo", "bar"]` | jsonArray | toJSONPretty "  " }}'
[
  "foo",
  "bar"
]
```

Other than that, `gomplate` simply isn't going to produce YAML that satisfies your particular linter.

**Comment by estahn** [comment]
@hairyhenderson Fair enough, although the linter it's neither mine nor particular :)

**Comment by hairyhenderson** [comment]
Ok, then instead of "your particular linter" read "the linter you're choosing to use, with its particular configuration" 😉
