### ISSUE TITLE
missing docker manifest for v3.11.4 

### ISSUE THREAD

**Issue by Fabian-K** [hairyhenderson/gomplate#1652]
Hi,

we are using the docker image hairyhenderson/gomplate as part of our ci pipeline and face a strange issue that seems to be related to the docker image manifest. 

`duplicate unique image found for platform: unknown/unknown: found sha256:5f2142b3bfc923b4f34805f61e73b47b8948c22fe21578f2331ba0d6f006e5bd and sha256:156980dbc3ee7a13b555440de275c4f3083c786b04a95f67fec5207a55b191eb.`

I don´t fully understand what is the issue... I´m guessing something went wrong during the publication of v3.11.4 because I noticed that I can successfully get the manifest for 3.11.3 via `docker manifest inspect hairyhenderson/gomplate:v3.11.3` 

However the same fails for 3.11.4 via `docker manifest inspect hairyhenderson/gomplate:v3.11.4`. It returns `no such manifest: docker.io/hairyhenderson/gomplate:v3.11.4`.

Have you seen something like this before?

Thanks, Fabian

**Comment by hairyhenderson** [comment]
Which container runtime are you using?

One possible cause is this recent change with [Docker BuildX v0.10.2](https://github.com/docker/buildx/releases/tag/v0.10.2):

> Buildx v0.10 enables support for a minimal [SLSA Provenance](https://slsa.dev/provenance/) attestation, which requires support for [OCI-compliant](https://github.com/opencontainers/image-spec) multi-platform images. This may introduce issues with registry and runtime support (e.g. https://github.com/docker/buildx/issues/1533). You can optionally disable the default provenance attestation functionality using --provenance=false.

It's also possible something went wrong when I built the Docker images for this release - I'll look into it!

**Comment by thaJeztah** [comment]
Likely related to `docker manifest` not supporting OCI (on docker 20.10 and older); that part should be addressed in docker cli 23.0; see https://github.com/docker/cli/pull/3990


If you have buildx installed, you can use `docker buildx imagetools inspect` as a workaround, or update to docker 23.0 (not yet included in docker desktop though)

**Comment by hairyhenderson** [comment]
just came to post the same:

```
$ docker buildx imagetools inspect hairyhenderson/gomplate:v3.11.4       
Name:      docker.io/hairyhenderson/gomplate:v3.11.4
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:418c33d559eca24ee820b416a12e7c2bb2a16f4e89ead548522f055c30a824fd
           
Manifests: 
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:dde9ec99e3039a93a100131ed107207f0fd10cb4e4a88b1c89953c96cd56a128
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/amd64
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:3c4312a22a827656d61809b1a74d6defe610c21a5f271b0002a5384c4476cde5
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/arm64
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:4698c176750f053ff14a16cffd225fe66628702f1221763adf67efd0569e8a0c
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/arm/v6
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:067790a20e78e549b3dbc2e1c9c393edf2f9b0a5d7217d8cd6855790423b5587
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/arm/v7
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:8fa4df46d5a9dfe20be1b9de543c50195179e739c8ead15f40e15ece80cc9cdf
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    windows/amd64
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:5f2142b3bfc923b4f34805f61e73b47b8948c22fe21578f2331ba0d6f006e5bd
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:dde9ec99e3039a93a100131ed107207f0fd10cb4e4a88b1c89953c96cd56a128
    vnd.docker.reference.type:   attestation-manifest
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:156980dbc3ee7a13b555440de275c4f3083c786b04a95f67fec5207a55b191eb
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:3c4312a22a827656d61809b1a74d6defe610c21a5f271b0002a5384c4476cde5
    vnd.docker.reference.type:   attestation-manifest
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:bfccb3f95faab4d53c0b80322746485dfc5bef11177df7238e0d78eb7038af58
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:4698c176750f053ff14a16cffd225fe66628702f1221763adf67efd0569e8a0c
    vnd.docker.reference.type:   attestation-manifest
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:8eeebd5c8f5f6285cdfe3c095e6b0cc5dfa85d076a60b86caab178802c295015
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:067790a20e78e549b3dbc2e1c9c393edf2f9b0a5d7217d8cd6855790423b5587
    vnd.docker.reference.type:   attestation-manifest
               
  Name:        docker.io/hairyhenderson/gomplate:v3.11.4@sha256:e61bd1f154772cbcb7187364f434277348bb319296f4d4de8f6c3a1afd282d6f
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.type:   attestation-manifest
    vnd.docker.reference.digest: sha256:8fa4df46d5a9dfe20be1b9de543c50195179e739c8ead15f40e15ece80cc9cdf
```

**Comment by Fabian-K** [comment]
Thanks a lot for the input! Our ci pipeline is based on https://github.com/tektoncd/pipeline, the nodes executing it are using containerd as the runtime. With the new information, this seems to be an issue on tekton side and not something with the images themselves. I´ll follow up on this with the tekton project :)

**Comment by hairyhenderson** [comment]
Thanks for confirming @Fabian-K!

I'll close this for now as there's no action to be taken.
