### ISSUE TITLE
etcd support

### ISSUE THREAD

**Issue by sivann** [hairyhenderson/gomplate#1663]
As I understand etcd is not supported, would it be possible to support it? etcd is now a popular choice. The alternative is doing constant conversions to/from yaml to support interfacing with gomplate. Or am I missing something obvious?

**Comment by hairyhenderson** [comment]
> The alternative is doing constant conversions to/from yaml to support interfacing with gomplate.

I'm not sure I fully understand what you mean here?

Either way, I'm open to etcd support, but it would have to be added to https://github.com/hairyhenderson/go-fsimpl first - all gomplate datasources will be read using that library as of the next release (v4.0.0).

**Comment by sivann** [comment]
Yes I wasn't clear, I would like etcd support as datasource as you understood correctly. For the conversions, it's what we do to support having etcd to store app configuration for apps that want configuration in file formats. So we convert e.g. etcd->yaml datasource and provide this to gomplate as input. I will add this request to go-fsimple then, thank you
