### ISSUE TITLE
PPC64 build missing from the latest release

### ISSUE THREAD

**Issue by sagikazarmark** [hairyhenderson/gomplate#1666]
Looks like the ppc64 build is missing from the latest release: https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.4

**Comment by hairyhenderson** [comment]
So it is... The ppc64 build isn't automated as part of the 3.x releases so last time I had to build it manually.

Will do that soon.

**Comment by hairyhenderson** [comment]
@sagikazarmark I've uploaded it here: https://github.com/hairyhenderson/gomplate/releases/download/v3.11.4/gomplate_linux-ppc64le

**Comment by sagikazarmark** [comment]
Perfect, thank you!

**Comment by hairyhenderson** [comment]
you're welcome! I've also updated the `3.11.x` branch to build that platform now, so if there's ever a 3.11.5 release it will contain that 😉 - https://github.com/hairyhenderson/gomplate/commit/ea986e7404d1dcacf41d6a9afea306da915c95fe
