### ISSUE TITLE
Gomplate function to output a gomplate function

### ISSUE THREAD

**Issue by seriousben** [hairyhenderson/gomplate#167]
This is a bit meta, but I have template files generating config files containing gomplate functions in them :)

Command:
```
gomplate < template.tmpl
```

Broken template:
```
VERSION=$(gomplate -d package.json -i '{{ (ds "package").version }}'
```
Working template (Workaround):
```
VERSION=$(gomplate -d package.json -i '{{"{{"}} (ds "package").version {{"}}"}}'
```
Propositions:
```
VERSION=$(gomplate -d package.json -i '{{ gomplate "(ds \"package\").version" }}'
```
or
```
VERSION=$(gomplate -d package.json -i '{{ gomplate `(ds "package").version` }}'
```

**Edit 1**: Adding gomplate command using the templates

**Comment by hairyhenderson** [comment]
lol!

I wonder if simply setting the delimiters to something different would make that easier? See https://gomplate.hairyhenderson.ca/usage/#overriding-the-template-delimiters

**Comment by hairyhenderson** [comment]
actually - what output are you expecting out of this? just `{{ (ds "package").version }}`? If so, why are you specifying a datasource?

**Comment by seriousben** [comment]
Yeah, I wondered about the delimiters but I felt it would be more confusing to deal with two different delimiters.

**Comment by seriousben** [comment]
added a command in the description to hopefully make things clearer.

**Comment by seriousben** [comment]
🍡

**Comment by seriousben** [comment]
overriding template delimiters is enough for me. Thanks.
