### ISSUE TITLE
output-map not working with external template

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#1686]
### Discussed in https://github.com/hairyhenderson/gomplate/discussions/1676

<div type='discussions-op-text'>

<sup>Originally posted by **dgarlitt** March 15, 2023</sup>
I was following the documentation [here](https://docs.gomplate.ca/usage/#referencing-complex-output-map-template-files) to learn how to use `--output-map` with external templates. I created the `out.t` file as indicated:

_out.t_
```go
{{- /* .in may contain a directory name - we want to preserve that */ -}}
{{ $f := filepath.Base .in -}}
out/{{ .in | strings.ReplaceAll $f (index .filemap $f) }}.out
```

as well as the filemap.json file:

_filemap.json_
```json
{ "eins.txt": "uno", "deux.txt": "dos" }
```

and stored my templates in the `in` directory. However, when I run the command in the example:

```shell
gomplate -t out=out.t -c filemap.json --input-dir=in --output-map='{{ template "out" }}'
``` 

I get the following error:

```shell
ERR  error="failed to gather templates for rendering: failed to render outputMap with ctx &map[ctx:0xc000a4e1b0 filemap:map[deux.txt:dos eins.txt:uno] in:deux.txt] and inPath deux.txt: failed to render template <OutputMap>: template: out:2:7: executing \"out\" at <.in>: nil data; no entry for key \"in\""
```

I am sure that I have a basic misunderstanding. Can someone please help point me in the right direction?</div>

**Comment by hairyhenderson** [comment]
My response:

> Hi @dgarlitt, thanks for reporting this - it looks like this is at least a bug in the documentation, and likely also a bug with how nested templates interact with output maps.
>
> I tested this with various gomplate versions all the way back to v3.4.0 (when the output-map feature was added), and I get the same error too.

**Comment by thesuperzapper** [comment]
@hairyhenderson are you sure you did not just forget to provide the context to the template, that is:

- GOOD: `--output-map='{{ template "out" . }}'` 
- BAD: `--output-map='{{ template "out" }}'`

**Comment by hairyhenderson** [comment]
😂 thanks so much @thesuperzapper - that's the issue!
