### ISSUE TITLE
net.ParsePrefix error

### ISSUE THREAD

**Issue by giorgiga** [hairyhenderson/gomplate#1696]
The example from https://docs.gomplate.ca/functions/net/ errors out:

    $ gomplate -i '{{ (net.ParsePrefix "192.168.0.0/24").Range }}'
    22:15:09 ERR  error="failed to render template <arg>: template: <arg>:1:4: executing \"<arg>\" at <net>: can't evaluate field ParsePrefix in type interface {}"

It may very well be just my system (I've just intalled gomplate version 3.11.4 via nix on tumbleweed).

Is there some way to get a more meaningful error?

**Comment by hairyhenderson** [comment]
Unfortunately `net.ParsePrefix` is not available in 3.11. It'll be available in 4.0.

Sorry about the confusion - I really need to figure out a way for the docs to reflect only the released version 😞
