### ISSUE TITLE
Consider supporting reusing keepalive connections

### ISSUE THREAD

**Issue by seriousben** [hairyhenderson/gomplate#170]
Reusing an `http.Transport` in the `http.Client` would allow reusing connections. 

https://golang.org/src/net/http/transport.go

This would be useful for some datasource doing multiple queries like vault. 

Also to keep in mind:
>   The http Client and Transport guarantee that Body is always non-nil, even on responses without a body or responses with a zero-length body. It is the caller's responsibility to close Body. The default HTTP client's Transport does not attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections ("keep-alive") unless the Body is read to completion and is closed. (https://golang.org/pkg/net/http/#Response)

**Comment by danedmunds** [comment]
@hairyhenderson I'd like to tackle this as part of hacktoberfest!

**Comment by hairyhenderson** [comment]
@danedmunds it's all yours

**Comment by hairyhenderson** [comment]
I think this is no longer relevant, but if there's something I'm missing, feel free to open a new issue!
