### ISSUE TITLE
Feature request: straightforward way to include templates

### ISSUE THREAD

**Issue by giorgiga** [hairyhenderson/gomplate#1707]
(Please note I might be very well missing something, as it seems unlikely that such a feature does not exist)

At the moment to include a template in another one must

````
{{ tmpl.Inline ( filepath.Join tmpl.PathDir "../../../includes/etc-config-system-ntp.inc" | file.Read ) }}
````

Since includes are the simplest way to organize code, it would IMHO be desirable to have a more straighfortward way to include ("call"? "render"?) a template from another.

Eg:

````
{{ tmpl.ExecFile "../../../includes/etc-config-system-ntp.inc" $context }
````

**Comment by giorgiga** [comment]
Addendum:

A nice and elegant way to define new variables for the included template would be great too... I need to pass variables to a template (without overriding `$`) and ended up with this abomination:

````
{{ tmpl.Inline ( filepath.Join tmpl.PathDir "../../../includes/etc-config-wireless-2g.inc" | file.Read )
               ( coll.Merge $ (data.YAML "from_parent_template: { radio_name: radio0 }") ) -}}
````

(in case you wonder about the context, I'm generating config files for various openwrt routers/wifi aps based on a common config file that describes my networks)

**Comment by hairyhenderson** [comment]
Hi @giorgiga,

> (Please note I might be very well missing something, as it seems unlikely that such a feature does not exist)

Have a look at these [nested templates docs](https://docs.gomplate.ca/syntax/#nested-templates).

Provide a template from a different file with the [`--template` flag](https://docs.gomplate.ca/usage/#template-t) (or in the config file's [`templates`](https://docs.gomplate.ca/config/#templates) section), then include it with the `template` action or [`tmpl.Exec`](https://docs.gomplate.ca/functions/tmpl/#tmpl-exec).

> A nice and elegant way to define new variables for the included template would be great too...

Generally when calling other templates I've provided only the data required by that template (i.e. I haven't passed in `.` or `$`), so merging isn't something I've needed to do...

Have a look at [`coll.Dict`](https://docs.gomplate.ca/functions/coll/#coll-dict) and [`coll.Slice`](https://docs.gomplate.ca/functions/coll/#coll-slice-deprecated) - these may be useful for creating data structures on the fly.


> I'm generating config files for various openwrt routers/wifi aps based on a common config file that describes my networks

This sounds like a really cool use-case! Thanks for sharing - I'm always interested in hearing how people use gomplate 🙂
