### ISSUE TITLE
Feature request: add crypto.MD5

### ISSUE THREAD

**Issue by giorgiga** [hairyhenderson/gomplate#1709]
MD5 is outdated but still has its (niche?) applications; having a function similar to the crypto.SHA* ones for MD5 would be great.

**Comment by giorgiga** [comment]
I'm not a security engineer, but AFAIK the problem with MD5 is essentially that it is not infeasible to search for collisions (values that have the same hash).

Suppose you have an account on a site that stores password hashes based on MD5 (regardless of salt): I don't necessarily need your *exact* password to break into your account, as any password that hashes to the same thing as yours will do.

In this regard MD5 is not inherently different than any other hash function... it's just that since it produces shorter hashes it is more vulnerable that others (SHA1 is also discouraged for secure applications, for the same reasons as MD5). 

Regardless of this, MD5 still has its applications in other domains (eg. rsync uses MD5 checksums to verify transfers and `.md5` files are often used in file repositories for the same purpose).

On top of that, I am sure a lot of legacy systems still use MD5 even for secure applications, and so one may need the function to interface with them (I remember setting up ecommerce payments with a bank that used HMAC-MD5 to sign messages - that was around 2015 and at the time MD5 had long been surpassed).

(as for my specific use case, I wanted to hash a password for `/etc/shadow` but I then realized my target system did support SHA-512 so I used that instead)

**Comment by hairyhenderson** [comment]
Thanks - your specific use case was what I was looking for 😉

Since you found a more secure alternative I suppose you don't need this anymore?

**Comment by giorgiga** [comment]
Thanks for your concern. I don't have specific plans that require a MD5 function. 

This seems like a relatively simple thing to add that would be suitable for a new contributor... may I suggest marking it as a "good first issue"? (well, if this is something you wouldn't mind was added to gomplate after all)

**Comment by hairyhenderson** [comment]
> This seems like a relatively simple thing to add

Agreed, however given that you don't have an actual use-case, and given that I don't really want to encourage people to be using MD5 _anyway_, I don't think it _should_ be added.

If someone chimes in with a valid use-case where generating MD5 hashes in templates is necessary, I can certainly consider it.
