### ISSUE TITLE
17.7M on Alpine Images

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#171]
`gomplate` seems to be quite big. Installing it via apk it takes 17.7M space. Is there a way to reduce it's size?

**Comment by hairyhenderson** [comment]
@estahn That's interesting - the result of the build that I make for Linux is 13.5MBs (https://github.com/hairyhenderson/gomplate/releases/download/v1.9.1/gomplate_linux-amd64). I'll have a closer look at the build for Alpine (https://github.com/alpinelinux/aports/blob/master/community/gomplate/APKBUILD)

One thing to note - I produce a smaller "slim" build for some platforms. The [Linux/amd64 binary](https://github.com/hairyhenderson/gomplate/releases/download/v1.9.1/gomplate_linux-amd64-slim) is 3.7MBs. I use [UPX](https://upx.github.io) to produce the slim ones, and unfortunately UPX isn't available in the Alpine repos yet, so it won't be able to be used during the Alpine build.

I'll try to see if I can get the build closer to the 13MB mark, but beyond that for now we're out of luck. The main reason it's so big is the `aws-sdk-go` package. I logged #47 a while back to track the possibility of making that smaller...

**Comment by estahn** [comment]
@hairyhenderson Actually, I'm using the `slim` version now in my alpine image.

```
curl -SsL -o /usr/local/bin/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v1.9.1/gomplate_linux-amd64-slim
```

Works fine.

It might be an idea to provide a version without `aws-sdk-go`, e.g. we're not using this feature atm. Anyways, the slim version works for me.

**Comment by hairyhenderson** [comment]
> It might be an idea to provide a version without `aws-sdk-go`

Yep - that crossed my mind, though it's easier said than done 😉
