### ISSUE TITLE
Feature request: function to embed the output of shell commands/scripts

### ISSUE THREAD

**Issue by giorgiga** [hairyhenderson/gomplate#1710]
A function that runs arbitrary shell commands could add a lot of flexibility to gomplate (at least for environments where performance is not a big concern).

For example, a `shell.Bash` function may allow something like:

````handlebars
{{ range "nmcli -t connection show" | shell.Bash | data.CSVByRow ":" "name:uuid:type:device" }}
    {{ .name }} {{ .uuid }} {{ .type }} {{ .device }}
{{ end }}
````

**Comment by giorgiga** [comment]
I swear I didn't know plugins were a thing!

This plugins thing seems much more elegant than the one I was imagining (and if I really wanted random shell commands I guess I could just define `bash` as a plugin and do it that way).

> potential security vulnerability

I see the point, but... `file.Write` also exists :smile:

**Comment by hairyhenderson** [comment]
@giorgiga no need to apologize! This wasn't a waste of time 🙂
