### ISSUE TITLE
Documentation: header and delimiter in data.CSVBy* functions

### ISSUE THREAD

**Issue by giorgiga** [hairyhenderson/gomplate#1711]
The `header` parameter of `data.CSVByRow` and `data.CSVByColumn` functions is documented as:

>  comma-separated list of column names

but really the separator must follow the `delim` parameter (which IMHO is not ideal, but I guess it's intentional)

(beware I've only verified this in `data.CSVByRow` and I only assume it also affects `data.CSVByColumn`)

**Comment by hairyhenderson** [comment]
@giorgiga can you clarify what you mean with an example?
