### ISSUE TITLE
Consider making slim-sprig functions first-class

### ISSUE THREAD

**Issue by kghenderson** [hairyhenderson/gomplate#1719]
There's a nice library called [Slim-sprig](https://github.com/go-task/slim-sprig) which aims to have a subset of high-performing functions from the fuller Sprig library. 

One of the nice hacks I've used from there are the list functions to pass multi-values to sub-templates. 
e.g. 
```
{{- template "MySubTemplate" list $thing1 $thing2 }}
```
and 
```
{{- define "MySubTemplate"}}
  {{- $thing1 := index . 0 }}
  {{- $thing2 := index . 1 }}
  [{{$thing1}}, {{$thing1}}] 
{{- end}}
```

Yes, I'm looking into converting these to collection/dictionaries, but these functions are still useful due to lists preserving order. 

Just wanted to capture it.

**Comment by kghenderson** [comment]
i'm seeing in the gomplate docs for [slice](https://docs.gomplate.ca/functions/coll/#coll-slice-deprecated):  `coll.Slice "Bart" "Lisa" "Maggie"` and i'm slightly confused in that there's a deprecated notice. I can't tell if `coll.Slice` is not deprecated but unqualified `slice` on its own is, or if `coll.Slice` is also deprecated.

**Comment by kghenderson** [comment]
I updated this ticket name because I thinking when using Go templates without gomplate, that it's pretty common to add sprig or slim-sprig into the funcMap and so these are somewhat standardized. Having these helps greatly with portability. I'm converting a number of Go (and CUE) text/templates into gomplate but there's a bunch of things that need to be re-written.  There's a few other functions which would be nice to have as well, but those can be separate topics.

**Comment by hairyhenderson** [comment]
> i'm slightly confused in that there's a deprecated notice. I can't tell if `coll.Slice` is not deprecated but unqualified `slice` on its own is, or if `coll.Slice` is also deprecated.

Yeah - sorry about that. Only `slice` is deprecated, but because `slice` is an alias to `coll.Slice` it's impossible to differentiate... The deprecation notice was intended to make that clear:

> Deprecation Notice: The `slice` alias is deprecated, use the full name `coll.Slice` instead.

Obviously not clear enough 😅... This is a downside of how my docs site is set up...

> I think that when using Go templates without gomplate, that it's pretty common to add sprig or slim-sprig into the funcMap and so these are somewhat standardized.

I'd challenge how "standardized" that is... I use templates outside of gomplate for a few different things and I've never even heard of slim-sprig (though I'm well aware of sprig).

Just so I'm clear, are you asking for parity between gomplate and sprig in terms of function names? or functionality? I don't think I'm interested in renaming (or adding additional aliases) for all the functions that have similar functionality - gomplate has namespaced functions, while sprig's functions are all in a single namespace.

If there's specific functionality that's missing though, please file new issues for those.

**Comment by kghenderson** [comment]
Cool:

re: slice documentation - not a big deal, I understood what it meant, was just calling it out for someday/later. 

re: sprig/slim-sprig, it's really 'sprig' that is the more familiar package, for sure, but it does have some slower functions with more baggage and I was just citing slim-sprig as an example of having a subset of them (although full sprig works too).

i think it will be pretty common (hopefully) for people to migrate to/from gomplate and go/cue templates so was just thinking about how to smooth this process. i'm all for the package namespacing, but I was in the process of converting my go templates to gomplate ones and this was a chore (and still not completed). so ... it's just something to consider that _some_ common sprig functions _could_ (someday) be aliases to the namespaced versions for easier conversion. 

also, just to be clear, obviously these are just ideas to see if you/others agree, there is zero expectation that they get implemented any time soon (if ever). 

currently i have .tmpl files which are @embed'ed into my go application, and in a perfect world i'd like those to be interchangeable with the gomplate versions, even if it also means wrapping the go templates in something to mimic the datasources definitions (although i'm currently just using gomplate context to avoid this).  

fwiw, i'm building some pipelines with gomplate and [nushell](https://www.nushell.sh/), and [cue](https://cuelang.org/), it's a very nice little cross-platform combo :-)
