### ISSUE TITLE
Possible to use as sidekick?

### ISSUE THREAD

**Issue by byrnedo** [hairyhenderson/gomplate#172]
Hi, 
Just wondering if it's possible to use this as a sidekick process to trigger a HUP signal for instance once a template has been generated?
Or is there another way to do it?

**Comment by hairyhenderson** [comment]
Hi @byrnedo! Thanks for taking the time to log this issue.

gomplate doesn't have any functionality for sending signals to other processes. However, I would think it could be driven by a script - something like:

```bash
#!/bin/sh

gomplate -f some-input.template -o some-output
kill -HUP $PID_OF_OTHER_PROCESS
```

Does that help?

**Comment by hairyhenderson** [comment]
Closing as I haven't heard anything back in 2 weeks - if you have follow-up questions, feel free to re-open or log something new!

**Comment by byrnedo** [comment]
Hi @hairyhenderson , 

Sorry, forgot to get back on this, the script example will do fine!
