### ISSUE TITLE
Consul support

### ISSUE THREAD

**Issue by stuart-c** [hairyhenderson/gomplate#173]
Would support for substitutions based on values stored in the key/value store within Consul be considered (optionally with authentication via Vault)?

**Comment by hairyhenderson** [comment]
@stuart-c Thanks for the issue! Yes, absolutely. I'd love to have Consul and other k/v stores as datasources, and have started writing this a few times over the last months 😉. A while back I had a look at https://github.com/docker/libkv as a potential way to make this simple, but it may be overkill.

As for authentication via Vault (I'm assuming you're talking about https://www.vaultproject.io/docs/secrets/consul/?) - it could be useful but I think I'd like to get unauthenticated Consul support in first.

**Comment by hairyhenderson** [comment]
Implemented by #178 🎉
