### ISSUE TITLE
update usage docs to explain "multiple outputs from one template" 

### ISSUE THREAD

**Issue by thesuperzapper** [hairyhenderson/gomplate#1746]
We should add to the [usage docs](https://docs.gomplate.ca/usage/#multiple-inputs) a brief overview of what is described in @hairyhenderson great blog: https://blog.hairyhenderson.ca/post/one_template_many_outputs/

Specifically, we should document the pattern of "multiple outputs from one template". 
It took me way too long to realize that [`--output-map`](https://docs.gomplate.ca/usage/#--output-map) is always one-to-one.

**Comment by hairyhenderson** [comment]
I wonder if a sort of "cookbook" section could be added with more complex usage examples...

If you feel like contributing something like that, I'd be happy to review!

**Comment by thesuperzapper** [comment]
Bumping for bot.

**Comment by hairyhenderson** [comment]
@thesuperzapper are you open to making a PR to contribute these docs?

**Comment by thesuperzapper** [comment]
@hairyhenderson I really dont have the cycles right now, sadly.
