### ISSUE TITLE
Coll.has not working with root context

### ISSUE THREAD

**Issue by mfidemraizer** [hairyhenderson/gomplate#1782]
Hi

I'm adding a context using `-c` CLI switch, and at some template I'm unable to get a simple `if has . "x"` working.

Also, I'm absolutely sure that `"x"` is a context's key, because if I do no `has` checking, the template is working as expected. 

Actually, in this case `has` is returning `false`.

Do you know what's going on?

For now I could solve the issue using `index`.

Thank you!

**Comment by hairyhenderson** [comment]
@mfidemraizer what version of gomplate is this happening with? Can you paste the exact command you're using, and the content of the datasource file?

This is working for me:

```console
$ gomplate --version
gomplate version 3.11.4
$ cat data.yaml 
x: hello world
$ gomplate -c .=data.yaml -i '{{ if has . "x" }}x is {{ .x }}{{ end }}'
x is hello world
```

**Comment by taraspos** [comment]
Hi @hairyhenderson I just faced the same problem, here is how you can reproduce it:

```shell
➜  gomplate --version
gomplate version 4.3.0
➜  echo 'x: hello world' > /tmp/data.yaml                                                                                                                            
➜  gomplate -c test=/tmp/data.yaml  -i '{{ if has . "test" }}test is {{ .test }} {{else}} oops  {{ end }}'                                                            
 oops  %
➜  gomplate -c test=/tmp/data.yaml  -i '{{ if has (keys .) "test" }}test is {{ .test }} {{else}} oops  {{ end }}'                                                     
test is map[x:hello world] %
```
