### ISSUE TITLE
Is there an equivalent to sprig's `set`?

### ISSUE THREAD

**Issue by thesuperzapper** [hairyhenderson/gomplate#1783]
I am needing to update the contents of an existing `dict`, but I see that `set` does not exist.

In sprig, the following can be used to [update `$myDict`](https://masterminds.github.io/sprig/dicts.html):

```
$_ := set $myDict "my-key" "my-value"
```

Is there an equivalent that I am missing in gomplate?

**Comment by hairyhenderson** [comment]
There is not currently an equivalent. I considered asking a `set`-like function years ago but I seem to recall some sort of technical blocker - I don't recall exactly what. Either way, this is the first time (to my recollection) that someone's requested it.

It's not too complex, and I'm not opposed to it. One factor with sprig's implementation is that it modifies the input; I think I would rather leave the input unmodified, and instead return a copy, so that further uses of the input map are left intact (you can always re-assign the input variable if you do want to overwrite it)

FWIW, the `coll.JQ` function, while somewhat inscrutable, can already do this:

```console
$ gomplate -i '{{ $m := dict "foo" "bar" }}{{ $m = jq `. += { baz: "qux" }` $m }}m is {{ $m }}'
m is map[baz:qux foo:bar]
```

LMK what you think!

**Comment by hairyhenderson** [comment]
Oh! I think I remember now why I didn't add a `set` function - this can be accomplished (with slightly more complexity) with [`coll.Merge`](https://docs.gomplate.ca/functions/coll/#collmerge).

So your example can be done like this:

```
{{ $myDict = merge $myDict (dict "my-key" "my-value") }}
```

A `set` function would likely get implemented like this:

```go
func (f *CollFuncs) Set(in map[string]interface{}, key string, val interface{}) (map[string]interface{}, error) {
	return f.Merge(in, map[string]interface{}{key: val})
}
```

**Comment by thesuperzapper** [comment]
@hairyhenderson my problem with the merge approach is actually the fact that it copies the map, which results in massive inefficiency when doing things like iteratively building up a map in a loop (you don't want to know [the horrors of what I am doing](https://github.com/deployKF/deployKF/blob/eaca1a56ec25937af2511af819630c0be2965888/generator/helpers/deploykf-profiles.tpl#L77-L184)  with gomplate).

Here is [sprig's implementation for `set` and `unset`](https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/dict.go#L15-L23).

**Comment by thesuperzapper** [comment]
While we are here, if we are allowing maps to be mutable, I would appreciate a `deepCopy` function!

Here is [sprigs implementation for `deepCopy`](https://github.com/Masterminds/sprig/blob/master/dict.go#L137-L144).

**Comment by thesuperzapper** [comment]
And one more thing! A true `get` function that does not result in a reflected value like `index` does would fix some problems.

Here is [sprigs implementation of `get`](https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/dict.go#L8-L13).

**Comment by hairyhenderson** [comment]
Ah - thanks @thesuperzapper. Updating does indeed make sense for your use-case (if I didn't want to know the horrors, why'd you link it? I couldn't resist looking! 🤣)

Is `unset` necessary?

I'll see about getting these all added before `v4`.

**Comment by thesuperzapper** [comment]
@hairyhenderson If we are implementing `set`, we may as well do `unset`.

In any case, I'm going to be releasing the first version of deployKF today after a very long time (I almost don't want to think) and I would like to thank you for that great foundation that gomplate provides (Even if I have had to fork it to change a few things).

If you ever need a machine learning platform on Kubernetes, you know what to use!

https://www.deploykf.org/

**Comment by thesuperzapper** [comment]
@hairyhenderson was there any movement on getting `set` into gomplate v4?

**Comment by hairyhenderson** [comment]
not yet - I've made some progress on v4 in general (there's a prerelease now!), but this is still outstanding
