### ISSUE TITLE
How to use coll.GoSlice

### ISSUE THREAD

**Issue by jeremych1000** [hairyhenderson/gomplate#1802]
Am I being stupid? I want to do the equivalent of Python's `a[0:1]`, where `a = ["a", "b", "c", "d"]`.

[Following the documentation](https://docs.gomplate.ca/functions/coll/#usage-2), it says
```
$ gomplate -i '{{ coll.GoSlice "hello world" 3 8 }}'
lo wo
```
where "hello world" can be a string, slice, array, etc.

but I get this:
```
$ gomplate -v
gomplate version 3.11.4

$ gomplate -i '{{ coll.GoSlice "hello world" 0 1 }}'
11:40:58 ERR  error="failed to render template <arg>: template: <arg>:1:3: executing \"<arg>\" at <coll>: can't evaluate field GoSlice in type interface {}"

$ gomplate -i '{{ coll.GoSlice (slice "a" "b" "c" "d") 0 1 }}'
11:41:13 ERR  error="failed to render template <arg>: template: <arg>:1:3: executing \"<arg>\" at <coll>: can't evaluate field GoSlice in type interface {}"
```

**Comment by hairyhenderson** [comment]
`coll.GoSlice` isn't in gomplate v3 😞 - you'll have to compile from `main` or wait for v4

**Comment by jeremych1000** [comment]
> `coll.GoSlice` isn't in gomplate v3 😞 - you'll have to compile from `main` or wait for v4

Ah right. What's the best way to do `a[0:1]`, where `a = ["a", "b", "c", "d"]` then? I just want to get the first 2 values from an array. JQ seems very overkill.

**Comment by jeremych1000** [comment]
I did this instead. Not great, but it works.

```
{{- range $i, $az := $all_azs }}
{{- if ge $i ($data.availability_zones | conv.ToInt) }}
  {{- break }}
{{- else }}
  {{- $azs = (coll.Append . $azs) }}
{{- end }}
{{- end }}
```

**Comment by hairyhenderson** [comment]
> JQ seems very overkill.

why's that?

**Comment by jeremych1000** [comment]
> > JQ seems very overkill.
> 
> why's that?

Wouldn't I need to do slice --> JSON --> JQ --> back to slice?

**Comment by hairyhenderson** [comment]
Nope - the [`coll.JQ` function](https://docs.gomplate.ca/functions/coll/#colljq) takes an object as input. If you need the output as an object you'll have to re-parse it though.

Something like:

```console
$ gomplate -i '{{ $a := coll.Slice 0 1 2 3 4 5 }}{{ coll.JQ ".[0:2]" $a | data.JSONArray }}'
[0 1]
```

**Comment by jeremych1000** [comment]
Thanks - let me make the required changes on my end.

I suppose there's no version selector on the documentation website right? How do I know which functions are in v3.x and v4.x? I'm guessing the current website shows v4.x.

**Comment by hairyhenderson** [comment]
> I suppose there's no version selector on the documentation website right?

that's https://github.com/hairyhenderson/gomplate/issues/1697

I'm not very frontend-savvy, so that particular issue is likely to stay open until I can get some help, or a lot of free time to focus on it 😅

**Comment by jeremych1000** [comment]
> I'm not very frontend-savvy, so that particular issue is likely to stay open until I can get some help, or a lot of free time to focus on it 😅

Noted - thanks again for this amazing tool. Closing.

**Comment by jeremych1000** [comment]
Sorry - reopening quickly. What's the equivalent in v3.x?

```
$ gomplate -i '{{ $a := coll.Slice 0 1 2 3 4 5 }}{{ coll.JQ ".[0:2]" $a | data.JSONArray }}'
11:32:08 ERR  error="failed to render template <arg>: template: <arg>:1:37: executing \"<arg>\" at <coll>: can't evaluate field JQ in type interface {}"
```

**Comment by hairyhenderson** [comment]
Oh right, `coll.JQ` isn't in v3 either. I think compiling your own binary off `main` is your best bet, or pulling the `:latest` Docker image
