### ISSUE TITLE
urlParse .Host also returns the port

### ISSUE THREAD

**Issue by dani** [hairyhenderson/gomplate#1823]
Hi and thanks for this tool which is very powerful. I've found an issue with the urlParse function I think :
```
{{ (urlParse "https://foo.example.org:8080" ).Host }}
```

Returns foo.example.org:8080 instead of just foo.example.org

.Port correctly returns 8080

**Comment by hairyhenderson** [comment]
Hi there @dani. That's expected. The `URL` type's `Host` field [is documented as](https://pkg.go.dev/net/url#URL):

> host or host:port

You can call the [`Hostname` method](https://pkg.go.dev/net/url#URL.Hostname) to get _just_ the host name:

```
$ gomplate -i '{{ (urlParse "https://foo.example.org:8080" ).Host }}
{{ (urlParse "https://foo.example.org:8080" ).Hostname }}
'
foo.example.org:8080
foo.example.org
```

**Comment by dani** [comment]
OK, thank you ! :-)
