### ISSUE TITLE
Documentation:  Mark features/functions that are coming in V4?

### ISSUE THREAD

**Issue by ArcticSnowman** [hairyhenderson/gomplate#1839]
To save confusion and issue being raised about function/feature not working as documented, could any feature/function that is in master but intended for V4 be marked as such in the documentation?

Maybe a simple (V4) tag or icon to let users know which gomplate version something is in?

**Comment by hairyhenderson** [comment]
Thanks for filing this @ArcticSnowman - I thought I had filed a similar issue, but I must've misremembered!

**Comment by ArcticSnowman** [comment]
Good luck with the move, I hope it goes smoothly.
