### ISSUE TITLE
Ignore not provided parametrs

### ISSUE THREAD

**Issue by matrus2** [hairyhenderson/gomplate#1919]
Would be nice to have an option/flag to accept to ignore error if one parameter is not provided. For now if in datasource there is no property the error is thrown:

datasource:

```yaml
cluster:
#  clusterName: "samename"
  clusterFQDN: "fqdn"
```

template:
```
# ------ Common variables
cluster_name = {{ (datasource "config").cluster.clusterName }}
cluster_fqdn = {{ (datasource "config").cluster.clusterFQDN }}
```
Throws error:

failed to render template templates/example.tmpl: template: templates/same.tmpl:2:30: executing \"templates/some.tmpl\" at <\"config\">: map has no entry for key \"clusterName\""

**Comment by hairyhenderson** [comment]
Hi @matrus2, you can use [`coll.Has`](https://docs.gomplate.ca/functions/coll/#collhas) to test for this.

See also the discussion in https://github.com/hairyhenderson/gomplate/issues/213, which this issue effectively duplicates, so for now I'll close this, unless you see a reason to re-open!

**Comment by matrus2** [comment]
Ok, I somehow miss `has` functionality, thank you for quick response.
