### ISSUE TITLE
[Feature]: integrate expr-lang

### ISSUE THREAD

**Issue by artemklevtsov** [hairyhenderson/gomplate#1941]
Hi,

Have you considered integrating [expr](https://github.com/expr-lang/expr)?

P.S.: Thank you for nice tool.

**Comment by hairyhenderson** [comment]
Hi @artemklevtsov, I have not. Can you elaborate your use-case? How would this be useful, and what sorts of things would this allow that aren't already possible with gomplate?

**Comment by artemklevtsov** [comment]
expr provides the compact and powerful syntax. So thought this would be a good addition or alternative.

**Comment by hairyhenderson** [comment]
> expr provides the compact and powerful syntax. So thought this would be a good addition [...]

@artemklevtsov sure, but it doesn't make sense to add features without a specific need or use-case.

> [...] or alternative.

alternative to what, exactly?

**Comment by artemklevtsov** [comment]
Thanks for the clarifying questions. I don’t have a specific case that would frustrate me.
My proposal was aimed at improving the user experience by simplifying the syntax with expr. Now I'm not sure if this is advisable.
