### ISSUE TITLE
Document 4 new conv functions in 2.0.0

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#196]
🤦‍♂️ I forgot to document `conv.ParseInt`, `conv.ParseFloat`, `conv.ParseUint`, and `conv.Atoi`.

**Comment by danedmunds** [comment]
I'd like to take this on for hackertoberfest!

**Comment by hairyhenderson** [comment]
Thanks @danedmunds - it's all yours!
