### ISSUE TITLE
how to use a json flow as input instead of a json file?

### ISSUE THREAD

**Issue by haiheipijuan** [hairyhenderson/gomplate#197]
I'm working with the CMD : gomplate -d zookeeper.json < zookeeper.tpl. How to use a json flow as input instead of a json file?

**Comment by hairyhenderson** [comment]
Hi @haiheipijuan - thanks for logging this!

By "json flow" I'm assuming you mean something like a file containing multiple separate JSON objects. If so, there's currently no way to do this - you'd have to pre-process this somehow.

Can you tell me more about your use case, and how you'd expect to be able to use an input like that?

**Comment by haiheipijuan** [comment]
Hi @hairyhenderson , thanks for your reply!
My case is simple，I handle a http request and get the JSON body, now i have to store it to a file named xxx.json, then use the command `gomplate -d xxx.json < xxx.tpl`. So I want to know if there is a way to skip this step .

**Comment by hairyhenderson** [comment]
Ah! I misunderstood 🙂

Yes, your use-case is possible, just use an HTTP URL as your datasource:

```console
$ gomplate -d foo=https://foo.example.com/path/to/resource -f xxx.tpl
...
```

See https://gomplate.hairyhenderson.ca/functions/data/#usage-with-http-data for details.

Let me know if this answers your question! 🙂

**Comment by hairyhenderson** [comment]
Just a follow-up note since it's not currently documented: if the HTTP server responds with a `Content-Type` header, gomplate will parse the reply accordingly. So, when the HTTP server is sending `application/json` as the `Content-Type`, it'll get parsed. If there is no `Content-Type` header, gomplate will fall back to the file extension in the URL.

**Comment by haiheipijuan** [comment]
OK, I got it. Thank you very much!

**Comment by hairyhenderson** [comment]
Closing since it seems the question has been answered.
