### ISSUE TITLE
Add some time-related functions

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#199]
I've run into situations where it'd be very useful to be able to retrieve the current time (in a given format), and the current system's local time zone.

For time zone, functions like `time.ZoneOffset` and `time.ZoneName` could be appropriate.

**Comment by hairyhenderson** [comment]
Would also need to be able to format a given local time (i.e. `07:00 EDT`) in UTC.

**Comment by danedmunds** [comment]
I'd like to take this on as part of Hacktoberfest... assuming you haven't started work on it!

**Comment by danedmunds** [comment]
Dang! 😉

**Comment by hairyhenderson** [comment]
@danedmunds sorry - forgot to PR the branch for this... 🙂
