### ISSUE TITLE
Specifying templates in the `.gomplate.yaml` causes no output to be rendered

### ISSUE THREAD

**Issue by stouset** [hairyhenderson/gomplate#2002]
```sh
❯ gomplate --version
gomplate version 3.11.7

❯ cat .gomplate.yaml
templates:
  foo.t:
    url: file://foo.t

❯ cat foo.t
abc

❯ cat bar.t 
{{ template "foo.t" }}

❯ gomplate --verbose < bar.t 

❯ rm .gomplate.yaml
❯ gomplate --verbose --template foo.t < bar.t
21:25:57 DBG starting gomplate
21:25:57 DBG config is:
---
templates:
  foo.t:
    url: file:///var/folders/_m/hjhtwf1s75d3cwc3c0rc08jc0000gn/T/tmp.dj1fS1HM1E/foo.t
 build= version=3.11.7
abc
```

**Comment by stouset** [comment]
This causes an early-exit before any logging is even output. It seems to be a parser failure of the `.gomplate.yaml`, but I have even attempted to use the literal output from the printed `DBG config` and the same issue occurs.

**Comment by NiceGuyIT** [comment]
I ran into the [same problem](https://github.com/hairyhenderson/gomplate/discussions/1996) and the pre-release version `4.0.0-pre-2` worked for me.

**Comment by hairyhenderson** [comment]
thanks for the followup @NiceGuyIT! @stouset is using `4.0.0-pre-2` an option for you?

**Comment by hairyhenderson** [comment]
One issue with your original config is `file://foo.t` is not a valid file URL - file URLs must have `file:///` as a prefix (_three_ `/` characters). That may or may not be the cause, but it's a potential factor...
