### ISSUE TITLE
plugin args example does not work

### ISSUE THREAD

**Issue by yngvark** [hairyhenderson/gomplate#2023]
# Description
https://docs.gomplate.ca/config/#args

Args are not passed to the shell.

# Steps to recreate

```shell

cat <<EOF > test.template
{{ echo "baz" }}
EOF

cat <<EOF > .gomplate.yaml
plugins:
  echo:
    cmd: /bin/echo
    args:
      - foo
      - bar
EOF

cat test.template | gomplate
```

The output is:

```
baz
```

# Expected behavior

The output should be

```
foo bar baz
```

# Gomplate version

```shell
gomplate version 3.11.7
```

**Comment by hairyhenderson** [comment]
Hi @yngvark, can you try this with the [v4.0.0-pre-2](https://github.com/hairyhenderson/gomplate/releases/tag/v4.0.0-pre-2) version, just to confirm if it's been fixed already?

**Comment by yngvark** [comment]
Yes it works, thanks!

**Comment by hairyhenderson** [comment]
@yngvark FYI I realized why this wasn't working for you - the `args` configuration is only supported in v4 and above (see [release notes](https://github.com/hairyhenderson/gomplate/releases/tag/v4.0.0-pre-2)). Unfortunately the config file documentation doesn't call that out specifically.

**Comment by yngvark** [comment]
Alright, good to know 👍
