### ISSUE TITLE
Using Gomplate as a library

### ISSUE THREAD

**Issue by obvionaoe** [hairyhenderson/gomplate#2029]
Hi would it be possible to use Gomplate as a library?
You've made quite a few handy wrappers over parsers that would be very handy in my project, but all those functions are private in your module :)

Thanks

**Comment by hairyhenderson** [comment]
> handy wrappers over parsers

Which are you looking to use, in particular?

In general, it should be a case of calling [`gomplate.Renderer#Render`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v4#Renderer.Render).
