### ISSUE TITLE
Support for text/binary files

### ISSUE THREAD

**Issue by adaphi** [hairyhenderson/gomplate#209]
Hey,

gomplate nicely supports structured files as datasources (yaml, toml, etc) but it would be nice if it were able to support basic text files, so you could just dump the entire contents of a file with gomplate. e.g.

```
$ echo "some_long_string" > mytextfile
$ echo '{{ (datasource "text") }}' | gomplate --datasource text=file://mytextfile
```

Would that be possible to add?

**Comment by hairyhenderson** [comment]
Thanks for logging this issue, @adaphi!

You should be able to use the [`include`](https://gomplate.hairyhenderson.ca/functions/data/#include) function for this:

```
$ echo "some_long_string" > mytextfile
$ gomplate -d text=mytextfile -i '{{ include "text" }}'
some_long_string
```

Hope this helps!

**Comment by adaphi** [comment]
Ahh I missed that one, tyvm! Seems to work fine.

**Comment by hairyhenderson** [comment]
Glad to hear it!
