### ISSUE TITLE
Default values for variables

### ISSUE THREAD

**Issue by vascop** [hairyhenderson/gomplate#213]
Is there a way to use a default value when a variable isn't defined?

Something like:
`{{(ds "config").notes | default "this a default note")}}`

**Comment by hairyhenderson** [comment]
@vascop Not in a general sense right now. For your specific example, that might result in an error if the `config` datasource doesn't have a `notes` key. I'd have to dig a little further into it to make sure.

Either way - this is a good idea! Thanks for logging this issue 🙂

**Comment by zealic** [comment]
I think we need a new func: `hasKey`

like hugo's [isset](https://gohugo.io/functions/isset/)

```
{{ $config := (ds "config") -}}
{{ $notes := "this a default note" -}}
{{ if hasKey $confg "notes" -}}
{{ $notes := $config.notes -}}
{{ end -}}
```

**Comment by hairyhenderson** [comment]
@zealic there is `has`/`conv.Has` already: https://gomplate.hairyhenderson.ca/functions/conv/#conv-has

**Comment by hairyhenderson** [comment]
And actually, that's an excellent point... @vascop will `has` fix your use case? What @zealic suggested should work (except use `has` instead of `hasKey`).

**Comment by vascop** [comment]
I think it'd probably work, though much more verbose since we'd have to do the whole "check if it has key and overwrite" dance instead of one-lining the default values.

**Comment by hairyhenderson** [comment]
@vascop understood. It's not ideal. But it might be the only option...

The challenge is that referencing an undefined key will cause Go's `text/template` to blow up:

```
$gomplate -i '{{ (json `{"foo":"bar"}`).baz }}'
panic: template: template:1:9: executing "template" at <`{"foo":"bar"}`>: map has no entry for key "baz"

goroutine 1 [running]:
main.(*Gomplate).RunTemplate(0xc42030e030, 0x7fff5fbff54c, 0x20, 0x1e95de0, 0xc42000c018)
	/go/src/github.com/hairyhenderson/gomplate/gomplate.go:31 +0x42c
```

My impression is that we won't be able to get that _specific_ syntax to work without re-implementing Go's templating system.

What we _can_ do is have a `default` function that will provide a value if the given input is `nil` or an empty string. That's not too difficult, but it wouldn't address your specific use-case.

**Comment by estahn** [comment]
👍 for `default`, e.g. `{{ .foo | default "bar" }}`.

**Comment by hairyhenderson** [comment]
@estahn if `.` has no `foo` key, that particular usage will never work. In that case you'll have to always wrap it in `{{ if has . "foo" }}...{{ end }}`.

But I still think `default` would be useful for handling empty values. I'll see about implementing this soon.

**Comment by thepalbi** [comment]
Just for future reference, I'm using this to make something like that default case:
```
{{ has (ds "config") KEY | ternary (ds "config").KEY "default value" }}
```

**Comment by paulhutchings** [comment]
Wanted to share another option that I found works and is pretty close to the sprig version as well. I'm configuring my datasources as contexts in the config file in this case.
```
{{ index . "foo" | default $.values.defaults.foo }}
```

**Comment by sepich** [comment]
Problem with `default` is that it considers bool `false` as empty.
So if your specifically set your `"foo": false` the example above would use `.values.defaults.foo` value instead
I believe [coalesce](https://masterminds.github.io/sprig/defaults.html) would suit here better
