### ISSUE TITLE
Provide TrimLeft and TrimRight Support

### ISSUE THREAD

**Issue by jsolana** [hairyhenderson/gomplate#2134]
# Situation

We are using gomplate to process *.proto file to generate `YAML`files. These proto files may belong to third party providers.
At the end, to check everything is correct, we are using `yamllint` to check it.

Sometimes, *.proto files contains trailing spaces and to avoid fails during the validation using `yamllint`, we are using `TrimSpace` but the problem is, we are loosing left indentation. Eg:

```proto
message MessageA{
string field1 = 1;
string field2 = 2;
...
}
```
Other operations as `Trim` affect also left and right and we can't use `TrimSuffix` to fix it.

# Solution

Provide:

-  strings.TrimLeft
- strings.TrimRight

Wdyt?

**Comment by jsolana** [comment]
If make sense I can do it by myself :)

**Comment by hairyhenderson** [comment]
Thanks @jsolana and thanks for the PR! I'm fine with adding these, but I'm curious about the use-case. Can you provide an example of the template you're using to process the .proto files?

**Comment by jsolana** [comment]
I want to create `Backstage` API  entities from *.proto files eg:

```proto
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: helloworld-grpc-api
  namespace: dev-x
spec:
  type: grpc
  lifecycle: testing
  owner: group:default/dev-x
  definition: |

    syntax = "proto3";

    option go_package = "gitlab.otters.xyz/platform/dev-x/deployment/helloworld_grpc.git/proto/v1/helloworld";

    package helloworld;

    // The HelloWorld service definition.
    service HelloWorld {
      // Sends a greeting
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

    // The request message containing the user's name.
    message HelloRequest {
      string name = 1;
    }

    // The response message containing the greetings
    message HelloReply {
      string message = 1;
    }

---

```

Im generating them using gomplate, the problem is, if the origin where the proto files belong (may be third party services) contains trailing spaces etc,.. running yamlling will fails


Right now Im doing:

```yaml
{{- $content := file.Read $file -}}
{{- $lines := strings.Split "\n" $content -}}
{{- range $line := $lines -}}
    {{- $trimmed := $line | strings.TrimSpace -}}
    {{- if ne $trimmed "" -}}
        {{"\n"}}{{ $trimmed | indent 4 }}
    {{- else -}}
{{"\n"}}
    {{- end -}}
{{- end -}}

```

The problem with it is, we are losing the indentation defined in the origin then, the `Backstage` API generated is like this one:

```proto
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: helloworld-grpc-api
  namespace: dev-x
spec:
  type: grpc
  lifecycle: testing
  owner: group:default/dev-x
  definition: |

    syntax = "proto3";

    option go_package = "gitlab.otters.xyz/platform/dev-x/deployment/helloworld_grpc.git/proto/v1/helloworld";

    package helloworld;

    // The HelloWorld service definition.
    service HelloWorld {
      // Sends a greeting
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

    // The request message containing the user's name.
    message HelloRequest {
    string name = 1;
    }

    // The response message containing the greetings
    message HelloReply {
    string message = 1;
    }

---

```
(message's field with no indentation)

**Comment by hairyhenderson** [comment]
A couple thoughts:

- you shouldn't need `file.Read` - `include` should work (though it should work either way)
- the `{{-` and `-}}`s that you're using are what are ultimately responsible for losing the indentation

Obviously what you've posted is a subset of what you're actually doing, but I wonder why you need to iterate through each line, and why not simply pass the whole proto file through `indent 4`?

**Comment by jsolana** [comment]
That was the first approach but it didn't work keeping trailing spaces at the end of some lines

```yaml
{{- $content := file.Read $file -}}
      {{- if $content | strings.Contains  (print "message " $messageName " {")}}
{{ $content | indent 4 }}
```

**Comment by jsolana** [comment]
@hairyhenderson  let me know if you need more information to clarify the why
Thanks a lot!

**Comment by hairyhenderson** [comment]
This line:

```
{{- $content := file.Read $file -}}
```

might be responsible for what you're seeing - the trailing `-}}` causes all following whitespace to be elided, including newlines and whitespace _following_ that.

Either way, TrimLeft/Right are fine additions. I'll re-review the PR after I release v4.0.1!

**Comment by jsolana** [comment]
Thanks mate!
