### ISSUE TITLE
Exclude option support

### ISSUE THREAD

**Issue by zealic** [hairyhenderson/gomplate#218]
Need "--exclude" option to ignore some files:

Example:
```
gomplate --input-dir=./data \
  --exclude=".*"     \ # Exclude file or directory with dot prefix
  --exclude="*.xml"  \ # Recursive exclude xml file
  --exclude="logs"   \ # Exclude logs file or directory
  --output-dir=./output
```

Refernece:
* https://golang.org/pkg/path/filepath/#Glob

**Comment by hairyhenderson** [comment]
@zealic thanks for logging this! Sounds like a reasonable feature when processing a directory with many files.

**Comment by zealic** [comment]
I will implement this feature.
Maybe '.gomplateignore' is better idea.

**Comment by hairyhenderson** [comment]
@zealic yeah - `.gomplateignore` would be great - I'm assuming you're meaning something similar to the `.gitignore` file?

**Comment by zealic** [comment]
@hairyhenderson Yes, it is.

Default use '--input-dir' root .gomplateignore file, sub folder can be inherit.
Finally, '--exclude' option add additional ignore files.

**Comment by hairyhenderson** [comment]
@zealic That sounds good. I'd like the `.gomplateignore` and `--exclude` features to be submitted as separate PRs, for clarity

**Comment by keydrevolta** [comment]
@zealic this may help you https://github.com/tsuru/tsuru-client/pull/25

**Comment by Gman98ish** [comment]
Hi, I've not done the whole thing, just found a potential solution for the command line flag, potentially provides a starting point for the `.gomplateignore`

**Comment by hairyhenderson** [comment]
`--exclude` is now available, so I'm going to close this issue. Feel free to enhance with further PRs though! 🙂
