### ISSUE TITLE
OS information...

### ISSUE THREAD

**Issue by sean-** [hairyhenderson/gomplate#2185]
Has there been any consideration or thought to incorporating something like https://github.com/shirou/gopsutil as a data source to emit hardware/OS information?

**Comment by hairyhenderson** [comment]
I could've sworn I saw this before... https://github.com/hairyhenderson/gomplate/issues/663 😂

If you're still interested in this, feel free to re-open the original issue. My comments there still stand.

Closing this since it's a duplicate
