### ISSUE TITLE
Unexpected behavior of evaluating "index" in "test.Ternary"

### ISSUE THREAD

**Issue by rmrnc** [hairyhenderson/gomplate#2222]
Hi
Maybe it's just me, but somehow the semantic of `gomplate`'s `test.Ternary` processing the result of `index` eludes me.  

```sh
$ gomplate --version

gomplate version 4.1.0
```

```sh
$ echo '{ "key": "value"  }' | gomplate --context .=stdin:///in.json \
    --in '{{ index . "key" | ternary (index . "key") (printf "unexpected %s" (index . "key")) }}'

unexpected value

$ echo '{ "key": "value"  }' | gomplate --context .=stdin:///in.json \
    --in '{{ index . "not_a_key" | ternary (index . "not_a_key") "expected" }}'

expected                                               
```

Especially, when compared to

```sh
echo '{ "key": "value"  }' | gomplate --context .=stdin:///in.json \
    --in '{{ $x := "initial" }}{{ if (index . "key") }}{{ $x = (index . "key") }}{{ else }}{{ $x = "default" }}{{ end }} x={{ $x }}'

x=value

echo '{ "key": "value"  }' | gomplate --context .=stdin:///in.json \
    --in '{{ $x := "initial" }}{{ if (index . "not_a_key") }}{{ $x = (index . "key") }}{{ else }}{{ $x = "default" }}{{ end }} x={{ $x }}'

x=default
```

Would you mind pointing out where I went wrong?

Thank you very much

**Comment by hairyhenderson** [comment]
It may just be an over-simple example, but why are you using `index` when you could just refer to the item by `.key`?

One other issue here is that the [test.Ternary](https://docs.gomplate.ca/functions/test/#testternary) expects a boolean (or boolean-like string), so feeding it `"value"` is indeed going to cause confusion.

The reason the second example works is that the `if` keyword is much broader in scope - given a non-boolean value it'll consider any non-empty value to be `true`. I suppose the documentation is somewhat misleading:

> This is effectively a short-form of the following template:

the word "effectively" does a lot of heavy lifting there, as what I _really_ meant was "this is similar in concept, but with subtle and very important differences" 🤦‍♂️

Perhaps simply removing that block would reduce confusion...

**Comment by rmrnc** [comment]
Sorry, for my late reply.

>  why are you using index when you could just refer to the item by .key?

Unfortunately, the clumsy use of `index` is due to the fact, that if a key does not exist, referring to it results in an `map has no entry for key` error.

> I suppose the documentation is somewhat misleading

I am afraid, I have to agree.

Still worse, trying to apply `test.Ternary` for some sort of "nil-coalescing", forces an arguably cumbersome 

`{{ (ne (index . "key") "") | ternary .key "some default" }}`

expression. What is your take on providing a dedicated operator/function for this common situation in `gomplate`?

**Comment by rmrnc** [comment]
Just realized, that 

`'{{ (has  . "key") | ternary .key "some default" }}`

provides a more palatable option. I guess, that's as good as it gets.
