### ISSUE TITLE
function "math" not defined

### ISSUE THREAD

**Issue by r0bj** [hairyhenderson/gomplate#224]
gomplate version: 2.1.0

Using math example from docs:
```
$ gomplate -i '{{ math.Add 1 2 3 4 }}'
2017/11/01 16:58:06 Line "{{ math.Add 1 2 3 4 }}": template: template:1: function "math" not defined
$ gomplate -i '{{ add 1 2 3 4 }}'
2017/11/01 16:58:09 Line "{{ add 1 2 3 4 }}": template: template:1: function "add" not defined
```

**Comment by hairyhenderson** [comment]
@r0bj sorry about this! the `math` namespace was _just_ added in #214, and hasn't hit a released version yet. The docs track `master` (for simplicity). I'm hoping to release a new version (probably 2.2.0) soon (maybe by tomorrow), at which point this will work.

**Comment by r0bj** [comment]
@hairyhenderson Thanks for info.

**Comment by marcbachmann** [comment]
Oh, I also just ran into this.
It's a bit weird that the new documentation is already online but there's no release.
Thanks for releasing. 😁

**Comment by hairyhenderson** [comment]
> It's a bit weird

I know, I know... 😂

**Comment by hairyhenderson** [comment]
A release is coming _soon_ - just want to get _one more thing_ in 😉

**Comment by hairyhenderson** [comment]
Ok, v2.2.0 is out now: https://github.com/hairyhenderson/gomplate/releases/tag/v2.2.0 - it knows `math` 😉

**Comment by marcbachmann** [comment]
😍 thanks
