### ISSUE TITLE
"merge" datasource breaks with "stdin:" input (gomplate 4.x)

### ISSUE THREAD

**Issue by aivajoe** [hairyhenderson/gomplate#2273]
I just upgraded from 3.x to 4.x, and all of my gomplate scripts which use `merge:` have broken. I ran some tests and it does seem as though there is a difference when one of the datasources being merged is a `stdin:` datasource. This issue does not seem to be present when both datasources are files.

Invocation:
```
echo -n '{"key1": "val1"}' | gomplate -i '{{ ds "cfg" }}' -d cfg1=stdin:///foo.json -d cfg2=test_input2.json -d 'cfg=merge:cfg1|cfg2'
```

gomplate 3.11.8 output:
```
map[key1:val1 key2:val2]
```

gomplate 4.2.0 output:
```
map[key2:val2]
```

gomplate 4.x seems to fail to merge in the data coming from the stdin: datasource.

**Comment by hairyhenderson** [comment]
I've had a look at this, and it seems to not be a bug with `merge` _per se_, but rather a bug with the stdin filesystem support.

The root issue is that the stdin content is being read once and discarded, and the next time it needs to be read, the buffer's empty.

I'll work on fixing this now.
