### ISSUE TITLE
Vault list support

### ISSUE THREAD

**Issue by tallpauley** [hairyhenderson/gomplate#229]
I'm unable to list vault approle secret ID accessors, since you have to LIST (not supported) or do a GET w/ a get string (also not supported). Any good way to support this? Maybe it could be something like the following?
```
{{ ds "vault" "path/to/secret" "list" }}
```

If you have a way you would want this implemented @hairyhenderson, I can submit a PR

**Comment by tallpauley** [comment]
By the way, gomplate has been THE missing templating tool for us, and I'm probably using it to do way too much :)

**Comment by hairyhenderson** [comment]
Hi @tallpauley! Thanks for the kind words, and thanks for the feature request!

This is an _interesting_ idea... It may be possible right now in _theory_ - you could try setting the path to `path/to/secret?list=true`. I'm not sure if that'll work, but it's definitely worth a try.

So, something like:

```
{{ ds "vault" "path/to/secret?list=true" }}
```

I'm not sure if that's ideal, but at least it'd be a start.

I'll think about the UX some more and get back to you 🙂

**Comment by tallpauley** [comment]
This is no longer a requirement for us. In my case I was trying to do a little too much with a templating engine :)

**Comment by hairyhenderson** [comment]
@tallpauley totally understand - I have to be careful to not overuse gomplate as well 😉

That being said, there may still be a place for a feature like this, maybe in conjunction with the "directory datasource" (#215) idea... I'm still formulating a UX I like, but I'm starting to think it may just be as simple as doing a "list" operation when the path ends in a `/`.
