### ISSUE TITLE
datasource vault with a value that has a hyphen/dash

### ISSUE THREAD

**Issue by docwhat** [hairyhenderson/gomplate#242]
How do you access a key in vault that has a hyphen or dash in it?

e.g. `{{ (datasource "vault").key-with-hyphens }}`

If this is possible, can we add it to `datasources_vault.bats` for reference (and the documentation)?

**Comment by hairyhenderson** [comment]
Good question, @docwhat! This really is more a general Go templating question, and not so much specific to Vault datasources, or datasources, or even gomplate.

One option is to use the `index` built-in:

```console
$ gomplate -i '{{ index (json `{"foo-bar":"baz"}`) "foo-bar" }}'       
baz
```

But that can get a bit awkward. I'm trying to figure out if there's cleaner syntax 🙂

**Comment by docwhat** [comment]
It is true this is generic, but it still would be good to add it to the gomplate docs someplace. :-)

**Comment by hairyhenderson** [comment]
@docwhat Sure! I'll think about where it'd fit best.

For the record, I haven't found any cleaner syntax than `index`.
