### ISSUE TITLE
Enable reading from AWS SSM Parameter Store?

### ISSUE THREAD

**Issue by tyrken** [hairyhenderson/gomplate#245]
I'm looking into using gomplate to fill in values from the AWS Parameter Store, any other interest or guidance as I'm currently hacking it to do so.

Would mean a bump up of the AWS package version to 1.10.x at least, and the re-run of `dep ensure` is adding a load of files to the repo unless I enable `prune` options...

**Comment by hairyhenderson** [comment]
@tyrken this sounds like a great feature! Sounds like you're already working on a PR?

As for the pruning - yeah, I was actually working earlier today on updating the `Gopkg.toml` to support the new `prune` option. I don't remember why I locked the AWS SDK - probably just annoyed that it kept getting updated 😉 - I'll bump that version as well.

**Comment by hairyhenderson** [comment]
@tyrken ok, deps updated in #246 and #247 - should help!

Were you planning on implementing this as a datasource? I think that may be what makes the most sense.

**Comment by tyrken** [comment]
I have started - but by creating an aws.SSMParam function as a sibling to aws.EC2Tag, roughly working but needs more tests.

On the DataSource front, SSM in design sounds like it might fit in libkv but they don't have AWS SSM Parameter support upstream... don't know how long it would take to get accepted there.  Do you want me to add a AWS SSM client to data.Source struct?

**Comment by tyrken** [comment]
On second thoughts, no SSM wouldn't fit in libkv - it cannot satisfy their backend requirements (Watching/Atomic ops).  So looking at ending via a new 'aws+ssm+param' sourceReader

**Comment by tyrken** [comment]
Initial work in PR - #248

**Comment by hairyhenderson** [comment]
Fixed in #248
