### ISSUE TITLE
Is crypto namespace functions in 2.2.0

### ISSUE THREAD

**Issue by pvdvreede** [hairyhenderson/gomplate#254]
Hey,

Just wanted to confirm if the crypto functions specifically sha256 or sha1 are in 2.2.0?

I am getting errors if I try and use them that say the crypto function does not exist...

**Comment by hairyhenderson** [comment]
@pvdvreede those aren't yet in a release, sorry! 😞 I meant to release a new version _much_ earlier! But thank you for the reminder - I will do that _right now_ 😉

**Comment by hairyhenderson** [comment]
It's in v2.3.0 now - https://github.com/hairyhenderson/gomplate/releases/tag/v2.3.0 😅

**Comment by pvdvreede** [comment]
Many thanks!

**Comment by hairyhenderson** [comment]
🙇
