### ISSUE TITLE
Method for renaming output files/folders created with --input-dir/--output-dir usage?

### ISSUE THREAD

**Issue by robesris** [hairyhenderson/gomplate#288]
The recursive `--input-dir`/ `--output-dir` gives me _almost_ exactly what I need, but I would like to be able to rename the output files based on some values (from datasource or otherwise).  Is there a way currently to accomplish this without wrapping several `gomplate` invocations in a shell script (i.e. one for each file)?  If not, this would be a great feature to add.

**Comment by hairyhenderson** [comment]
Hi @robesris, thanks for logging this! There's not a way to currently do this, but I totally agree - it'd be a good feature.

How about parsing `--output-dir`'s value as a template string, with the input context being set to the input path?

Something vaguely like:

```console
$ gomplate --input-dir /tmp --output-dir '/dest/{{ .  | strings.ReplaceAll ".in" ".out" }}'
...
```

What do you think?

**Comment by Croissong** [comment]
I would also love to be able to change filenames when using `--input-dir` and `--output-dir`, e.g. stripping `.gotmpl` suffix off the filenames.

**Comment by hairyhenderson** [comment]
@Croissong Thanks! Can you tell me if my suggestion above will meet your needs?

**Comment by Croissong** [comment]
> @Croissong Thanks! Can you tell me if my suggestion above will meet your needs?

Absolutely!

**Comment by hairyhenderson** [comment]
Ok, great 😉 - I'll see what I can do!

**Comment by hairyhenderson** [comment]
@robesris @Croissong FYI I'm adding `--output-map` in #529 - it's a new flag (instead of overriding `--output-dir` as I suggested above), and instead of referencing `.` for the input dir, it's `.in`. See https://deploy-preview-529--gomplate-docs.netlify.com/usage/#output-map for details.
