### ISSUE TITLE
unexpected "|" in template clause

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#290]
Template:
```
{{- template "base" -}}
{{ define "jobs" }}
  {{ template "job-checkout_code" | indent 4 }}
{{ end }}
```

Error message:
```Error: template: -:39: unexpected "|" in template clause```

**Comment by hairyhenderson** [comment]
Thanks for logging this, @estahn!

That doesn't seem to be _quite_ the right syntax, though there's still a bug. Using the built-in `js` function, this fails in the same way:

```console
$ gomplate -i '{{define "foo"}}hello world{{end}}{{ template "foo" | js }}'   
Error: template: <arg>:1: unexpected "|" in template clause
```

But this succeeds:

```console
$ gomplate -i '{{define "foo"}}hello world{{end}}{{ template "foo" . | js }}'
hello world
```

This _should_ succeed, but doesn't:

```console
$ gomplate -i '{{define "foo"}}hello world{{end}}{{ template "foo" . | strings.ToUpper }}'
Error: template: <arg>:1:56: executing "<arg>" at <strings>: wrong type for value; expected string; got *main.Context
```

So, clearly there's something missing 😉

**Comment by hairyhenderson** [comment]
Ok, this is a pretty widely-scoped bug. Essentially, I have a number of functions that accept only `string`s, which should really be able to handle anything, converting to `string` as necessary.

Interestingly, at first glance `strings.Indent` _isn't_ only accepting `string`, and indeed it gives a different error:

```console
$ gomplate -i '{{define "foo"}}hello world{{end}}{{ template "foo" . | strings.Indent }}' 
2018/04/18 20:39:19 Indent: invalid arguments
```

This is because it takes `...interface{}` as its arguments. It immediately fails if the last element in that array is a non-`string`, though.

All this to say - the fix for `strings.Indent`/`indent` will be slightly different than the fix for every other function that expects a `string`.

I'm on it - just need to step out for a quick jog and I'll try and get a fix drafted tonight or tomorrow 👍

**Comment by hairyhenderson** [comment]
Ok, further discovery - my reading of the template docs was way off... When rendering templates of the form `{{ template "T1" pipeline }}`, I thought the `T1` template would be piped through `pipeline`, but that's not at all true - instead the value set by `pipeline` is passed to `T1` as the context (`.`):

```console
$ gomplate -i '{{ define "T1" }}hello {{ . }}{{end}}{{template "T1" "world" | strings.ToUpper }}'
hello WORLD
$ gomplate -i '{{ define "T1" }}hello {{ .hello }}{{end}}{{template "T1" data.JSON `{"hello":"world"}` }}'
hello world
```

So, based on all this, this _isn't_ a bug in gomplate, but a simple syntax issue.

I'd be nice to be able to handle many different kinds of input to the functions in the `strings` namespace, but that's orthogonal to this issue.

I'm going to close this now - feel free to re-open if you disagree 🙂

**Comment by estahn** [comment]
I feel that helps sort of with #291 , but don't see how it will help with the indentation of the output of ``{{ template ...}}``.

**Comment by hairyhenderson** [comment]
> don't see how it will help with the indentation of the output of `{{ template ...}}`.

I'm not sure this is possible with `template` unfortunately. You'd have to alter it where it's `define`d, which may or may not be awkward:

```console
$ gomplate -i '{{ define "T1" }}{{ strings.Indent .width "." "hello world" }}{{ end -}}
{{ template "T1" data.YAML "width: 3" }}
{{ template "T1" data.YAML "width: 4" }}'
...hello world
....hello world
```

Hope that helps!

**Comment by estahn** [comment]
@hairyhenderson Thanks for the support and quick turnaround. 👍

**Comment by hairyhenderson** [comment]
🙇

**Comment by RevantBabu** [comment]
The other approach I think (especially while including template files) is to use tmpl.Exec (that returns a string which can be piped to strings.Indent)

`{{ tmpl.Exec "t/input.tmpl" . | strings.Indent 4 }} `
