### ISSUE TITLE
function "dict" not defined

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#291]
My code:
```
{{- template "base" -}}
{{ define "jobs" }}
  {{ template "job-checkout_code" dict "Version" $version }}
{{ end }}
```
Error:
```
function "dict" not defined
```

**Comment by hairyhenderson** [comment]
gomplate doesn't yet have a `dict` function - see https://github.com/hairyhenderson/gomplate/issues/210#issuecomment-336660398 for some discussion of that possibility (which was never implemented).

**Comment by estahn** [comment]
@hairyhenderson Bummer, I was looking at doing something like macros in Jinja (http://jinja.pocoo.org/docs/2.10/templates/#macros).

If you have a good idea for this let me know.

**Comment by estahn** [comment]
@hairyhenderson How would that look like with non-existing `ver`?

Example:
```
gomplate -i '{{define "T1"}}Version {{if . has "ver"}}{{ .ver }}{{end}}{{end}}{{template "T1"}}'
Version Error: template: <arg>:1:28: executing "T1" at <.>: can't give argument to non-function .
```

**Comment by estahn** [comment]
Never mind, got it working:

```
gomplate -i '{{define "T1"}}Version {{if has . "ver"}}{{ .ver }}{{end}}{{end}}{{template "T1"}}'
```
```
gomplate -i '{{define "T1"}}Version {{if has . "ver"}}{{ .ver }}{{end}}{{end}}{{template "T1" data.JSON `{"ver":"1.2.3"}`}}'
```
