### ISSUE TITLE
File mode is not preserved

### ISSUE THREAD

**Issue by djgilcrease** [hairyhenderson/gomplate#296]
when using something like ```gomplate --input-dir=templates --output-dir=deploy``` that contains files with the execute bit set that is not preserved.

I am thinking to update ```gatherTemplates``` to add get the current FileMode and pass it to ```addTarget``` and then into ```openOutFile```

If this approach is ok I will create the pull request

**Comment by hairyhenderson** [comment]
Hi @djgilcrease - thanks for logging this!

That sounds like a reasonable plan overall. You'll need to alter `walkDir` as well to track and output the mode.

A PR would be greatly appreciated! Thank you!

**Comment by djgilcrease** [comment]
https://github.com/hairyhenderson/gomplate/pull/297
