### ISSUE TITLE
[question] what is the diff between regular binary and slim one?

### ISSUE THREAD

**Issue by yermulnik** [hairyhenderson/gomplate#326]
What is the diff between regular binary and slim one?

**Comment by hairyhenderson** [comment]
@yermulnik functionally, there's no difference! Size-wise, the `slim` binary is ~5x smaller than the regular one. The `slim` binary is compressed with [UPX](https://upx.github.io), and self-extracts at start.

There are a few reasons I still distribute a regular binary:
- UPX lacks support for some platforms
- there's a very (like, infinitesimally) slight  chance that the `slim` binary could exhibit some form of bug related to being compressed
- there could be environments where UPX-compressed binaries are disallowed

**Comment by hairyhenderson** [comment]
I'm realizing that the documentation is silent on these binaries, so I'll add some docs about this 😉

**Comment by yermulnik** [comment]
Thanks for explanation
