### ISSUE TITLE
Add slugify

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#336]
@hairyhenderson We're using gomplate extensively. One of our use-cases is creating the final YAML files for Kubernetes in our CI/CD pipeline. We're currently using some bash (sed/regexp) magic to slugify the branch name into a domain name that can be used.

It would be great if this can be added to gomplate natively.

Maybe as easy as adding this lib: https://github.com/gosimple/slug

**Comment by chillichicken** [comment]
@estahn could you provide a pull request  ?

**Comment by hairyhenderson** [comment]
Sounds like a good feature! I can add this, if you're not already working on this @estahn.

**Comment by hairyhenderson** [comment]
PR incoming...

**Comment by estahn** [comment]
Yeah, I already have this working on mine. I can commit shortly.

**Comment by estahn** [comment]
See #340

**Comment by estahn** [comment]
@hairyhenderson Is there anything else missing before this can be released?

**Comment by hairyhenderson** [comment]
@estahn there's 1 other thing I wanted to put into the release, but it can wait - I'll get this released today - sorry about the delay!
