### ISSUE TITLE
Multiple template engine support?

### ISSUE THREAD

**Issue by htfy96** [hairyhenderson/gomplate#337]
Hi,
Is there any plan for this project to support template engines other than `text/template`? Currently we need to write `M x N` copies of code with `M` template engines and `N` data sources in multiple languages, would it be great if we can use a simple tool to support all template formats? If so, I think `pongo2` would be a great addon since it already provides Go library.

**Comment by htfy96** [comment]
The design of Go's `text/template` only allows one parameter (the dot `.`) for template definitions, which is cumbersome when you need to call a template with parameters from different levels of data source. Moreover, in such design the template definition does not explicitly specify which parts of `.` does it need.

## Example
### Data source
```yaml
- value: 456
  many_other_field: blahblah
  lists:
    - aaa
    - bbb
    - ccc
- value: 123
  many_other_field: blahblah
  lists:
    - bcd
    - def
```

### text/template
```
{{ $cfg := (ds "cfg") }}

{{ range $single := $cfg }}
{{ range $item := $single.lists }}
{{/* how to abstract the common parts in each block ? */}}
block1 {
  Complex templates about {{ $single.value }} {{ $item }}
}

block2 {
  Complex templates about {{ $single.value }} {{ $item }}
}

block3 {
 Complex templates about {{ $single.value }} {{ $item }}
}

{{ end }}
{{ end }}
```

### pongo2
```
{% macro block_contents(singleValue, item) %}
   Complex templates about {{ singleValue }} {{ item }}
{% endmacro %}

{% with cfg = ds.cfg %}
{% for single in cfg %}
{% for item in cfg.lists %}

block1 {
    {{ block_contents(single.value, item) }}
}

block2 {
    {{ block_contents(single.value, item) }}
}

block3 {
    {{ block_contents(single.value, item) }}
}
```

**Comment by hairyhenderson** [comment]
🤔 Interesting... I'm not sure I _fully_ understand the use-case, but I think maybe #210 is related. One way to call a template with multiple parameters is to use [`conv.Slice`](https://gomplate.hairyhenderson.ca/functions/conv/#conv-slice), and I have vague plans to implement  a function that can create a `map[string]interface{}` for passing more complex objects (like a context) to templates.

As far as adding support for or switching to a different templating engine, I'm not sure that's necessary, and I'd rather that gomplate stay focused on the `text/template` syntax and templating engine.

**Comment by hairyhenderson** [comment]
> I have vague plans to implement a function that can create a map[string]interface{} for passing more complex objects (like a context) to templates.

That's now done in #393 - I'm going to assume this meets the original needs in this issue. If not, feel free to re-open this issue 🙂
