### ISSUE TITLE
AWS KMS Support

### ISSUE THREAD

**Issue by jbialy** [hairyhenderson/gomplate#342]
I think it'd be cool to have KMS support in `gomplate` allowing "on-the-fly" encryption while templating values. 

The idea's inspired by a tool called [Shush](https://github.com/realestate-com-au/shush) that I came across recently when looking for a way to encrypt sensitive information using AWS KMS.

**Comment by jbialy** [comment]
Maybe a function similar to `crypto`? Say, something like this:

```
gomplate -i '{{ "foo" | kms.Encrypt alias/app-secrets }}'
```

Encrypt could accept either an alias or a kms key-id or even an ARN. The resulting output would be a ciphertext. 

```
gomplate -i '{{ CyphertextBlob | kms.Decrypt }}'
```

Would obviously decrypt the message/string.

I first need to do a bit more work with KMS to understand it better and poke around the `gomplate` source code! :smile:

**Comment by pvdvreede** [comment]
as for usage as a datasource, could it be something like:

```
$ gomplate -i '{{ (ds "mysecret") }}' -d mysecret=aws+kms://<kms-key/alias>@<encryptedblob>
my decrypted secret
```
not sure if `@` appears in base64, otherwise another character that could not be part of a encrypted KMS blob.

**Comment by jbialy** [comment]
@pvdvreede, I'm just getting back to this now. Thanks for you suggestions. I see your point about implementing the KMS encrypt/decrypt support as a datasource but I'm thinking that making it a function will make the encryption/decryption more seamless?

For example, using a datasource (as per your example): 

```
$ gomplate -i '{{ (ds "mysecret") }}' -d mysecret=aws+kms://<kms-key/alias>@<encryptedblob>
```

while using a function, there's no need to define a datasource on the command line:

```
gomplate -i '{{ CyphertextBlob | kms.Decrypt }}'
```

I'm just thinking that the KMS functionality should add as little bulk as possible to both your template and how you run gomplate in order to process that template. As for AWS auth, I believe that the existing AWS functions (EC2Meta, etc) already assume that the user has ambient credentials in their environment?  

That's just my opinion though, and there's nothing wrong with having a function and also a datasource supports KMS 😄
