### ISSUE TITLE
Can't evaluate field Trunc in type *funcs.StringFuncs

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#347]
Command:
```
 gomplate -i '{{ "hello, world" | strings.Trunc 5 }}'
```

Error:
```
template: <arg>:1:20: executing "<arg>" at <strings>: can't evaluate field Trunc in type *funcs.StringFuncs
```

**Comment by hairyhenderson** [comment]
@estahn what version of gomplate? where was it installed from? My guess is that you're using an older version of gomplate, as `strings.Trunc` was only just recently added in version [2.6.0](https://github.com/hairyhenderson/gomplate/releases/tag/v2.6.0).

**Comment by estahn** [comment]
@hairyhenderson Well, on point as usual. I used `2.5.0`. Updated and working. 👍
