### ISSUE TITLE
Need to be able to override output file permission

### ISSUE THREAD

**Issue by lystor** [hairyhenderson/gomplate#368]
Hello

Since v2.5 gomplate creates output files with 464 instead of 644 permissions.

for i in {2..7}; do
./gomplate_linux-amd64-slim-2.$i.0 -f backend/values.yaml.template -d inventory.services.json -o 2.$i.0.txt
done

$ umask
0002

$ ls -l *txt
-rw-r--r-- 1 xxx xxx 2954 Aug  1 13:22 2.2.0.txt
-rw-r--r-- 1 xxx xxx 2954 Aug  1 13:22 2.3.0.txt
-rw-r--r-- 1 xxx xxx 2954 Aug  1 13:22 2.4.0.txt
-r--rw-r-- 1 xxx xxx 2954 Aug  1 13:22 2.5.0.txt
-r--rw-r-- 1 xxx xxx 2954 Aug  1 13:22 2.6.0.txt
-r--rw-r-- 1 xxx xxx 2954 Aug  1 13:22 2.7.0.txt

Please fix the bug.

Thank you

**Comment by hairyhenderson** [comment]
@lystor thanks for logging this issue!

Unfortunately I can't reproduce this:

```console
localhost:~# for n in `seq 2 7`; do curl -sSL https://github.com/hairyhenderson/gomplate/releases/download/v2.${n}.0/gomplate_linux-amd64-slim -o gomplate-2.${n}.0; done
localhost:~# chmod 755 gomplate-2.*
localhost:~# for n in `seq 2 7`; do ./gomplate-2.${n}.0 -i 'foo' -o out-${n}; ls -alh out-${n}; done
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-2
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-3
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-4
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-5
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-6
-rw-r--r-- 1 root root 3 Aug  1 13:11 out-7
```

Also, on macOS with the non-slim binary:

```console
$ for n in `seq 2 7`; do ./gomplate-2.${n}.0 -i 'foo' -o out-${n}; ls -alh out-${n}; done
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-2
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-3
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-4
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-5
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-6
-rw-r--r-- 1 dee 3 Aug  1 09:13 out-7
```

I set my `umask` on both systems to `0002`, though usually I run with `0022` (mildly safer that way).

This line is responsible for setting the mode: 

https://github.com/hairyhenderson/gomplate/blob/fbb3f3f9dde228494b8d91698d7e11b749d2b88e/template.go#L63

and referenced here:

https://github.com/hairyhenderson/gomplate/blob/fbb3f3f9dde228494b8d91698d7e11b749d2b88e/template.go#L51

and finally, used here:

https://github.com/hairyhenderson/gomplate/blob/fbb3f3f9dde228494b8d91698d7e11b749d2b88e/template.go#L187

Can you give me some more details on your system? I'm assuming you got the binaries from the releases page?

**Comment by lystor** [comment]
> Can you give me some more details on your system? 

Ubuntu 16.04.5 LTS

> I'm assuming you got the binaries from the releases page?

Sure

It seems I have found the cause of this strange behavior: 
gomplate 2.5+ copies permissions from template file to output file.

```
$ touch in
$ chmod 420 in

$ rm -f out*

$ for n in `seq 2 7`; do 
    ./gomplate-2.${n}.0 -f in -o out-${n}
done

$ ls -l out*

-rw-r--r-- 1 warface warface 0 Aug  1 16:47 out-2
-rw-r--r-- 1 warface warface 0 Aug  1 16:47 out-3
-rw-r--r-- 1 warface warface 0 Aug  1 16:47 out-4
-r---w---- 1 warface warface 0 Aug  1 16:47 out-5
-r---w---- 1 warface warface 0 Aug  1 16:47 out-6
-r---w---- 1 warface warface 0 Aug  1 16:47 out-7
```

Could you please revert this behavior to v2.4?

We use Perforce and all of our templates are read only (all files without changes are read-only in Perforce VCS).

As a result we can't run gomplate multiple times with same output file because gomplate creates it also with read-only permissions and is not able to rewrite it.

Thank you

**Comment by lystor** [comment]
> How does this sound?

Also you can add --chmod=MODE option. 
rsync has the same for example. 
It will provide more flexibility to gomplate than --inherit-perms.

**Comment by hairyhenderson** [comment]
@lystor I've changed the title, hope you don't mind. I'm hoping to implement this in the next few days.

**Comment by lystor** [comment]
> I've changed the title, hope you don't mind. 

No problem

> I'm hoping to implement this in the next few days.

Thank you
