### ISSUE TITLE
go get not install executable

### ISSUE THREAD

**Issue by acesyde** [hairyhenderson/gomplate#386]
Hi,

I follow your documentation for install gomplate cli with go get method

[Documentation](https://gomplate.hairyhenderson.ca/installing/#install-with-go-get)
```
$ go get github.com/hairyhenderson/gomplate
$ gomplate --help
```

Result 
`bash: gomplate: command not found`

PATH for go bin is ok, works with others libraries

Checked on :
* Windows 10  > Not work
* Ubuntu 18.04 > Not work

Thks,

**Comment by hairyhenderson** [comment]
Thanks for logging this issue, @acesyde! Indeed, the documentation lied to you! 😲

The command now lives in the `cmd/gomplate` subdirectory, so you'll want:

```
go get github.com/hairyhenderson/gomplate/cmd/gomplate
```

I'll update the docs to reflect this!

**Comment by acesyde** [comment]
Haha thanks a lot you save my day ;)

And thks for your work it's very usefull

**Comment by hairyhenderson** [comment]
you're welcome! Glad you're finding gomplate useful 😁

**Comment by hairyhenderson** [comment]
(reopening so I can close this with #388 😝)
