### ISSUE TITLE
ERROR :  function "required" not defined

### ISSUE THREAD

**Issue by lktslionel** [hairyhenderson/gomplate#398]
Hello,

It looks like the [example](https://gomplate.hairyhenderson.ca/functions/test/#examples-2) for `test.Required` helper doesn't work. 

When I run : 

```
FOO=foobar gomplate -i '{{ getenv "FOO" | required "Missing FOO environment variable!" }}'
```

I got this error output : 

```
template: <arg>:1: function "required" not defined
```

Thanks in advance
Regards

**Comment by hairyhenderson** [comment]
I responded in a Twitter DM, but just so it's clear to others who may run into this - that function is not in a gomplate release yet. The docs follow whatever’s in the master branch unfortunately. I'll try to get a release out soon!
