### ISSUE TITLE
Function defineDatasource pollutes output

### ISSUE THREAD

**Issue by vadim-hleif** [hairyhenderson/gomplate#399]
## what
* Need to silence function output in rendered template

## why
* It pollutes rendered template
* Example doesn't have such behaviour

# references
* https://gomplate.hairyhenderson.ca/functions/data/#examples-1

![image](https://user-images.githubusercontent.com/11632146/45482078-62a2c780-b74d-11e8-8c18-d121a909db64.png)

**Comment by hairyhenderson** [comment]
Hi @vadim-hleif, thanks for reporting this! The docs are at fault here - that function returns the datasource itself, so you can use it later.

So the correct usage would be something like:

```
{{ $person := defineDatasource "person" "person.json" }}Hello {{ $person.name }}
```

**Comment by vadim-hleif** [comment]
@hairyhenderson yes, function returnes datasource, but it's just some path, how i can get access to properties like in you example?
![image](https://user-images.githubusercontent.com/11632146/45518714-bf849900-b7b2-11e8-9294-c7258a7806d8.png)

**Comment by hairyhenderson** [comment]
@vadim-hleif Ah, nuts. Clearly I never properly tested that particular usage 😞

It's not a path, what you're seeing is the string representation of a `*data.Source`. Now that I think about it, it's not what I want to return anyway, and this sort of usage would never properly work anyway!

I broke this in #356. I think I have a reasonable fix for this, so I'll issue a PR _real soon!_

Sorry about this!
