### ISSUE TITLE
Add datasources to root context

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#404]
This is an _extraction_ from #210, where one of the items that @f4tq worked on was the removal of the need for the `datasource`/`ds` function, by adding datasources to the root context (i.e. the default `.` in a template).

I'm not 100% certain this can fully work, though the initial work done by @f4tq in [his fork](
https://github.com/f4tq/gomplate/commit/c4145ea086da1deeca0cecd278c63e0dad92d2b3) works for the simple case (i.e. datasource with no arguments).

This would make the following commands equivalent:

```console
$ gomplate -d config=some:///config/source -i '{{ (ds "config").value }}'
$ gomplate -d config=some:///config/source -i '{{ .config.value }}'
```

Still to figure out:
- what to do about datasources that take multiple (required or optional) arguments? do we ignore these and only support the simple case?
- a key designs around datasources is that they're lazily-loaded, and this needs to be retained - i.e. a datasource is only read when needed (i.e. when the `datasource` function is executed), and if `datasource` is never called (due to a negative `if` condition, for example), gomplate must not attempt to read the datasource at all
- we can't break current usage of `.Env` - this should be straightforward, though

**Comment by ArcticSnowman** [comment]
Maybe take a look at Helm and how its' template processor includes the data as a `.Values` in the context.

**Comment by hairyhenderson** [comment]
@ArcticSnowman helm doesn't load `.Values` dynamically (or, any of the other items in the context), so it doesn't have this challenge 😉.

I'm basically taking the pre-load approach in #424 - the tradeoff then is if you want to use a datasource in your context, it'll be pre-loaded.

**Comment by ArcticSnowman** [comment]
True it loads them as start time..   I was using helm template as a general purpose template processor but they made a change recently that assumed the output was YAML and force some YAML lint standard. So I came across you tool and I am converting over to it...

For now I simple load the datasource into a variable at the start of the templates and that allow me to fake the values stored in a context..

```
{{- $values := datasource "values" -}} 
```

**Comment by assayire** [comment]
> True it loads them as start time.. I was using helm template as a general purpose template processor but they made a change recently that assumed the output was YAML and force some YAML lint standard. So I came across you tool and I am converting over to it...
> 
> For now I simple load the datasource into a variable at the start of the templates and that allow me to fake the values stored in a context..
> 
> ```
> {{- $values := datasource "values" -}} 
> ```

This saved my day. Thank you so much.

@hairyhenderson Is `{{ .config.Name }}` possible today? I am not sure if I saw or just imagined `-d .=context.json` that would allow me to `{{ .Name }}`. That would be great because I am dealing with just one datasource.

**Comment by hairyhenderson** [comment]
@assayire See https://docs.gomplate.ca/syntax/#the-context

Also please use [Discussions](https://github.com/hairyhenderson/gomplate/discussions) for questions like this.. This issue was closed over 5 years ago and so can easily get ignored.
