### ISSUE TITLE
How to import/load a template with another template without using "define"

### ISSUE THREAD

**Issue by lktslionel** [hairyhenderson/gomplate#419]
### Feature:

**As A** : User 
**I want to** : Include a gomplate file within another one
**In order to** : Use share subset of templates across multiple other templates. The behavior is similar to *nested templates* without the need to keep all template definition within the main template file.

#### Include a template file within another

**Given** : A template file called `main.gomplate`
**And** : The following content:

```
{{  import 'common.gomplate' }}

{{ template "TPL_HELLO" "World" }}
```

**And** : Another template file called `common.gomplate`
**And** : The following content:
    
```
{{ define "TPL_HELLO" -}}
Hello {{ . }}!
{{- end -}}
```

**When** : I Run `gomplate < main.gomplate`
**Then** : It should output : 
```
Hello World!
```

### Information

This is achieved using the keyword `import` or `load`. The same task could have been done using something like `{{  include 'common' }}` and making sure that `gomplate` insert the content `common.gomplate`, parse and then evaluate the whole `main.gomplate` file, to produce the same output.

Thanks in advance.

**Comment by hairyhenderson** [comment]
@lktslionel Thanks for logging this detailed feature request!

Just to be clear, you're looking for something _different_ from [external nested templates](https://gomplate.hairyhenderson.ca/syntax/#external-templates), correct?

I think this approach was discussed in #210 but the final design (#403) requires a command-line argument.

A similar approach that I've thought about is the ability to render a given input string as a template, so you could do something like:

`main.tmpl`:
```
{{ tpl (file.Read "hello.tmpl") }}
```

`hello.tmpl`:
```
Hello World!
```

```console
$ gomplate -f main.tmpl
Hello World!
```

Where `tpl` would be a new function that acts the same as `template`, except the first argument is the template itself, not the name of a template.

Does that sound OK?

**Comment by lktslionel** [comment]
Yeah this sounds great !!!!! 

> Just to be clear, you're looking for something different from external nested templates, correct?
That's correct!

Again thanks for this great/awesome project.
