### ISSUE TITLE
Add quote/squote functions from sprig

### ISSUE THREAD

**Issue by ArcticSnowman** [hairyhenderson/gomplate#429]
Add quote/squote functions from sprig..

http://masterminds.github.io/sprig/strings.html

**Comment by hairyhenderson** [comment]
Instead of `quote`, you can use `printf "%q"`:

```console
$ gomplate -i '{{ "foo" | printf "%q" }}'
"foo"
```

For `squote` you can use `printf "'%s'"`:

```console
$ gomplate -i "{{ \"foo\" | printf \"'%s'\" }}"
'foo'
```

Obviously `squote` is quite a bit less convenient to emulate.

I'm not opposed to adding these functions for convenience, though.
