### ISSUE TITLE
Add option to suppress the generation of template if empty

### ISSUE THREAD

**Issue by ArcticSnowman** [hairyhenderson/gomplate#430]
In our use case the datasource has boolean values to control the generation of certain templates.

There should be an option to suppress the creation of an output file if the template generated no output.

**Comment by ArcticSnowman** [comment]
or a command line option?

**Comment by ArcticSnowman** [comment]
Going to take a stab at implementing this...  any suggestion?
Maybe do it as a cleanup hook?

**Comment by ArcticSnowman** [comment]
The code in helm is https://github.com/helm/helm/blob/master/cmd/helm/template.go#L239-L250

**Comment by hairyhenderson** [comment]
Ah. Thanks @ArcticSnowman. Helm's approach is to buffer the data in memory first then write it out if it's got anything. gomplate renders the template directly into the file, streaming rather than buffering it. I prefer the streaming approach.

**Comment by ArcticSnowman** [comment]
This make any change to that stream a careful change to do...

**Comment by hairyhenderson** [comment]
@ArcticSnowman not sure if you got anywhere with this, but I've had a stab at it - in #439 - what do you think?

**Comment by ArcticSnowman** [comment]
Yeah not real work got in the way... I'll take a look...
