### ISSUE TITLE
it does not actually support using env var as data source

### ISSUE THREAD

**Issue by SongGithub** [hairyhenderson/gomplate#433]
I followed the [official doc](https://gomplate.hairyhenderson.ca/datasources/#using-env-datasources)
If I ran: 
```
$ export foo='{"one":1, "two":2}'
$ gomplate -d foo=env:/foo?type=application/json -i '{{ (ds "foo").two }}'
```
It should be expected to see result: 2

But instead, it errors `zsh: no matches found: foo=env:/foo?type=application/json`

using both Gomplate v2.7 & v3.0

**Comment by hairyhenderson** [comment]
@SongGithub very strange! This works for me:

```console
$ export foo='{"one":1, "two":2}'
$ gomplate -d foo=env:/foo?type=application/json -i '{{ (ds "foo").two }}'
2
$ gomplate -d foo=env:///foo?type=application/json -i '{{ (ds "foo").two }}'
2
```

This was in zsh 5.6.2 on macOS 10.13.6, with gomplate 3.0.0

This also works in a Docker container (Alpine Linux 3.8, gomplate 2.6.0):

```console
docker run -it --rm alpine:3.8
/ # apk add --no-cache gomplate
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ca-certificates (20171114-r3)
(2/2) Installing gomplate (2.6.0-r0)
Executing busybox-1.28.4-r0.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 30 MiB in 15 packages
/ # export foo='{"one":1, "two":2}'
/ # gomplate -d foo=env:/foo?type=application/json -i '{{ (ds "foo").two }}'
2
```

I suspect your shell has a setting that's causing it to interpret the `?` character (see also [this](https://apple.stackexchange.com/questions/254014/zsh-no-matches-found)). Try enclosing the datasource in quotes, or escaping the `?`:

```console
$ gomplate -d 'foo=env:/foo?type=application/json' -i '{{ (ds "foo").two }}'
2
$ gomplate -d foo=env:/foo\?type=application/json -i '{{ (ds "foo").two }}'
2
```

This is, however, not a gomplate bug, so I will be closing this issue - feel free to update if you find out what caused this!
