### ISSUE TITLE
break/continue in a range.

### ISSUE THREAD

**Issue by jurgenweber** [hairyhenderson/gomplate#440]
as per; https://stackoverflow.com/questions/43485290/how-to-use-continue-and-break-keywords-in-golang-templates

> The new actions {{break}} and {{continue}} break out of the innermost  {{range ...}} loop, like the corresponding Go statements.

This was introduced in golang version 1.10, I am using gomplate version 2.8.0 which uses golang 1.11.

When I try to use it:

```
template: example.tmpl:167: function "continue" not defined
```

**Comment by hairyhenderson** [comment]
@jurgenweber unfortunately, they were only present in a 1.10 beta - they weren't released as part of the 1.10 release, and are not there in 1.11 either.

The feature was reverted, and the issue has been re-opened: https://github.com/golang/go/issues/20531

So, until that feature is re-implemented and provided in a Go release, gomplate will not be able to support it 😞

**Comment by jurgenweber** [comment]
yeah, I started digging around and go to the same place. Was coming back to this.

Thanks

**Comment by ostavnaas** [comment]
With go 1.18 now supports break and continue in templates again https://tip.golang.org/doc/go1.18 
Would be nice to see a gomplate build with 1.18

**Comment by hairyhenderson** [comment]
@ostavnaas yup! the next one (3.11) will be built with 1.18. Shouldn't be _too_ long now...
