### ISSUE TITLE
cross platform installer - GoFish

### ISSUE THREAD

**Issue by gedw99** [hairyhenderson/gomplate#441]
https://github.com/fishworks

This is a 100% golang based installer for Desktops.
Its being used for lots of tools that golang programmers use but because its golang and cross platform its great for anything.

Might be a good way to get gomplate out there for windows..

Its also very easy to use.

**Comment by hairyhenderson** [comment]
@gedw99 thanks for logging this! It's an interesting idea. I've thought about distributing gomplate with [Chocolatey](https://chocolatey.org) in the past, but I don't have easy access to a Windows system for development.

I'm open to having gomplate installable by GoFish. I'll have a look and see what's involved. Thanks again for the tip!

**Comment by gedw99** [comment]
I just played around with gofish.
Its sems quite polished.
Its easy to make the manifest and publish a package, and it worked on MacOS, Windows and Linux first time. 

A simple make file example for a package to be generated for Gofish
````


# just to run some scenarios to leanr what it can do.

LIB_BIN=$(PWD)/./gofish


print:
	@echo
	@echo LIB -
	@echo LIB_BIN : $(LIB_BIN)

	@echo

help: 

	$(LIB_BIN) home

	$(LIB_BIN) -h

dep:
	go get github.com/xlab/treeprint
	cd $(GOPATH)/src/github.com/xlab/treeprint && go install

init:
	# to setup an environment here:
	# /usr/local/Fish
	# /usr/local/Fish/Barrel
	# /usr/local/Fish/Rigs
	# /usr/local/bin
	# /Users/apple/Library/Caches/Fish

	$(LIB_BIN) init

code:
	# see what its doing..
	code /usr/local/Fish

list:
	$(LIB_BIN) tank

create:
	$(LIB_BIN) create foo

install:
	$(LIB_BIN) install --log-level 9001 foo






````

**Comment by hairyhenderson** [comment]
@gedw99 see https://github.com/fishworks/fish-food/pull/81 😉

**Comment by hairyhenderson** [comment]
Merged into GoFish!
