### ISSUE TITLE
Consider using region from instance metadata for SSM if none is specified

### ISSUE THREAD

**Issue by jen20** [hairyhenderson/gomplate#458]
Currently, it's necessary to specify the `AWS_REGION` environment variable or use a shared configuration file when using AWS SSM.

This is inconvenient if you want to package up templates in a region-agnostic manner (to be executed as a systemd `ExecStartPre`, for example), since you have to modify the systemd unit in place, or set up shared configuration files which have no other purpose if using instance profiles.

I think the code path for SSM should be changed such that if no region is set in the environment, we default to the region in which the instance is running - determined via the instance metadata - in order that no additional configuration is needed.

If you're willing to make this change I'll be happy to submit a pull request implementing it.

**Comment by hairyhenderson** [comment]
@jen20 thanks for catching this - I thought for some reason that instance metadata was already considered, but clearly it's not! A PR would be most welcome, or I can work on this if you don't have the time anymore!
