### ISSUE TITLE
Missing some map functions for data merging

### ISSUE THREAD

**Issue by niflostancu** [hairyhenderson/gomplate#467]
Hello,
I'm missing most of Sprig's [dicts](http://masterminds.github.io/sprig/dicts.html) and [lists](http://masterminds.github.io/sprig/lists.html) functions. Specifically, the `keys`, `uniq`, `merge`, `append` were extra useful.

My use case: I want to have two data sources for configuration file templates: a defaults.yaml (with the default values, ofc) + user's config.yaml. Most of the time, the configuration is structured as such:
```yaml
section1:
   conf_key1: value1
   conf_key2: value2
section2:
   # ...
```

Now, I need to merge the two data sources together, but keys that are present in one might not be in the other. So the template needs to merge the list of keys from both maps and iterate through them all (aka union of sets):
```
{{ $configKeys := ((keys $userConfig $defaults | sortAlpha) | uniq) -}}
{{ range $key := $configKeys }}
  {{ $defaultVal := (index $defaults $key) -}}
  {{ $val := (or (index $userConfig $key) $defaultVal) -}}
  ...
```
Note that, if $val is a map, I can nest similar statements and further merge them.

I can't do this anymore using **gomplate** because of those missing functions. I need to be able to create new sets based on data source contents, but go templates lack the means to do so, by default.
I know that this kind of logic should not be inside templates, but hey, so is the datasources concept ;) I just don't want to write custom data processing scripts just to merge some maps together.
Thanks.

**Comment by ppmathis** [comment]
@hairyhenderson I think this is a very good idea, as I recently started using gomplate and quickly discovered how ugly templates will turn out when having to specify default values straight in the template files. It makes them quite hard to read and when the same value gets used multiple times, there is even more duplication. The absolutely worst thing is when you're starting to deal with nested dictionaries, as things are getting crazy that way, at least when doing it in Go's text/template library... :)

An additional bonus of a separate defaults file is that users of the Docker image (or wherever gomplate is being used) can easily see all supported values and their defaults at once, without having to go dig into template files. I assume your proposal would recursively merge dictionaries while overwriting lists/slices? This would be the behavior I expect, but I think it makes sense to clearly define how merging behaves.

**Comment by hairyhenderson** [comment]
> I assume your proposal would recursively merge dictionaries while overwriting lists/slices? This would be the behavior I expect, but I think it makes sense to clearly define how merging behaves.

Yes, that's what I was thinking. Most map-merging I've seen in the wild behaves this way, even though it's sometimes a pain!

For reference, the library I'm currently playing with for the purpose is https://github.com/imdario/mergo (which is what Sprig's `merge` function uses).
