### ISSUE TITLE
env_file as a file format

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#479]
I currently have an env file (e.g. file full of NAME=value pairs).  We use it in our dev environment.  However, I need to transform it into a son file for production.  As such I'd like to use it as a datasource in Gomplate.

I currently do not see a way to do that.  It certainly is not listed as a file type support by the datasource option.  But maybe there is another way?

Or is this a feature request?  I'd like to do this:
```
echo DOG=bark > myenv.env
gomplate -d myenv.env -I 'The dig will {{ (datasource "myenv").DOG }}'
The dog will bark
```

**Comment by hairyhenderson** [comment]
Hi @rayjlinden, thanks for logging this! This seems like a good idea to me, and should be quite straightforward to implement.

**Comment by hairyhenderson** [comment]
I've renamed the title, since this doesn't involve a new _datasource_, but instead a new _file format_ (or MIME type if you prefer). 😉
