### ISSUE TITLE
gomplate docker image v3.2.0 failed to build

### ISSUE THREAD

**Issue by sarcasticadmin** [hairyhenderson/gomplate#484]
In dockerhub it looks like the most recent build v3.2.0 failed: https://hub.docker.com/r/hairyhenderson/gomplate/builds

**Comment by hairyhenderson** [comment]
@sarcasticadmin thanks for letting me know! I'll get it back up and running and will report here when it is.

**Comment by sarcasticadmin** [comment]
@hairyhenderson you're welcome! Im looking forward to being able to use `v3.2.0` container!

**Comment by hairyhenderson** [comment]
😅 You might've noticed a couple hours ago, but it's fixed now, and new tags have been pushed 😬

**Comment by sarcasticadmin** [comment]
@hairyhenderson I just had a chance to look at it, thank you so much!
