### ISSUE TITLE
Is it possible to generate multiple output files from one template?

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#485]
I have a datasource (a Yaml file) with a bunch of services  listed.  For each service, I need to create a Dockerfile - all will be built with the same template  - which some things varying by the service name.

So I have one template - and want to create N files with that template based on the data.

How can I do that with Gomplate?  I feel like it should be possible but am struggling to think how.

**Comment by hairyhenderson** [comment]
@rayjlinden I'm pretty sure I've had this request before, and I've got a bunch of use-cases for it too... But, unfortunately, it's not possible right now 😞

I'm open to ideas about how to do this, especially - how should the user interface look? I'm wondering if there'd be some crossover with #288...

**Comment by rayjlinden** [comment]
Well, my instinct when I was looking for the solution was to look in the functions.  I was thinking it could work something like this:
```
{{ range (datasource "services").services -}}
{{ gomplate (print "rel/path/", $service, ".json") (usetmpl "template")}}
{{end }}
```
(With the assumption that variables, data sources, named templates, etc. would pass down...  E.g. The sub template might need $service and another datasource pass into the command line.)

Go meta!  :) . Not 100% sure about the above syntax - but it seems to me having the ability to recursively generate templates within a template offers much more power than trying to do something via command line options.

**Comment by hairyhenderson** [comment]
> but it seems to me having the ability to recursively generate templates within a template offers much more power than trying to do something via command line options.

yeah, I see your point - I've been shying away from functions that can write directly to the filesystem, mostly because of the lack of precedent. There's also a slightly increased risk, since datasources (and probably templates at some point) can come from remote sources, and it would be non-trivial to find out how many new files would be created as a result. Not that this means this isn't a good idea 😉

I'm just brainstorming here, but maybe something like this could work:

_`in.tmpl`_:
```
{{- define "config" }}
{{- .config | data.ToJSONPretty }}
{{ end }}
{{ range (ds "services").services -}}
{{ $outPath := path.Join .name "config.json" }}
{{ templateOut "config" . | output $outPath }}
{{ end }}
```

```console
$ gomplate -d services.yaml -f in.tmpl --output-dir outputs/
...
```

If the `services` key had a two-element array as its value, each with `name` keys of `foo` and `bar`, This would end up with `outputs/foo/config.json` and `outputs/bar/config.json`.

There'd be two new functions here:
- `templateOut` would work exactly like the `template` built-in, except instead of printing the output it'd return it as a `string`. Not sold on the name though - see also  #444 for some discussion on this exact thing.
- `output` (also not sold on the name) would take as arguments a path and some data to write to a file at that path
  - I'm thinking `--output-dir` may be relevant here - it could be used as the base path to which all other `output` paths are joined (to reduce the risk of writing data to dangerous or unexpected places)

I'll keep thinking about this, but interested if this seems useful!

**Comment by rayjlinden** [comment]
I like the decomposition into the two parts.  The "templateOut" (maybe
template.ToString ?) would have the same semantics as template function and
would be easy to understand (and have more uses than just this use case.)

The "output" function (maybe file.Write ?)  is then a pretty simple, easy
to understand function as well.

I love it.  Indeed, I would start using it the day it ships!  :)

Ray

P.S.  Thanks for shipping the .env file reader stuff.  Already using that
as well!

**Comment by rayjlinden** [comment]
One question:  If the example looked like this:
```
{{- define "config" }}
{{- .config | data.ToJSONPretty }}
{{ end }}
{{ range $service := (ds "services").services -}}
{{ $outPath := path.Join .name "config.json" }}
{{ templateOut "config" . | output $outPath }}
{{ end }}
```

How can one pass the current $service to the template.  I assume you could do this:
```
{{ templateOut "config" $service | output $outPath }}
```

But if you do would you then lose .Env, etc?  (Or would you just need to access as $.Env?)

**Comment by hairyhenderson** [comment]
> The "templateOut" (maybe template.ToString ?) would have the same semantics as template function and would be easy to understand (and have more uses than just this use case.)

`template.ToString` sounds good, except `template` is taken (by the `template` keyword 😉). It'd need to be `templates.ToString` maybe, or `tmpl.ToString` or something... I'll ponder that a bit more!

> The "output" function (maybe file.Write ?) is then a pretty simple, easy to understand function as well.

`file.Write` occurred to me as well, except that it would likely have to be able to write anywhere in the filesystem, given that `file.Read` can _read_ from anywhere in the filesystem. I'm not super-comfortable with that, given the security risks.

I'd much rather have a function that's intended for the sole purpose of writing output files, confined to the `--output-dir` - that way the user has at least _some_ control over where files will be written. Also, thinking further about it, that function would also need to have a side-effect that prevents the input template from producing an output.

**Comment by hairyhenderson** [comment]
> How can one pass the current $service to the template. I assume you could do this:
>
> ```
> {{ templateOut "config" $service | output $outPath }}
> ```
> But if you do would you then lose .Env, etc? (Or would you just need to access as $.Env?)

Yes, you'd lose `.Env`. But there's always the [`env.Getenv`/`getenv`](https://gomplate.hairyhenderson.ca/functions/env/#env-getenv) function, which I find myself using much more often than `.Env` 😉

**Comment by rayjlinden** [comment]
I get what you are saying about security.  Maybe one way to deal with that
would be a command line option to turn on functionality:

--security flags (where flags can be bit-wise constant so you can combine
them.  Like File modes.)
Mode can be:
- ALLOW_WRITES
- ALLOW_WRITES_ANYWHERE (if not set it would be limited to output-dir)

The default would not have either option set and not allow writes.

This would allow you use the name file.Write with implied semantics that it
can write anywhere - but you must set appropriate security setting for
actual use.

(P.S.  The --security flag could perhaps also allow or constrain database
fetches of remote sources by something like defineDatasource.)

**Comment by hairyhenderson** [comment]
🤔 I get the idea, but it still wouldn't address the necessary side-effect to disable regular template output...

Though, thinking about it some more, perhaps that side-effect isn't necessary (or, really, desired).

How about something like this:

_`in.tmpl`_:

```
{{- define "config" }}
{{- .config | data.ToJSONPretty }}
{{ end }}
{{ range (ds "services").services -}}
{{ $outPath := path.Join .name "config.json" }}
{{ templateOut "config" . | file.Write $outPath }}
{{ end }}
```

```
$ gomplate -d services.yaml -f in.tmpl --workdir outputs/
...
```

Two things:
1. `file.Write` would be sandboxed into the current working directory by default, and could be overridden by `--workdir`. I think that strikes a good balance between flexibility and security. Relative paths would be forced, and `..` would be forbidden. Doing things like `{{ file.Write "/etc/passwd" }}` or `{{ file.Write "../../../../etc/passwd" }}` would simply error. For cases where the user really _does_ want to write to paths anywhere in the filesystem, that's still possible by setting `--workdir /` or just running with `/` as the current working directory.
  - actually, `--workdir` is probably unnecessary, at least for the time being
2. The "don't output" side-effect can pretty easily be worked around by just outputting to standard out, but ensuring that the template doesn't actually produce anything - in the example above a few newlines would be printed, and these can be eliminated with judicious use of `{{-` and `-}}`.

Ok, I think I'm closer to where I want to be - `file.Write` makes sense now (with the above parameters). I know I need a `templateOut` function, but I can't decide on the name 😂

**Comment by rayjlinden** [comment]
Those constraints would certainly work for me.  (99% of the time I'm going
to call this from a Makefile operating on a repo anyway!  :)
Some devops folks may have other opinions - but like you said running from
a different working dir it an easy work around if you really need do it.

What did you think about template.ToString?  It is a little long perhaps.
But I thought it was rather clean and clear as to what it does.

Ray

**Comment by hairyhenderson** [comment]
> What did you think about template.ToString? It is a little long perhaps. But I thought it was rather clean and clear as to what it does.

I totally agree, except that `template` can't be the namespace (conflicts with the `template` built-in) 😞

**Comment by hairyhenderson** [comment]
@rayjlinden I added `tmpl.Exec`, and with that and `file.Write`, it's now possible to generate multiple output files! I've added an integration test to make sure that specific use-case works, so you should be good to go 😉

Let me know if there's anything that doesn't quite work how you expect and I'll try to get that all squared away before the next release.

**Comment by rayjlinden** [comment]
Trying it out now.  (Though I have to on a plane in a few hours out of the country so I'm not sure when I will be able to give feedback.)  Very exciting!

**Comment by rayjlinden** [comment]
Wow.  This is really cool.  It makes my Dockerfile generation an order of magnitude faster.  (I'm generating ~70 files in the time it previously took to generate about 3.  Nice!

**Comment by hairyhenderson** [comment]
@rayjlinden awesome! Glad to hear it's working for you 🎉 - and, safe travels 🛫😉

**Comment by hairyhenderson** [comment]
@rayjlinden FYI, I blogged about this here: https://blog.hairyhenderson.ca/post/one_template_many_outputs/ 😉

**Comment by rayjlinden** [comment]
Nice blog post!  And thanks for the shout out!  :)

More importantly - thanks for writing gomplate.
It is allowing me to kill a whole bunch of weird python scripts and random
uses of sed.  It has a lot of power but I think will be fairly easy to
maintain.

Ray

**Comment by hairyhenderson** [comment]
@rayjlinden you're totally welcome. 😄
