### ISSUE TITLE
Some way to generate randomness without external scripts

### ISSUE THREAD

**Issue by Southclaws** [hairyhenderson/gomplate#487]
Would be very useful to have a function that could just do what [crypto/rand.Read](https://golang.org/pkg/crypto/rand/#Read) does with a nice simple conversion to hex or base64.

I ask because the current docker image is based on scratch, meaning it's really awkward to get a nice random string out-of-the-box for a Kubernetes config template filler.

I thought I could do this with `file.Read` on /dev/urandom but since it's a never-ending stream and there are no length controls for `file.Read` it won't work. The only thing I can think of is generating a bcrypt of some other piece of data.

**Comment by hairyhenderson** [comment]
Hi @Southclaws - yeah, I agree it'd be _super useful_ to have this functionality! There's a somewhat-related (but much larger-scoped) PR at #410, but I've been wanting to create a `random` namespace with some simple functions to get started.
