### ISSUE TITLE
A hexadecimal converter

### ISSUE THREAD

**Issue by Southclaws** [hairyhenderson/gomplate#488]
Base64 is useful for similar situations but I'm hitting a problem where a config requires a hexadecimal field and there's no way to convert a value to base 16. This would be a useful addition, let me know if I can help with a PR for this!

**Comment by hairyhenderson** [comment]
Hi @Southclaws, thanks for asking! You can do this a few different ways with the `printf` built-in:

```
$ gomplate -i '{{ 42 | printf "%X" }} {{ 42 | printf "%x" }} {{ 42 | printf "%#x" }}'
2A 2a 0x2a
```

This is just an alias to Go's `fmt.Sprintf` - see https://golang.org/pkg/fmt/#hdr-Printing for the docs on  the format 🙂

I'm going to close this for now as I think this answers your question, but feel free to re-open if you think there's something more to be done!
