### ISSUE TITLE
env.SetEnv

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#500]
I have template that calls another template.  It passes a context that is useful for the sub-template.  However, I need to now pass an additional value and constructing a more complex context is bit complicated.

I was wondering if we could get an env.SetEnv function.  This would allow to override environment variables which I think could be useful in some cases or set new ones.  In any case, it would then be easy for sub templates to read additional variables via env.GetEnv without needing to create a complex context.

**Comment by hairyhenderson** [comment]
Thanks for logging this, @rayjlinden!

I'm not _too_ opposed to the idea. Can you elaborate a bit on the use-case? Specifically, what's complicated about creating a "more complex context?" (I'm trying to see if maybe there's something more we can do to make building objects easier)

**Comment by rayjlinden** [comment]
Sure he is a part of one of my templates:
```
{{- range $repo, $repo_data :=  (datasource "data").repos}}
    {{- if $repo_data }}
        {{- range $service := $repo_data.services}}
            {{- $outFile := (print "dockerfiles/Dockerfile.generated." $service) }}
            {{- tmpl.Exec "dockerfile" $service  | file.Write $outFile }}

            {{- $outFile = (print "dockerfiles/Dockerfile.dev." $service) }}
            {{- tmpl.Exec "devmode" $service  | file.Write $outFile }}

            {{- $outFile = (printf "dockerfiles/dev-%s.yml" $service) }}
            {{- tmpl.Exec "devmode-compose" $service  | file.Write $outFile }}
        {{- end}} 
    {{- end}}
{{- end }}
```
I now want to pass $repo into each template I'm generating.  (I will eventually have one or two things hanging off repo that may also need to get passed in.)

**Comment by hairyhenderson** [comment]
You could use [`dict`](https://gomplate.hairyhenderson.ca/functions/coll/#coll-dict) to create a context, IMO would be "cleaner". But it would also require altering the templates to use a slightly different structure (i.e. reference `.service.<whatever>` instead of `.<whatever>`)

```handlebars
{{- range $repo, $repo_data :=  (datasource "data").repos}}
    {{- if $repo_data }}
        {{- range $service := $repo_data.services}}
            {{- $ctx := dict "service" $service "repo" $repo }}
            {{- $outFile := (print "dockerfiles/Dockerfile.generated." $service) }}
            {{- tmpl.Exec "dockerfile" $ctx  | file.Write $outFile }}

            {{- $outFile = (print "dockerfiles/Dockerfile.dev." $service) }}
            {{- tmpl.Exec "devmode" $ctx  | file.Write $outFile }}

            {{- $outFile = (printf "dockerfiles/dev-%s.yml" $service) }}
            {{- tmpl.Exec "devmode-compose" $ctx  | file.Write $outFile }}
        {{- end}} 
    {{- end}}
{{- end }}
```

**Comment by hairyhenderson** [comment]
@rayjlinden I played around a bit with the possible implementation for `env.Setenv`, and I'm not too sure I like the implications:

```console
$ export FOO=foo
$ gomplate -i '{{getenv "FOO"}}
{{env.Setenv "FOO" "bar" -}}
{{getenv "FOO"}} ' -- sh -c 'echo $FOO'
foo
bar bar
```

So, not only would the variable change apply to all future calls to `env.Getenv` (naturally, and also in further template files and external nested templates), but it would _also_ apply to post-run commands. There may be some interesting use-cases for that, but I'm not sure I'm willing to risk the impacts of the side-effects.

I'll sleep on it, but I think my `dict` workaround should satisfy your use-case, and I think a `env.Setenv` function will be a "no for now" 🙂

**Comment by rayjlinden** [comment]
Oh - the dict example you gave above is cleaner than what I was attempting before...

I had no idea you had an ability to run another command after the gomplate args.  I agree it would not be expected for the env to change for that command.

Of course, you could have it not do that by having the env.funcs operate on a copy of the environment.  And keep the clean version for the exec.    But I understand your point of view.

Though another part of me thinks it would be really cool to have an exec command inside templates as well.  (In which case a setenv may be more needed.) . I don't have a real use case for it at the moment - other than I love unix commands that allow you to use other unix commands in powerful ways!  (Though most use cases I'm thinking of could easily be handled by calling such commands first and passing in the results as a datasource.)

Obviously, as a developer I tend to opt for more power.  But if gomplate is used in a lot more of ops settings (with less trusted inputs) rather than dev settings I get the concern for security.

**Comment by hairyhenderson** [comment]
> it would be really cool to have an exec command inside templates as well

😱 that's _definitely_ on the "no for now" list 😉 - I'd like for it to be safe to execute "untrusted" gomplate templates (for the most part)

**Comment by hairyhenderson** [comment]
I'm going to close this for now, since I don't think there's any action that's going to come from this just yet. If there's a use-case that can't be dealt with as above, feel free to re-open 🙂
