### ISSUE TITLE
Timing for next release?

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#502]
Wondering the plans for when the next release of Gomplate will be?  Asking because we are starting the process of making new build images to support the just released Go 1.12 which will freeze tools we use for a little while.  I'd love to get those new features coming in the next release of Gomplate into that image!  :)

**Comment by hairyhenderson** [comment]
@rayjlinden ooh! I'll try to get to it over the next day or two 😬

**Comment by rayjlinden** [comment]
Any chance this might happen today?  No pressure - just trying to plan.  :)

**Comment by hairyhenderson** [comment]
Hey @rayjlinden - sorry, last week was pretty rough for me, and though I tried to fit in a release on Thursday evening, it just wasn't possible. Will try to find some time today in and around family events and commitments!

**Comment by hairyhenderson** [comment]
😅 https://github.com/hairyhenderson/gomplate/releases/tag/v3.3.0
