### ISSUE TITLE
file.Write error

### ISSUE THREAD

**Issue by kubanka-peter** [hairyhenderson/gomplate#504]
Hi, I would like to use the file.Write function but I got the following error:

./gomplate_linux-amd64 -i '{{ file.Write "foo.txt" "hello world" }}'
template: <arg>:1:3: executing "<arg>" at <file>: can't evaluate field Write in type *funcs.FileFuncs

I tired full path to current directory, relative path, but I got the some error.
Can you fix it? Thanks!

**Comment by hairyhenderson** [comment]
@kubanka-peter Thanks for trying this out! I think the problem is the version you're using - `file.Write` isn't yet available in a gomplate release - but it's coming! soon! like... in the next hour or 3 😂

**Comment by kubanka-peter** [comment]
Thx, I will wait for it (or compile the source and hope it will work)
