### ISSUE TITLE
Impossible to merge env files

### ISSUE THREAD

**Issue by AntonyCook** [hairyhenderson/gomplate#509]
Am I doing something wrong, or is it not (yet) possible to merge x-env files ?

**Comment by hairyhenderson** [comment]
Hi @AntonyCook - thanks for reporting this. How are you trying to merge env files?

**Comment by hairyhenderson** [comment]
I just tried this out, and indeed got an error 😱:

```console
$ cat 1.env
FOO=1
BAR=2
BAZ=3
$ cat 2.env
FOO=4
QUX=5
$ gomplate -c "merged=merge:./2.env|./1.env" -i '{{ .merged.FOO }}'
Couldn't read datasource 'merged': unexpected data type 'map[string]string' for datasource (type application/x-env); merge: can only merge maps
```

🤔 this seems nonsensical - a `map[string]string` _is_ a map... but I'll dig a little deeper to see what the problem is!

**Comment by hairyhenderson** [comment]
_(I've taken the liberty to change the title to express that this is, in fact, a bug 😉)_

**Comment by hairyhenderson** [comment]
I've tested this out with equivalent JSON files, and it works, so the bug is specific to how `.env` files are handled.

**Comment by AntonyCook** [comment]
Yup, that's exactly what I was getting...glad I'm not going nuts !
Thanks for quick response..love the tool...I was looking for a flexible templating solution to use instead of Helm as we've got a bunch of microservices, home grown Jenkins jobs and different yml for each service per environment. Yml and JSON merging works fine so I might just convert our properties files to yml as a workaround.

Keep up the good work!

**Comment by hairyhenderson** [comment]
@AntonyCook thanks for the kind words! The bug's fixed, and I'll have it in a release soon!

**Comment by AntonyCook** [comment]
Nice one..cheers Dave! I'll hold off my global search and replace :-)

**Comment by hairyhenderson** [comment]
@AntonyCook [v3.3.1](https://github.com/hairyhenderson/gomplate/releases/tag/v3.3.1) is out now! 😬

**Comment by AntonyCook** [comment]
excellent...tried it out and works a treat...thanks Dave.
Ant.
