### ISSUE TITLE
file.Write does not truncate file

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#512]
Looks like I found a bug in file.Write.  It does not appear to truncate the file if it already exists.

What I'm seeing is if I write to the file and it is new it works great.  If I write to it again (and the content is shorter than the first time I write to it) I get left over test from the first write in the file.

**Comment by hairyhenderson** [comment]
🤦‍♂️ Looks like I forgot to open the file with `O_TRUNC`:

https://github.com/hairyhenderson/gomplate/blob/a94e9aaf842532448567c337d512ceec3b692ebb/file/file.go#L68
