### ISSUE TITLE
"npm i gomplate" fails on Windows

### ISSUE THREAD

**Issue by MikhailSemichev** [hairyhenderson/gomplate#522]
Hello, I'm trying to run "npm i gomplate" on Windows 10.
And there is a wrong path 404 error

```
npm install gomplate

> gomplate@3.3.1 postinstall D:\ADIDAS\gmr-config-lambda\node_modules\gomplate
> go-npm install

Downloading from URL: https://github.com/hairyhenderson/gomplate/releases/download/v3.3.1/gomplate_windows-amd64-slim
Error downloading binary. HTTP Status Code: 404
```

The problem is in absence of ".exe" in download path
The correct download path should be:
```
https://github.com/hairyhenderson/gomplate/releases/download/v3.3.1/gomplate_windows-amd64-slim.exe
```

**Comment by hairyhenderson** [comment]
Thanks for reporting this, @MikhailSemichev! I'm going to move this to https://github.com/gomplate/gomplate-npm since that's where the integration lives.

**Comment by hairyhenderson** [comment]
See gomplate/gomplate-npm#4
