### ISSUE TITLE
New Datasource: AWS Secretsmanager

### ISSUE THREAD

**Issue by nexeck** [hairyhenderson/gomplate#544]
I would like to to use aws secretsmanager with gomplate.
Can we add such a feature?

I would be happy to contributing this.

**Comment by hairyhenderson** [comment]
Thanks for suggesting this @nexeck! This looks very interesting! I'm not familiar with AWS Secrets Manager, so I'll need to take some time to digest what it is. If it could work similar to the Vault datasource, that'd probably feel pretty natural.

You're absolutely welcome to contribute! I'll do my best to help the PR get in smoothly 🙂

**Comment by nexeck** [comment]
AWS Secret is similar to AWS SSM Parameterstore.
It has some benefits, like not so small limitations with rate-limiting.

**Comment by nexeck** [comment]
PR: https://github.com/hairyhenderson/gomplate/pull/549

I used the AWS SSM Parameterstore datasource as a reference, because both services are more or less identical (From what we would use for the moment, retrieving secrets/parmeters from AWS)
