### ISSUE TITLE
Switch from gometalinter to golang-ci

### ISSUE THREAD

**Issue by nexeck** [hairyhenderson/gomplate#546]
gometalinter seems to be deprecated https://github.com/alecthomas/gometalinter/issues/590
They suggest to use https://github.com/golangci/golangci-lint

**Comment by hairyhenderson** [comment]
Thanks for the heads up! I'm at a conference this week so won't have much time to look at the PR, but will definitely look at it.

**Comment by nexeck** [comment]
https://github.com/hairyhenderson/dockerfiles/pull/55 This PR is related to the failing Circle CI Lint test.

**Comment by hairyhenderson** [comment]
Fixed by #547 - thanks again @nexeck!
