### ISSUE TITLE
Needs to be easier to use programatically

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#548]
I've heard from a few different places (below) that gomplate isn't that easy to use programatically.

Right now the only way to process templates is to create a [`gomplate.Config`](https://godoc.org/github.com/hairyhenderson/gomplate#Config), and run [`gomplate.RunTemplates`](https://godoc.org/github.com/hairyhenderson/gomplate#RunTemplates). In some ways, the inflexibility was by design - I didn't want to open up too much API before being comfortable with how processing works.

It seems like the main issues are:
1. datasources should be easier to provide to the `RunTemplates` function
2. it should be possible to provide `io.Reader`s and `io.Writer`s instead of providing filenames and requiring a filesystem to be present
3. the `gomplate.Config` struct is pretty awkward to construct if you're not the CLI

There will need to be tradeoffs in which functionality is exposed programatically, perhaps the directory-walking & exclusion support isn't as necessary, for example...

**I'm looking for feedback** - is this on the right track? Am I missing something?

See also:
- #372
- https://gophers.slack.com/archives/CGTR16RM2/p1556025412029900
- https://github.com/roboll/helmfile/pull/569
- https://github.com/roboll/helmfile/issues/392

/cc @osterman @sgandon @mumoshu @bartmeuris

**Comment by sgandon** [comment]
Yesss! I believe this is the right approach, especially the removal of the filesystem oriented APIs.
I can imagine leveraging the vaul datasource for secret generation in helmfiles.

**Comment by rms1000watt** [comment]
@hairyhenderson https://github.com/roboll/helmfile/pull/573#issuecomment-489167836

Here are some of my thoughts on it. Ultimately, you guys are the maintainers, so it's all good. 

I'm also in the Cloud Posse slack if we all wanted to chat faster. 😄 

(Please feel free to 👎 if this comment in particular is off topic. It's all good! 🤣)

**Comment by hairyhenderson** [comment]
@rms1000watt thanks! I'll respond in that issue since it's more specific to that context.

I have no opinion on whether or how gomplate should be used in helmfile or not. I'm happy to make things easier for that integration though! 😉

**Comment by angelofdeauth** [comment]
gomplate + helmfile, two of my most favored tools as of recent. Nice.

**Comment by charles-dyfis-net** [comment]
Just to provide a specific use case --

I'm seriously considering generating an API-based client for gomplate to permit more nuanced error handling. Inputdir + outputdir functionality is great, except if one needs to be able to keep going on failures (possibly deleting or moving aside only the specific output files for which a template evaluation failure took place). I don't see my needs as something that necessarily map to a right-thing-for-everyone feature request for CLI-centric functionality... hence thinking about creation of a custom entrypoint.

**Comment by hairyhenderson** [comment]
@charles-dyfis-net interesting! I'd be interested to hear how that goes. Error handling is certainly an area that needs to be better fleshed out. Let me know if there's anything specific we can do in the gomplate code to make it easier for you 😉

**Comment by davidalpert** [comment]
is this issue still open/unsolved? perhaps in need of some `hacktoberfest` ❤️ ?

**Comment by hairyhenderson** [comment]
@davidalpert this is still open, though it's really much more of a meta-issue than something that can be solved easily in some kind of concrete way. While I'm absolutely open to hacktoberfest-related PRs, I don't think this would be the best issue to tackle in that context.

**Comment by hairyhenderson** [comment]
I've addressed this (finally! 😅) in #1422. For the 3.11.0 release it'll be marked as experimental (i.e. the API is subject to change), but I'd like it to be stable by the 4.0 release.

I'd be very grateful if folks could try it out and file issues (or start [discussions](https://github.com/hairyhenderson/gomplate/discussions)) to let me know if it works adequately for people!
