### ISSUE TITLE
Next release plans?

### ISSUE THREAD

**Issue by nexeck** [hairyhenderson/gomplate#553]
Are there any plans for the next release?

I would like to update gomplate in all of our microservices and build jobs in order to use the AWS Secrets Manager :-)

**Comment by hairyhenderson** [comment]
@nexeck a release indeed is overdue - will try to get that out this week 😉

**Comment by hairyhenderson** [comment]
Just wanted to follow up and let you know I haven't forgotten about this! I've had a very busy week, and am now travelling - without the laptop I usually use for releasing gomplate 🤦‍♂. I'll be back on the weekend, and will hopefully be able to cut the release then. Sorry about the huge delay!

**Comment by hairyhenderson** [comment]
https://github.com/hairyhenderson/gomplate/releases/tag/v3.5.0 😅
