### ISSUE TITLE
--exclude doesn't work with a path

### ISSUE THREAD

**Issue by dwatrous** [hairyhenderson/gomplate#554]
--exclude appears to look at only the filename. When I provide a path, it doesn't exclude. Take the following example

```
➜  docker run --rm -v ~/Documents/gitrepos/jenkins-shared-libraries/resources/api/slmconfig:/content hairyhenderson/gomplate -d data=/content/data.json --input-dir /content/ --exclude data.json --output-dir /content/rendered -V
gomplate version 3.4.0, build aae1a680 (2019-04-17T12:00:02Z)
config is:
input: /content/
exclude: data.json
output: /content/rendered
datasources: data=/content/data.json

rendered 5 template(s) with 0 error(s) in 33.4141ms
➜   docker run --rm -v ~/Documents/gitrepos/jenkins-shared-libraries/resources/api/slmconfig:/content hairyhenderson/gomplate -d data=/content/data.json --input-dir /content/ --exclude /content/data.json --output-dir /content/rendered -V
gomplate version 3.4.0, build aae1a680 (2019-04-17T12:00:02Z)
config is:
input: /content/
exclude: /content/data.json
output: /content/rendered
datasources: data=/content/data.json

rendered 6 template(s) with 0 error(s) in 42.636ms
```

Notice that when a path is provided, the data.json file is not excluded.

**Comment by hairyhenderson** [comment]
Thanks for logging this @dwatrous - indeed that won't work. The argument to `--exclude` is relative to `--input-dir`, so your example would want to exclude `/content/content/data.json`, which obviously isn't what you want 😉

The syntax is the same as for the [`.gomplateignore`](https://docs.gomplate.ca/usage/#ignorefile) file, which is (mostly) equivalent to a [`.gitignore`](https://git-scm.com/docs/gitignore) file.

Clearly the docs are lacking in this respect - I'll work on clarifying that section!
