### ISSUE TITLE
map as no entry for key

### ISSUE THREAD

**Issue by dwatrous** [hairyhenderson/gomplate#555]
I am using the latest Docker image in this example. All the files line up, but it is still failing to render

```
[Pipeline] sh
+ ls -la k8s/templates/
total 36
drwxr-xr-x    2 10000    10000          148 May 22 17:12 .
drwxr-xr-x    3 10000    10000          166 May 22 17:12 ..
-rw-r--r--    1 10000    10000          422 May 22 17:12 api-core.properties
-rw-r--r--    1 10000    10000          107 May 22 17:12 api-security.properties
-rw-r--r--    1 10000    10000         8718 May 22 17:12 context.xml
-rw-r--r--    1 10000    10000          547 May 22 17:12 data.json
-rw-r--r--    1 10000    10000         1557 May 22 17:12 environment.properties
-rw-r--r--    1 10000    10000         6479 May 22 17:12 server.xml
[Pipeline] sh
+ cat k8s/templates/data.json
{"BASE_ENVIRONMENT": "env1",
"FORGEROCK_AUTH_URL": "https://mybranch.api-gopher-cicd-k8s.company-k8s.com/companyAuth",
"AUTH_COOKIE_NAME": "company_env1",
"ENV_SSOURL": "mybranch.api-gopher-cicd-k8s.company-k8s.com",
"IMAGETAG": "jenkins-api-gopher-integration-integration-M.2019.06.01-12",
"INGRESS_URL": "mybranch.api-gopher-cicd-k8s.company-k8s.com",
"BRANCH": "mybranch",
"API_NAME": "api-gopher",
"K8S_NAMESPACE": "api-gopher-cicd-k8s"}[Pipeline] sh
+ cat k8s/templates/api-core.properties
messaging.server=messaging{{ (ds "data").BASE_ENVIRONMENT }}.hrpassport.com
messaging.port=5672
messaging.username=greenstack
messaging.password=company123

cache.redis.server={{ (ds "data").BASE_ENVIRONMENT }}brmsche01.ux.corp.local
cache.redis.port=6379
cache.redis.password=GreenStack01

batch.redis.server={{ (ds "data").BASE_ENVIRONMENT }}brmsche01.ux.corp.local
batch.redis.port=6379
batch.redis.password=GreenStack01[Pipeline] sh
+ gomplate -V -d 'data=k8s/templates/data.json' --input-dir k8s/templates/ --output-dir k8s/templates/ --exclude k8s/templates/data.json
gomplate version 3.4.0, build aae1a680 (2019-04-17T12:00:02Z)
config is:
input: k8s/templates/
exclude: k8s/templates/data.json
output: k8s/templates/
datasources: data=k8s/templates/data.json

rendered 0 template(s) with 1 error(s) in 368.414µs
template: k8s/templates/api-core.properties:1:33: executing "k8s/templates/api-core.properties" at <"data">: map has no entry for key "BASE_ENVIRONMENT"
```

As can be seen, the data.json includes BASE_ENVIRONMENT and api-core.properties correctly references it. Any idea how I can troubleshoot this?

**Comment by dwatrous** [comment]
This is somewhat related to #554 and the fact that I'm rendering over the template. What happens is that gomplate is trying to render data.json, which leaves it empty, which means the error is accurate. By the time it tries to render the template, data.json is empty.

I can work around this by rendering into a different folder (maybe best anyway...) or by referencing only the filename in `--exclude`

**Comment by hairyhenderson** [comment]
> What happens is that gomplate is trying to render data.json, which leaves it empty, which means the error is accurate. By the time it tries to render the template, data.json is empty.

Right - gomplate creates the output file before rendering it.

You _may_ be able to hack around this by using `-c` instead of `-d` - the `ds`/`datasource` function will only read the datasource when it gets to that point in the template, while if you use `--context`/`-c`, gomplate will read the datasource as one of the first things (I _think_ before creating the output file, and certainly before parsing the template).
