### ISSUE TITLE
default data source?

### ISSUE THREAD

**Issue by dwatrous** [hairyhenderson/gomplate#556]
I currently use Jinja2 to render some templates, but I want to move to gomplate. I got this working, but it requires that I change all my templates. For example.

{{ MYTOKEN }} needs to be changed to {{ (ds "data").MYTOKEN }}

This is a large effort because the templates are distributed across many repositories and branches. The rendering occurs during a build pipeline and the rendering is part of a shared library that will be consumed by all builds as soon as it is committed... In other words, as soon as I introduce gomplate, I will have broken builds.

I wonder if there is some way to define a default data source. This way when gomplate encounters {{ MYTOKEN }} it will try to find MYTOKEN in the default data source. 

I thought maybe this is how I would use `--context`, but what I tried didn't work and I can't find an actual example of using `--context`. All I can find is documentation describing it.

Is there some way to accomplish what I'm trying to do?

**Comment by hairyhenderson** [comment]
Hi @dwatrous! Thanks for logging this - I saw your tweet and meant to respond but I'm in the middle of about 18 different things 😂

Using `--context` IMO is the right way to approach this, but you'll still need to change syntax (i.e. from `{{ MYTOKEN }}` to `{{ .MYTOKEN }}`).

You're totally right about lacking docs - the section where an example _should_ be is https://docs.gomplate.ca/syntax/#the-context - but all it does is describe it 🤦‍♂. Sorry about that!

If you have, for example, a YAML file that contains some data like this:

_data.yaml:_
```yaml
MYTOKEN: foo
YOURTOKEN: bar
```

You could use `--context` (or `-c` for short) to reference the YAML file as a datasource:

```console
$ gomplate -c data=data.yaml -i 'my token is {{ .data.MYTOKEN }}'
my token is foo
```

(this is equivalent to `-c data.yaml`, where the filename without extension is used as the datasource alias - but that only works for files in the current working directory)

If you don't want to have the `.data` prefix, you can use that datasource as the _root_ context:

```console
$ gomplate -c .=data.yaml -i 'my token is {{ .MYTOKEN }}'
my token is foo
```

Hope that helps! Let me know if you need anything else. I see the other issues you've logged - will get to those soon.

**Comment by dwatrous** [comment]
I think I get it now. `-c` and `-d` are sort of interchangeable. So far I have been using `-d` the way you show using `-c` here.

Even with this change, I will still have to change the template files, so I may as well keep the more verbose form.

Thank you for the example and additional explanation

**Comment by hairyhenderson** [comment]
@dwatrous I mentioned it in #555 just now, but I'll repeat here for completeness - `-c` pre-loads the datasource, whereas `-d` does nothing on its own - a function like `ds` or `datasource` must be used to read the datasource.

There are tradeoffs to both approaches, but personally I've been using `--context` more often in the general case lately, since it's _way_ less typing 😉
