### ISSUE TITLE
S3 Datasource or Functions

### ISSUE THREAD

**Issue by Josh-West-Bose** [hairyhenderson/gomplate#566]
It would be great if `gomplate` could use S3 as a datasource, or had functions to read objects from S3, so that they could be used in templates!

**Comment by hairyhenderson** [comment]
Excellent idea! A datasource for `s3://` schemes would be quite useful IMO.

**Comment by hairyhenderson** [comment]
FYI I've got a work-in-progress PR up at https://github.com/hairyhenderson/gomplate/pull/625 - wouldn't mind some 👀 on the docs especially, with a preview available at https://deploy-preview-625--gomplate-docs.netlify.com/datasources/#using-s3-datasources
