### ISSUE TITLE
Template/Indent issue

### ISSUE THREAD

**Issue by andyrooster** [hairyhenderson/gomplate#570]
I'm using a template and passing a scope so that the template can make use of it, e.g:
`{{ template "my_template" . }}`

This works and the template can access `.Values.my_value` (I'm using .Values to be similar to how helm does it)

The template has multiple lines and I would like to render the template but pipe it to the indent function like so:
`{{ template "my_template" . | strings.Indent 2 }}`

However when I do this it breaks with the error:
`executing "my_template" at <.Values.my_value>: can't evaluate field Values in type string`

Is this expected behaviour or am I doing something wrong or not supported?

**Comment by hairyhenderson** [comment]
Hi @andyrooster! Thanks for logging this.

The `template` built-in doesn't work like a normal function, unfortunately. So in gomplate there's a `tmpl.Exec` function that you can use to work around this. See https://docs.gomplate.ca/functions/tmpl/#tmpl-exec for docs!

**Comment by andyrooster** [comment]
You know I read that page but clearly missed the critical detail that it returns the data as a string.

Thanks for the help
