### ISSUE TITLE
Question: Context overriding, similar to how helm Values work

### ISSUE THREAD

**Issue by andyrooster** [hairyhenderson/gomplate#571]
Hi @hairyhenderson 

I'm familiar with helm and the way that when you call `helm install` you can pass multiple `-f` arguments and it will override the values it brings in. The example from the manual is `helm install -f myvalues.yaml -f override.yaml ./redis`

I am trying to replicate some of helms functionality in gomplate to build docker-compose files. So the command I have been using is `gomplate -t templates/ -f docker-compose.yml --context Values=values.yml` which works just fine if I don't want to override any values.

What I'd like to do is something like `gomplate -t templates/ -f docker-compose.yml --context Values=values.yml  --context Values=dev-values.yml` and have .Values populated with the merged result of values.yml and dev-values.yml. When I try this the whole .Values object is overridden which is not what I am after.

Examples of the files might be:
values.yml:
```
config:
  url: http://example.com
  debug: false
```
dev-values.yml:
```
config:
  debug: true
```

Using the command above with multiple context arguments for the Values name, .Values ends up with just the config.debug element and its lost the url element from values.yml.

Is there a way to do this sort of thing in gomplate or should I be looking to merge the values YAML before I pass it to gomplate? If you have any alternative suggestions I'd love to hear them.

Thanks in advanced.

**Comment by hairyhenderson** [comment]
There's a way to do this, with `merge://` datasources! See the docs here: https://docs.gomplate.ca/datasources/#using-merge-datasources

**Comment by andyrooster** [comment]
Sorry I should of mentioned I did see that feature but it would mean all my `{{ .Values.my_value }}` would need to turn into` {{ (datasource "Values").my_value }}` which moves it further away to the helm syntax that myself and the other developers in the team are used to.

I guess its not a major problem using `(datasource "Values")`. Would this be available in templates too if I did `{{ template "my_service" . }}`?

**Comment by hairyhenderson** [comment]
Not at all, you can still use `--context` with that - the only difference between `--datasource` and `--context` is how the data's read - the data source is all ready at startup with `--context`, whereas with `--datasource` it's only read when the `datasource` function is called (which may be never when using conditionals).

So, something like this should work fine:

```console
gomplate -d 'Values=merge:overrides.yaml|defaults.yaml' -i '{{ .Values.my_value }}'
```

**Comment by andyrooster** [comment]
In your example I think you meant to use a `-c` but thanks for explaining that, I didn't realise the context argument supported the merge type.

Thanks for your patience answering my questions :)

**Comment by hairyhenderson** [comment]
Thanks @andyrooster - yes, I edited that in case someone reads this in the future...
