### ISSUE TITLE
Function plugins to execute external programs during template rendering

### ISSUE THREAD

**Issue by staffan-einarsson** [hairyhenderson/gomplate#580]
Hi. Is it possible to invoke an external program during template rendering? I feel like I'm missing something. In my template I iterate over a list of files and I want to use an external short script to assemble some metadata for each file entry, that would otherwise be awkward to implement in the template itself.

**Comment by hairyhenderson** [comment]
Hi @staffan-einarsson, thanks for logging this!

I think what you're asking for is some sort of `exec` function, where gomplate would execute a process inline?

If that's the case, unfortunately that's not possible, and I don't plan on implementing the ability to execute arbitrary programs, mostly due to the security issues that opens up.

Can you describe what exactly you're trying to accomplish? Perhaps it's not so awkward 😉

**Comment by staffan-einarsson** [comment]
Yes. That is exactly what I'm asking for. ;) I completely respect your decision to disallow this due to security concerns. I would not want to have a template invoke malicious code when I render it.

However, I would be perfectly if I could bind executables to symbolic function names from the gomplate command line, and only these bound functions would be usable from within templates. Then if a template tries to call one of these functions and it has not been bound at CLI level, you would get an error of undefined function. I'm thinking that it could be similar to how we now bind external data sources to symbolic names.

I'm using gomplate to render a file catalog document with a specific format, based on the contents in a directory. What I'm having problem with is MIME type "guessing" based on file name pattern, which is a tedious process, and I just want to fall back to a python script that uses the `mimetypes` module. Right now I need to have a preprocessing step that iterates over the files in the directory and prepares the content type and encoding information in a JSON file, that is used as a data source for gomplate. Gomplate is then used to render the file catalog document based on this JSON file. I would prefer if I could do this in one go, without having to have a pre-processing step.

**Comment by hairyhenderson** [comment]
> bind executables to symbolic function names from the gomplate command line, and only these bound functions would be usable from within templates.

This is a cool idea! This could be a way of doing function plugins - it's been vaguely discussed in the past (#343, #410, others), and I would totally be OK with doing this.

> What I'm having problem with is MIME type "guessing" based on file name pattern, which is a tedious process, and I just want to fall back to a python script that uses the `mimetypes` module.

I'm not sure I fully understand the issue - I guess you have a directory with datasource files having different formats, and gomplate doesn't understand the file extensions? Which extensions are they? If it's a matter of adding more file extension/MIME type mappings, that's fairly straightforward.

But I'm probably missing something 😉.

I'm going to re-name the issue to be in line with the external command/script as function plugin idea. I think it's a great idea, and will find some time to work on it at some point!

**Comment by hairyhenderson** [comment]
My initial thought on user interface would be something like:

```console
$ gomplate --plugin figlet=/usr/local/bin/figlet \
    -i '{{ figlet "hello" }}{{ "\n" }}{{ strings.ToUpper "world" | figlet }}"
 _          _ _       
| |__   ___| | | ___  
| '_ \ / _ \ | |/ _ \ 
| | | |  __/ | | (_) |
|_| |_|\___|_|_|\___/ 
                      
__        _____  ____  _     ____  
\ \      / / _ \|  _ \| |   |  _ \ 
 \ \ /\ / / | | | |_) | |   | | | |
  \ V  V /| |_| |  _ <| |___| |_| |
   \_/\_/  \___/|_| \_\_____|____/ 
```

Does this seem workable?

It may make sense at some point to support some kind of config file when covering many different mappings...

**Comment by hairyhenderson** [comment]
Note this is also related to #551, though that's more about compile-time extension rather than runtime extension 😉

**Comment by staffan-einarsson** [comment]
> ```
> $ gomplate --plugin figlet=/usr/local/bin/figlet \
>     -i '{{ figlet "hello" }}{{ "\n" }}{{ strings.ToUpper "world" | figlet }}"
> ```
Yes, that's pretty much how I imagined it too, and calling it plugins sounds good. Maybe it would be a good idea to use a namespace when you access them, like `plugin.figlet`, to minimise the risk of collision with existing symbols.

**Comment by hairyhenderson** [comment]
> Maybe it would be a good idea to use a namespace when you access them, like `plugin.figlet`, to minimise the risk of collision with existing symbols.

I considered that, but I don't think it's necessary TBH. Not requiring a prefix would also make it possible to adapt non-gomplate templates with minimal or no changes.
