### ISSUE TITLE
Allow to pass rendered template as stdin to post-template command

### ISSUE THREAD

**Issue by ProvoK** [hairyhenderson/gomplate#581]
As discussed in https://github.com/hairyhenderson/gomplate/issues/578 with @hairyhenderson , it might be useful a flag to permit passing the rendered template as stdin to the command executed when gomplate finishes succesfully its rendering.

Eg:
```
gomplate -f my_template.tpl -exec-pipe -- my_stdin_reading_application
```
Other possible flags names:
- stdin
- command-stdin
- pipe
- ...others?

This would be a great addition since the post-process command is executed only on gomplate success, and will avoid (sometimes) unnecessary writes to file.

:warning: This features may not be needed if gotemplate could generate output only when it's sure the template could be rendered (alias buffering the output till complete rendering). In that case, a simple shell pipe could do the work.

EDIT: changed `stdin` to `exec-pipe `

**Comment by charles-dyfis-net** [comment]
@ProvoK, ...so, is what you're looking for akin to the following?

```
maybe_pipe() {
  local -a cmd=( )
  local output
  while [[ $1 != -- ]]; do
    cmd+=( "$1" )
    shift
  done
  [[ $1 = -- ]] && shift
  output=$( "${cmd[@]}" ) && [[ $output ]] && "$@" <<<"$output"
}

maybe_pipe gomplate -f my-template.tpl -stdin -- my_stdin_reading_application
```

**Comment by hairyhenderson** [comment]
> Possible flags names:
> 
> * stdin
> * command-stdin
> * pipe
> * ...others?

How about `--exec-pipe`? As in "pipe the output to the post-run exec command"... 🤔

> In that case, a simple shell pipe could do the work.

TBH I think this feature is still useful - there are users who don't run gomplate in an environment where any shells are installed (such as in a `FROM scratch` Docker container).

**Comment by ProvoK** [comment]
> How about --exec-pipe? As in "pipe the output to the post-run exec command"... thinking

Seems fine to me :D

**Comment by ProvoK** [comment]
> @ProvoK, ...so, is what you're looking for akin to the following?
> 
> ```
> maybe_pipe() {
>   local -a cmd=( )
>   local output
>   while [[ $1 != -- ]]; do
>     cmd+=( "$1" )
>     shift
>   done
>   [[ $1 = -- ]] && shift
>   output=$( "${cmd[@]}" ) && [[ $output ]] && "$@" <<<"$output"
> }
> 
> maybe_pipe gomplate -f my-template.tpl -stdin -- my_stdin_reading_application
> ```

@charles-dyfis-net 
Seems a bit complicated but it's should be equivalent to
`$ rendered_template=$(gomplate -f template.tpl) && echo "$rendered_template" | my_binary
`
https://github.com/hairyhenderson/gomplate/issues/578#issuecomment-521145337

The point is: it's very useful that gomplate can call a command on success: less useful  (imho, for use cases such as the one in the comment above) that for consuming gomplate output you have to save it to a file (or use shell tricks).

**Comment by charles-dyfis-net** [comment]
I believe `ifne` from moreutils would do the same thing, but more efficiently than any of the above-proposed shell approaches (lauching `binary` after the first byte of stdin input is seen, rather than collecting all of `gomplate`'s output):

```
gomplate -f my-template.tpl -stdin | ifne my_binary
```

**Comment by hairyhenderson** [comment]
@charles-dyfis-net `ifne` doesn't really help, since it still outputs when the return code is non-zero
