### ISSUE TITLE
Add POSIX-shell-compatible quote function

### ISSUE THREAD

**Issue by charles-dyfis-net** [hairyhenderson/gomplate#584]
At the cost of adding new dependencies, this could be `shellquote.Join()` from https://github.com/kballard/go-shellquote, or `shellescape.Quote()` from https://github.com/alessio/shellescape; both are MIT-licensed.

**Comment by hairyhenderson** [comment]
Thanks @charles-dyfis-net - this sounds like a good idea! I'm thinking `strings.ShellQuote` may be the right function name.

I like the implementation in github.com/alessio/shellescape far better - the other one seems a bit convoluted! I think you offered to issue a PR for this, it would be most welcome! If you want to simply copy/paste to avoid the extra dependency, that'd be fine too. Either way is good!

**Comment by hairyhenderson** [comment]
Closed in #587
