### ISSUE TITLE
Tag <major> and "stable" versions of docker images

### ISSUE THREAD

**Issue by docwhat** [hairyhenderson/gomplate#648]
Currently, the tags in `docker.io` are:

- `latest` and derivatives: `slim`, `alpine`, and `artifacts`
- `vM.m.p` and derivatives. Where `M` is major, `m` is minor, and `p` is patch à la [semver](https://semver.org).

I would propose adding one or both of:

- `stable` and derivatives. e.g. `stable-slim`
- `vM` and derivatives. e.g. `v3`, `v3-alpine`

The `vM` is the most valuable as it lets people using `gomplate` in (for example CI) to prevent breakages due to new-breaking features (major release as per [semver](https://semver.org)).

**Comment by hairyhenderson** [comment]
@docwhat Thanks for logging this! It's been on my mind for a while, and I definitely want to do this.

And I agree and thing both `stable` and `stable-*`, and `vM` and `vM-*` are useful.

I'll get working on this soon 😉

**Comment by docwhat** [comment]
WOOT!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
