### ISSUE TITLE
Add regexp.QuoteMeta

### ISSUE THREAD

**Issue by f0rmiga** [hairyhenderson/gomplate#751]
Feature request:

The `regexp.QuoteMeta` is useful for sanitizing strings that should be treated as literal on property fields that only accept a regexp.

Ref: https://golang.org/pkg/regexp/#QuoteMeta.

**Comment by hairyhenderson** [comment]
Hi @f0rmiga - sorry for the slow response!

I agree! If you'd like to implement this, a PR would be great, otherwise I'll get to it soon 🙂

**Comment by f0rmiga** [comment]
Hi @hairyhenderson. Thanks for giving your feedback on it. I can try finding some time in the next 2 weeks. If I do, I'll post here so you can assign this issue to me. :)
