### ISSUE TITLE
Only write to -o if the rendered result differs from the destination

### ISSUE THREAD

**Issue by dawidpogorzelski** [hairyhenderson/gomplate#752]
It would be nice to be able to write the rendered template to the output only if the file at the destination differs from the rendered template, for example:
`gomplate -f /tmp/templates/nginx.conf -o /etc/nginx/nginx.conf` but only write to -o if the file at -o is different than the output from gomplate -f.
It would be possible then to pair gomplate with systemd path units to restart a service when a configuration file of that service is updated. In the current situation that is not possible since -o is updated at every run and therefore the service is restarted even if there were no changes.

More details and full discussion reference https://gophers.slack.com/archives/CGTR16RM2/p1580729071008500

**Comment by hairyhenderson** [comment]
@dawidpogorzelski FYI I'm (finally!) working on this in #840 - this'll be in the next release.

I've decided that it makes sense for this to be the normal behaviour, and not to put this behind a flag or environment variable. So this should "just work" once you upgrade 😉
