### ISSUE TITLE
Support for accessing terraform output values

### ISSUE THREAD

**Issue by jbialy** [hairyhenderson/gomplate#774]
It would be really useful if gomplate could have native support for accessing terraform [output values](https://www.terraform.io/docs/configuration/outputs.html). Using the terraform CLI this can easily be done using `terraform output -json some_output_value`. Having the ability to access terraform state using a data source would be pretty useful when performing various templating tasks!

**Comment by hairyhenderson** [comment]
Is there still any interest in this? Given #1336 this would need to be added to https://github.com/hairyhenderson/go-fsimpl if so.
