### ISSUE TITLE
Support for GCP secret manager

### ISSUE THREAD

**Issue by jbialy** [hairyhenderson/gomplate#788]
Gomplate supports reading from the AWS parameter store using the`aws+smp` datasource. It would be great to also support the GCP secret manager, https://cloud.google.com/secret-manager/docs/managing-secrets.

**Comment by dontlaugh** [comment]
I had to implement a version of this that only fetches the _latest_ version of a secret. I don't have time to pick this up, but I'll leave this here in case it helps anyone.

```go
package secret

import (
	"context"
	"fmt"

	secretmanager "cloud.google.com/go/secretmanager/apiv1"
	secretmanagerpb "google.golang.org/genproto/googleapis/cloud/secretmanager/v1"
)

// Get ...
func Get(ctx context.Context, projectID, secretName string) ([]byte, error) {

	// Create the client.
	client, err := secretmanager.NewClient(ctx)
	if err != nil {
		return nil, err
	}

	vreq := secretmanagerpb.GetSecretVersionRequest{
		Name: fmt.Sprintf("projects/%s/secrets/%s/versions/latest", projectID, secretName),
	}
	v, err := client.GetSecretVersion(ctx, &vreq)
	if err != nil {
		return nil, err
	}

	req := secretmanagerpb.AccessSecretVersionRequest{
		Name: v.Name,
	}

	s, err := client.AccessSecretVersion(ctx, &req)
	if err != nil {
		return nil, err
	}

	return s.Payload.Data, nil
}

```

I think you have to get version metadata first. `versions/latest` is an alias to the latest version. With that fully-qualified name you can use `AccessSecretVersion` get the secret's contents as bytes.

**Comment by hairyhenderson** [comment]
Thanks @dontlaugh, that looks super helpful! 😁

**Comment by vtatarin** [comment]
@dontlaugh thank you for the snippet!
Waiting for Secret Manager to be added in the upcoming releases:)

**Comment by sthomson-wyn** [comment]
I'm going to take a crack at adding this, if that's OK

**Comment by hairyhenderson** [comment]
I've filed https://github.com/hairyhenderson/go-fsimpl/issues/364, and when that's implemented (contributions accepted!) support will be available in gomplate. As no further action is necessary in gomplate, I'll close this issue.
