### ISSUE TITLE
gomplate w/vault error: user: Current not implemented on linux/amd64 

### ISSUE THREAD

**Issue by drmdrew** [hairyhenderson/gomplate#79]
Example failure using gomplate inside a linux docker container:
```bash
nobody@5f067e23aa9a:/srv$ gomplate -v
gomplate version 1.2.1
nobody@5f067e23aa9a:/srv$ echo -n "{{(datasource \"vault\" \"secret\")}}" | gomplate -d vault="vault://"
2016/11/19 22:58:14 user: Current not implemented on linux/amd64
```

This looks to be due to `os/user` having a dependency on libc which is broken if `CGO_ENABLED=0` when gomplate was built (see golang/go#11797)

```
vault/token_strategy.go:54:     u, err := user.Current()
vault/token_strategy_test.go:26:        u, err := user.Current()
```

**Comment by drmdrew** [comment]
Since cross-compiling several platforms with `CGO_ENABLED` is the very definition of _non-trivial_ ... one approach would be to look for `HOME` (Mac+Linux) and `USERPROFILE` (Windows) environment variables and use those to locate `~/.vault-token` for each supported platform.

**Comment by hairyhenderson** [comment]
Aw man, I'm so fired. I totally ran across this a week or 2 ago, too... 😞
