### ISSUE TITLE
Bug with aws+smp, region not being read from AWS Shared credentials file

### ISSUE THREAD

**Issue by qlikcoe** [hairyhenderson/gomplate#795]
So having this: 

```
aws configure set aws_access_key_id $aws_access_key_id --profile $account
aws configure set aws_secret_access_key $aws_secret_access_key --profile $account
aws configure set region $region --profile $account
AWS_PROFILE=$account gomplate -c sumo_endpoint=aws+smp:///sumo/http-endpoint
```

leads to this error: 
```
Gomplating and applying remaining manifests...
Couldn't read datasource 'sumo_endpoint': Error reading aws+smp from AWS using GetParameter with input {
  Name: "/de-stage/sumo/http-endpoint",
  WithDecryption: true
}: RequestError: send request failed
caused by: Post https://ssm.unknown.amazonaws.com/: dial tcp: lookup ssm.unknown.amazonaws.com on 100.100.192.0:53: no such host
```

Adding `export AWS_REGION=$region` solves the problem.

**Comment by hairyhenderson** [comment]
@qlikcoe which version of `gomplate` are you using? This should've been fixed in #465, but that may not have covered reading the AWS config file 🤔

**Comment by qlikcoe** [comment]
I think it's using 3.5.0-slim

**Comment by hairyhenderson** [comment]
@qlikcoe ok, then we have a bug! Note that v3.6.0 is latest, but 3.5.0 has that fix.

**Comment by hairyhenderson** [comment]
The issue seems to be that gomplate only considers (for this particular datasource) the environment variables and the EC2 metadata. So if you're not running in EC2, or if the EC2 Instance Metadata Service isn't reachable, region won't be discovered.

For now though, using `AWS_REGION` is a good workaround.
