### ISSUE TITLE
It'd be nice to also resolve templates from files

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/gomplate#8]
Let's start with JSON support (because `encoding/json`). I figure usage like this would be useful:

_data.json_
```json
{
  "name": {
    "first": "Joe"
  }
}
```

_in.txt_
```
Hello {{.data.name.first}}!
```
_(where `data` comes from the name of the file)_

```console
$ gomplate -f data.json < in.txt
Hello Joe!
```

**Comment by drewmacinnis** [comment]
Yeah, a `-f` would be handy.

**Comment by hairyhenderson** [comment]
Something that might be a bit simpler to implement, and would probably flow better with the rest of the built-in functions is:

```go
Hello {{ (jsonfile "data.json").name.first }}
```

```console
$ gomplate -d data.json < in.txt
Hello Joe!
```

**Comment by hairyhenderson** [comment]
...although if I'm taking a path or filename as the argument to `jsonfile`, then I don't need to pass it on the commandline...

_Conversely,_ forcing a file to be named a specific way may not be a good plan either. Maybe something like:

```go
Hello {{ (jsonfile "data").name.first }}
```

```console
$ gomplate -d data.json < in.txt
Hello Joe!
```

Where `"data"` is resolved because the file is named `data.json`. I could support mappings with `=` like:

```console
$ gomplate -d data=myotherfilename.json < in.txt
Hello Joe!
```

It'd be interesting to _also_ support other data sources from URLs, so to treat the `-d` argument like: `alias=URL`, or:

```console
$ gomplate -d data=https://some.url/where/i/can/find/data.json < in.txt
Hello Joe!
```

This implies a few things:
1. `jsonfile` is a bad name - it should be something more generic like `datasource`
2. in the absence of `=`, the argument is assumed to be a file in the cwd, and the alias is set to the file name (sans extension)
3. paths (i.e. anything with a directory name in it, not just the filename) and URLs would _require_ the alias

**Comment by drmdrew** [comment]
I like the "data source alias" idea. Perhaps always use uri style? Like file:// https://?

**Comment by hairyhenderson** [comment]
yeah - well `data.json` is _technically_ a valid relative URL, so if we always use the cwd as the base file:// url, there shouldn't be any special-casing needed.

I was also thinking I could support lots of different formats this way (eventually!) like yaml or toml or even XML, detecting by Content-Type with a fallback to file extension...
