### ISSUE TITLE
type query not parsed by defineDataSource

### ISSUE THREAD

**Issue by glensc** [hairyhenderson/gomplate#809]
Brief: Load a [.env] file and export it as yaml:

[.env]: https://docs.gomplate.ca/datasources/#the-env-file-format

```yaml
{{- defineDatasource "env_file" ".env" -}}

config:
  {{ (ds "env_file") | data.ToYAML | strings.Indent 1 "  " | trimSpace }}
```

however, my local file is named `.env.foo`, there seems no way to specify [mime-type]:

[mime-type]: https://docs.gomplate.ca/datasources/#overriding-mime-types

```
{{- defineDatasource "env_file" ".env.staging?type=application/x-env" -}}
```

I tried also the absolute path and `file://` prefix as well.

```
config:
  template: values.yml:4:6: executing "values.yml" at <ds "env_file">: error calling ds: Couldn't read datasource 'env_file': Can't stat /tmp/env-import/.env.staging?type=application/x-env: stat /tmp/env-import/.env.staging?type=application/x-env: no such file or directory
```

**Comment by hairyhenderson** [comment]
🤔 Ok, this looks like a bug! I'd expect that adding `?type=application/x-env` would've worked...

BTW, is there a reason you're defining the datasource in the template, and not on the commandline? Just curious about use-cases 😉

**Comment by glensc** [comment]
Usecase is that I'm pre-processing helm `values.yml` file.

Defining data source in a file is better isolated than having to define data sources externally in another language (shell script embedded in gitlab-ci yaml). Especially if not all environments have the same data sources. We have a set of config files, one for each deployed environment.

My helm chart expects top-level `config` and `secrets` key to define config maps. So `gomplate` kicks in to add keys to these elements.


```yml
{{ defineDatasource "env_file" "kubernetes/.env" -}}
{{ defineDatasource "secrets_env_file" "kubernetes/.ci.env" -}}

.env.file: &env_file
  {{ (ds "env_file") | data.ToYAML | strings.Indent 1 "  " | trimSpace }}

.env.secrets: &env_secrets
  {{ (ds "secrets_env_file") | data.ToYAML | strings.Indent 1 "  " | trimSpace }}

config:
  <<: *env_file
  TZ: Europe/Tallinn

secret:
  <<: *env_secrets
  DB_PASSWORD: "${DB_PASSWORD}"
```

This might not be the optimal solution but works for us now pretty nicely.

**Comment by hairyhenderson** [comment]
@glensc Ok, sounds great! Glad it's working for you (other than this bug 😂)

**Comment by glensc** [comment]
In fact, I would see third argument cleaner solution to this bug than hacking filename.

**Comment by hairyhenderson** [comment]
@glensc a 3rd argument would be a totally new thing, but not out of the question. The filename "hack" should already work though, since it should be parsed as a URL.
