### ISSUE TITLE
docker image: binary is not in PATH anymore

### ISSUE THREAD

**Issue by vbehar** [hairyhenderson/gomplate#814]
Hi,

since https://github.com/hairyhenderson/gomplate/pull/811 the `gomplate` binary in not in `$PATH` anymore - at least in the `alpine` image tag:
- it used to be located at `/bin/gomplate`
- it is now at `/gomplate`

Is there a reason it's not in `$PATH` anymore? Would you consider putting it back?

Thanks

**Comment by hairyhenderson** [comment]
Sorry @vbehar - that was a mistake! I fixed it in #816 😅 

You may want to also consider using the `hairyhenderson/gomplate:v3.6.0-alpine` image instead - the `:alpine` tag (along with `:latest` and `:slim`) is based on `master`, so may be less stable.

**Comment by vbehar** [comment]
thanks! yes we already used the right tag everywhere, except for 1 daily job.
