### ISSUE TITLE
How to "include" templates within other templates

### ISSUE THREAD

**Issue by McShauno** [hairyhenderson/gomplate#815]
First, thank you for this great tool.  I use it almost everyday.  It is deeply embedded in many of my build pipelines.

One thing I really like about helm is the ability to use the `include` syntax to have one template reference another template.  For example:
```
{{- define "my-service.fqdn" -}}
{{- printf "%s.%s" .CurrentNamespace .Host.Domain -}}
{{- end -}}

{{- define "my-service.uri-scheme" -}}
{{- default "http" .ExternalUriScheme -}}
{{- end -}}

{{- define "my-service.external-url" -}}
{{- printf "%s://%s" (include "my-service.uri-scheme" .) (include "my-service.fqdn" .) -}}
{{- end -}}
```
However, this doesn't seem to be supported within gomplate.  I don't necessarily get a syntax error but I do see this error when trying to use `my-service.external-url`:

```
executing "my-service.external-url" at <.>: wrong type for value; expected string; got map[string]interface {}
```
Perhaps there is another/better way to do this but I have yet to discover it.  

Thank you!

**Comment by hairyhenderson** [comment]
Hi @McShauno - thanks for the kind words, I'm glad gomplate is useful for you! 😁

You can do this already with gomplate, but not with `include` ([`include`](https://docs.gomplate.ca/functions/data/#include) is a different function!).

Have a look at the [`tmpl`](https://docs.gomplate.ca/functions/tmpl/) functions, I think `tmpl.Exec` will do what you're looking for!

If you're interested, a much more convoluted usage of `tmpl.Exec` is described here: https://blog.hairyhenderson.ca/post/one_template_many_outputs/ 😉

Oh, I should also mention that you don't even always need `tmpl.Exec`, as the Go templating language has a [`template` action](https://golang.org/pkg/text/template/#hdr-Actions) that works the same. The only difference is it only prints the rendered output, it doesn't return it for further processing.

**Comment by hairyhenderson** [comment]
@McShauno I think that answers your question, so I'll close the issue now, but if I've totally misunderstood you, feel free to re-open it! 😂

**Comment by McShauno** [comment]
@hairyhenderson You nailed it!  Thank you so much!
