### ISSUE TITLE
Provide non-compressed docker image

### ISSUE THREAD

**Issue by glensc** [hairyhenderson/gomplate#820]
I run gomplate in CI, I don't care for image size there (images are usually cached), but having gomplate compressed delays each run of it 1+ seconds.

Please provide an image without pax.

```
➔ docker pull hairyhenderson/gomplate:v3.6.0-slim 
➔ time docker run --rm hairyhenderson/gomplate:v3.6.0-slim --version
gomplate version 3.6.0

real	0m1.170s
user	0m0.046s
sys	0m0.021s
```

**Comment by hairyhenderson** [comment]
@glensc what do you mean by `pax`?

There are 3 image flavours that I ship to DockerHub (see https://hub.docker.com/r/hairyhenderson/gomplate/tags?page=1&name=v3.6.0):

- `v3.6.0`: just the binary, in `/gomplate`
- `v3.6.0-slim`: just the binary, compressed with UPX, in `/gomplate`
- `v3.6.0-alpine`: the "slim" binary, on an Alpine Linux base, on the `$PATH` in `/bin/gomplate`

**Comment by glensc** [comment]
sorry, mistyped UPX for pax

**Comment by glensc** [comment]
@hairyhenderson looking at the dockerfile, I see all variants are compressed:
- https://github.com/hairyhenderson/gomplate/blob/v3.6.0/Dockerfile

I'm looking for a non-compressed variant

**Comment by glensc** [comment]
Looks like alpine itself contains non-compressed variant. perhaps I'll use that, currently, it's fresh enough, but I suspect it will lag behind when you make a new version.

```
➔ docker run --rm -it alpine:3.11 sh
Unable to find image 'alpine:3.11' locally
3.11: Pulling from library/alpine
Digest: sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54
Status: Downloaded newer image for alpine:3.11
/ # apk add gomplate
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ca-certificates (20191127-r1)
(2/2) Installing gomplate (3.6.0-r0)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 53 MiB in 16 packages
/ # time gomplate --version
gomplate version 3.6.0
real	0m 0.04s
user	0m 0.01s
sys	0m 0.02s
/ #
```

compared to compressed:

```
➔ docker run --rm -it --entrypoint='' hairyhenderson/gomplate:v3.6.0-alpine sh
/ # time gomplate --version
gomplate version 3.6.0
real	0m 0.73s
user	0m 0.69s
sys	0m 0.03s
/ #
```

**Comment by hairyhenderson** [comment]
Oh, strange!

The regular (`:v3.6.0`) variant shouldn't be compressed - the Dockerfile copies the non-`slim` binary: https://github.com/hairyhenderson/gomplate/blob/v3.6.0/Dockerfile#L36

And in fact, if I copy the binaries, the one from `:v3.6.0` is clearly not compressed:

```console
$ docker create --name normal hairyhenderson/gomplate:v3.6.0
7d10bc30efdea202a02299883d2467c9cd6ba2d04cced4f1d8a167f33faaf13e
$ docker create --name slim hairyhenderson/gomplate:v3.6.0-slim
aeec9c794dcd0bf985874e94f4ebebf492a21b8b7ec86f8db7166cb52e2be9ff
$ docker create --name alpine hairyhenderson/gomplate:v3.6.0-alpine
e96eb85560ce2fe7b7f3fdfdb07171043af3b54e3a102032337e644ef36d58e8
$ docker cp normal:/gomplate ./gomplate-normal
$ docker cp slim:/gomplate ./gomplate-slim
$ docker cp alpine:/bin/gomplate ./gomplate-alpine
$ ls -alh gomplate-*
-rwxr-xr-x 1 hairyhenderson 7.5M Nov 15 22:10 gomplate-alpine
-rwxr-xr-x 1 hairyhenderson  34M Nov 15 22:10 gomplate-normal
-rwxr-xr-x 1 hairyhenderson 7.5M Nov 15 22:10 gomplate-slim
```

And here's the timings:

```console
$ time docker run hairyhenderson/gomplate:v3.6.0 --version
gomplate version 3.6.0
docker run hairyhenderson/gomplate:v3.6.0 --version  0.06s user 0.02s system 15% cpu 0.493 total
$ time docker run hairyhenderson/gomplate:v3.6.0-slim --version
gomplate version 3.6.0
docker run hairyhenderson/gomplate:v3.6.0-slim --version  0.05s user 0.02s system 7% cpu 1.004 total
$ time docker run hairyhenderson/gomplate:v3.6.0-alpine --version
gomplate version 3.6.0
docker run hairyhenderson/gomplate:v3.6.0-alpine --version  0.05s user 0.02s system 7% cpu 1.001 total
```

So I see that the `:v3.6.0` variant is 2x faster than the compressed ones.

Can you try out the `:v3.6.0` image and post logs of that one? And, just to be sure, make sure to `docker pull` the images first, just to make certain that they're the correct ones!

**Comment by glensc** [comment]
I can confirm the base (`hairyhenderson/gomplate:v3.6.0) is not-compressed:

```
/ # time gomplate --version
gomplate version 3.6.0
real	0m 0.01s
user	0m 0.00s
sys	0m 0.00s
/ #
```
