### ISSUE TITLE
Control flow 

### ISSUE THREAD

**Issue by ysaakpr** [hairyhenderson/gomplate#824]
How to do conditional control flow using this library. Could not find any docs on it. Is it possible?

```
{{ if true }}
True case
{{ else }}
false
{{end }}
```

Is there anything like this can be done in gomplate ?

**Comment by hairyhenderson** [comment]
Hi @ysaakpr! Yes, control flow is possible using `if`/`else`/`end` as you presumed. Those actions are part of the Go `text/template` language, and are documented here: https://golang.org/pkg/text/template/#hdr-Actions

There are also some references to built-in functions and comparison operators (`and` and `or` are particularly relevant to conditionals): https://docs.gomplate.ca/syntax/#functions

I'm realizing that while I've provided links to the docs for the built-ins and operators, I haven't provided a similar list for the _actions_ (though they are referenced throughout the [syntax](https://docs.gomplate.ca/syntax/) docs).
