### ISSUE TITLE
Is there any way to exclude piece of template from processing?

### ISSUE THREAD

**Issue by vsapronov** [hairyhenderson/gomplate#857]
I have a script that is template but also it remains runnable script itself - following all conventions of the scripting language (yaml+bash - don't ask me why). Let's say the script is named `script.yml`

Here's the line that I execute in that script:
```gomplate --file script.yml --context .=data.json --left-delim {{{ --right-delim }}} > processed_script.yml```
This line needs to be in the `script.yaml` - so it's using the `script.yaml` itself as a template. When this line is running it's trying to process itself and basically complains on this part `{{{ --right-delim }}}`

I'm thinking: if I would have some instruction to ignore piece of template during processing I could avoid this issue...

**Comment by hairyhenderson** [comment]
@vsapronov Hi, thanks for logging this!

That's an unusual use-case to be sure, and if this must be entirely self-contained you can hack around it by using `tr` to mask the strings:

_script.yml_:
```bash
#!/bin/bash

gomplate --file script.yml --context .=data.json --left-delim $(echo '<<<' | tr '<' '{') --right-delim $(echo '>>>' | tr '>' '}') > processed_script.yml
exit

foo: {{{ print "hello world" }}}
```

```console
$ bash script.yml
$ cat processed_script.yml
#!/bin/bash

gomplate --file script.yml --context .=data.json --left-delim $(echo '<<<' | tr '<' '{') --right-delim $(echo '>>>' | tr '>' '}') > processed_script.yml
exit

foo: hello world
```

Does that make sense? It's a bit of an ugly hack though to be honest...

Did you know that gomplate has support for config files now (as of version 3.7.0)? It may be cleaner to use a configuration instead:

_config.yml_:
```yaml
leftDelim: '{{{'
rightDelim: '}}}'

inputFiles:
  - script.yml

outputFiles:
  - processed_script.yml

context:
  .:
    url: ./data.json
```

_script.yml_:
```bash
#!/bin/bash

gomplate --config=config.yml
exit

foo: {{{ print "hello world" }}}
```

```console
$ bash script.yml
$ cat processed_script.yml
#!/bin/bash

gomplate --config=config.yml
exit

foo: hello world
```

This is a bit cleaner, and doesn't require hacking around delimiters!

See https://docs.gomplate.ca/config for docs on the new config format.

Finally, I'm not at all sure what your use-case is, so this may not work, but gomplate can [execute a post-template command](https://docs.gomplate.ca/usage/#post-template-command-execution), so you may be able to avoid calling gomplate from the file completely:

_script.yml_:
```yaml
foo: {{{ print "hello world" }}}
```

_config.yml_:
```yaml
leftDelim: '{{{'
rightDelim: '}}}'

inputFiles:
  - script.yml

postExec: [tr, '[a-z]', '[A-Z]']

execPipe: true

context:
  .:
    url: ./data.json
```

```console
$ gomplate --config=config.yml
FOO: HELLO WORLD
```

Or, without a config file:

```console
$ gomplate --left-delim '{{{' --right-delim '}}}' -c .=./data.json -f script.yml --exec-pipe -- tr '[a-z]' '[A-Z]'
FOO: HELLO WORLD
```

Hope that helps!

I think this has probably answered your question, so I'm going to close this for now, but feel free to re-open it if you feel there's some functionality missing!

**Comment by vsapronov** [comment]
Yeah, I went with symbols replacing option and it worked. So my problem is solved.
I just thought something like `{% raw %}` in Jinja would be useful.
Thank you.

**Comment by hairyhenderson** [comment]
@vsapronov right, I understand. Unfortunately there's no equivalent with the Go `text/template` language.

One other option, actually, now that I think of it, would be to use a multi-line comment.

Something like this would work:

_script.yml_:
```bash
# {{{/*
gomplate --file script.yml --left-delim '{{{' --right-delim '}}}' > processed_script.yml
exit
# */}}}
foo: {{{ print "hello world" }}}
```

```console
$ bash script.yml
$ cat processed_script.yml 
# 
foo: hello world
```

**Comment by vsapronov** [comment]
@hairyhenderson thank you, with comments it looks better
