### ISSUE TITLE
Intermittent failure using -slim binaries, exit code 127

### ISSUE THREAD

**Issue by bhartshorn** [hairyhenderson/gomplate#861]
Hi, I've recently encountered a problem using the -slim versions of the gomplate release binaries. When running hundreds of times in succession, eventually gomplate will fail and return an exit code `127`. I suspect this is due to an issue with the upx compression used for the -slim binary.

## Tested versions:
I'm going to try to test some other combinations and will report back

All of these combinations failed when run in rapid succession using the script shared below:
- (v3.6.0) gomplate_linux-amd64-slim on Ubuntu Xenial 16.04 (Docker) and RHEL 7.7 (Metal)
- (v3.7.0) gomplate_linux-amd64-slim on RHEL 7.7 (Metal)

These combinations completed 100,000 iterations without failure:
- (v3.6.0) gomplate_linux-amd64 on RHEL 7.7 (Metal)

## Steps to reproduce

I've managed to reproduce the issue in a docker container, hopefully you can reproduce it this way also.
1. Files:
```
.
├── Dockerfile
├── gomplate_linux-amd64      (v3.6.0)
├── gomplate_linux-amd64-slim (v3.6.0)
└── test.sh
```

2. Dockerfile:
```
FROM ubuntu:xenial
COPY test.sh .
COPY gomplate* /usr/bin/
```

3. test.sh:
```
#!/usr/bin/env bash
set -e
#set -x

if [[ $# -eq 1 ]]; then
  bin="gomplate_linux-amd64-$1"
else
  bin="gomplate_linux-amd64"
fi

echo "Running ${bin}"

for ((ITER = 1; ITER <= 100000; ITER++)); do
  export ITER=${ITER}
  [ $(($ITER % 100)) != "0" ] && echo -n "." || echo " Running ${ITER}"
  avar=avar bvar=bvar ${bin} '--in={ "avar": {{ .Env.avar | toJSON }}, "bvar": {{ .Env.bvar | toJSON }} }' --out=output.yaml >gomplate.log 2>&1 || {
    echo -e "\nexit code: $?"
    echo "Ended on iteration ${ITER}"
    break
  }
  rm -f gomplate.log output.yaml
done
```

4. Docker build:
`> docker build . -t gomplate-upx-issue:latest`

5. Run in Docker:
```
> docker run -it --entrypoint /bin/bash gomplate-upx-issue
root@496699bf7dda:/# ./test.sh slim
Running  /usr/bin/gomplate_linux-amd64-slim
................................................................................................... Running 100
................................................................................................... Running 200
................................................................................................... Running 300
................................................................................................... Running 400
................................................................................................... Running 500
................................................................................................... Running 600
..............................................................................................
exit code: 127
Ended on iteration 694
```

Non-slim binary is included if you want to test it also, just run test.sh with no params.

**Comment by bhartshorn** [comment]
Reproduced on:
- (v3.6.0) gomplate_linux-amd64-slim on Ubuntu Bionic 18.04 (Docker)

**Comment by hairyhenderson** [comment]
@bhartshorn thanks for this report - this is very thorough! The big difference is indeed with UPX. In v3.6.0 I used UPX v3.94 to compress the binary, while in v3.7.0 I upgraded to v3.96, which included a fix for https://github.com/upx/upx/issues/222 (which I was experiencing with v3.95).

Out of curiosity, is there a reason you built your own Docker images instead of basing off the [`hairyhenderson/gomplate`](http://hub.docker.com/r/hairyhenderson/gomplate/) images?

For now, is using the non-slim binary an option for you? Note that it's actually faster, since UPX decompression adds some overhead. The tradeoff is of course in size.

**Comment by hairyhenderson** [comment]
@bhartshorn just to clarify, the v3.7.0 non-slim binary is working, correct?

**Comment by bhartshorn** [comment]
> Out of curiosity, is there a reason you built your own Docker images instead of basing off the hairyhenderson/gomplate images?

The docker image built above was just for reproducing the bug. I attempted to use your docker image, but it doesn't include a shell. This UPX bug doesn't manifest when the binary is run in a fresh container each time so it seems to be related to running in rapid succession (haven't tested with a delay between runs though) on the same host.

> just to clarify, the v3.7.0 non-slim binary is working, correct?
I tested 3.7.0 to almost 7000 runs without a failure. I can test further if you want to know.

> For now, is using the non-slim binary an option for you?
That's the plan. I switched this project over to the non-slim, and won't need to use slim for now.

Thanks for taking a look!

**Comment by hairyhenderson** [comment]
Ok, thanks @bhartshorn. One thing you can try is to compress the non-slim binary with UPX 3.94 and see if that makes a difference. I have a UPX 3.94 Docker image at `hairyhenderson/upx:3.94` (source: https://github.com/hairyhenderson/dockerfiles/blob/3.94/upx/Dockerfile) that you could use.

Also I _believe_ I compressed the GitHub Release binaries on macOS, not Linux, and there have been some bugs with binaries compressed on macOS (even if they're non-macOS binaries). The binaries inside the containers are compressed on Linux.

So one thing to also try is to use the binary from `hairyhenderson/gomplate:v3.7.0-slim` to see if it works better over time:

```Dockerfile
FROM ubuntu:xenial
COPY test.sh .
COPY --from=hairyhenderson/gomplate:v3.7.0-slim /usr/bin/gomplate-slim
```

**Comment by hairyhenderson** [comment]
Just as a bit of an update, I think I've experienced this error with the binary in the `hairyhenderson/gomplate:v3.7.0-slim` Docker image as well.

I'll use upx 3.94 to compress binaries instead in the next release.
