### ISSUE TITLE
Add Kubernetes data source

### ISSUE THREAD

**Issue by glensc** [hairyhenderson/gomplate#883]
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

> The lookup function can be used to look up resources in a running cluster. The synopsis of the lookup function is §lookup apiVersion, kind, namespace, name§ -> resource or resource list.

**Comment by glensc** [comment]
While I don't need this right now (as even haven't tested how it works in helm itself), but this may be useful to some scenarios.

**Comment by hairyhenderson** [comment]
@glensc Interesting idea! One use-case of gomplate that I've seen in the wild is as a replacement for `helm template`, so this may well be appropriate.

One use-case that I can think of that would help me in particular is a spot where I've had to run a `kubectl` command (to list the namespaces in the cluster, if I recall correctly), and output the JSON into a file which is then picked up by gomplate as a datasource. This would definitely be simpler if I could just do `gomplate -d k8s:///api/v1/namespaces` or something like that...

In the meantime, it may already be possible to accomplish this with an `http://` datasource: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#directly-accessing-the-rest-api
