### ISSUE TITLE
Is it possible to use template in double quoted string?

### ISSUE THREAD

**Issue by boskiv** [hairyhenderson/gomplate#886]
I know that single quote works but what if I want to use double quotes in my result file?
I'm trying to use in nginx.conf
```
add_header Cache-Control "max-age={{ (ds \"app\").cache_max_age }}"
```

But it failure with:
```
00:55:46 FTL  error="template: /app/templates/vhost.template:29: unexpected \"\\\\\" in operand"
```

```
➜ APP='{"cache_max_age":30}' gomplate -d "app=env:/APP?type=application/json" -f vhost.template
```

**Comment by boskiv** [comment]
this works
```
add_header Cache-Control "max-age={{ (ds "app").cache_max_age }}"
```

**Comment by hairyhenderson** [comment]
@boskiv The key thing to remember is that gomplate sees the file as a template when it processes it, and doesn't care about any text except the text inside the template delimiters (`{{`/`}}`).

So unless you have nested quotes inside a string passed as an argument to a template function, gomplate won't care.

Perhaps worth also mentioning - you can use the <code>`</code> character as a (raw) string delimiter as well. So if you need to avoid escaping double-quotes, you can do something like:

```
{{ print `hello "world"` }}
```
