### ISSUE TITLE
`go get` style installation doesn't result in a `gomplate` executable

### ISSUE THREAD

**Issue by mcarifio** [hairyhenderson/gomplate#894]
The `go get` style installation seems to have completed, but no `gomplate` was created in `$GOPATH/bin` as I would have expected (but might be wrong, my go fu is weak). Aside: I installed 3.7.0 by manually downloading the release and making it an executable.

Note that I was able to install [grpc](https://pkg.go.dev/google.golang.org/grpc) with `go get google.golang.org/grpc`. I did that to test my environment and it seems to have installed correctly.

Note that if I'm misinformed about how `go get` works, then perhaps a few more sentences in the README.md could indicated what to expect.

Here's the "transcript":

```bash
$ go version # what go's installed?
go version go1.12.17 linux/amd64
$ go env  # note GOROOT. This go was installed with `snap install go`
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mcarifio/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mcarifio/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/5365"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5365/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build822903002=/tmp/go-build -gno-record-gcc-switches"


$ go get -u github.com/hairyhenderson/gomplate/cmd/gomplate # install as per the README.md
package google.golang.org/genproto/googleapis/rpc/status: google.golang.org/genproto is a custom import path for https://github.com/googleapis/go-genproto, but /home/mcarifio/go/src/google.golang.org/genproto is checked out from https://github.com/google/go-genproto
package cloud.google.com/go/compute/metadata: cloud.google.com/go is a custom import path for https://github.com/googleapis/google-cloud-go, but /home/mcarifio/go/src/cloud.google.com/go is checked out from https://code.googlesource.com/gocloud
package cloud.google.com/go/iam/credentials/apiv1: cloud.google.com/go is a custom import path for https://github.com/googleapis/google-cloud-go, but /home/mcarifio/go/src/cloud.google.com/go is checked out from https://code.googlesource.com/gocloud
package cloud.google.com/go/storage: cloud.google.com/go is a custom import path for https://github.com/googleapis/google-cloud-go, but /home/mcarifio/go/src/cloud.google.com/go is checked out from https://code.googlesource.com/gocloud
package google.golang.org/api/option: google.golang.org/api is a custom import path for https://github.com/googleapis/google-api-go-client, but /home/mcarifio/go/src/google.golang.org/api is checked out from https://code.googlesource.com/google-api-go-client
package google.golang.org/api/googleapi: google.golang.org/api is a custom import path for https://github.com/googleapis/google-api-go-client, but /home/mcarifio/go/src/google.golang.org/api is checked out from https://code.googlesource.com/google-api-go-client
package google.golang.org/api/iterator: google.golang.org/api is a custom import path for https://github.com/googleapis/google-api-go-client, but /home/mcarifio/go/src/google.golang.org/api is checked out from https://code.googlesource.com/google-api-go-client
package google.golang.org/genproto/googleapis/iam/credentials/v1: google.golang.org/genproto is a custom import path for https://github.com/googleapis/go-genproto, but /home/mcarifio/go/src/google.golang.org/genproto is checked out from https://github.com/google/go-genproto

$ find $(go env GOPATH) -name gomplate -type f -executable  # anything installed anywhere? no...
$ echo $?
0
```

**Comment by hairyhenderson** [comment]
Thanks for logging this, @mcarifio! Seems you've stumbled upon a documentation bug 😅

The correct command should be:

```
go get github.com/hairyhenderson/gomplate/v3/cmd/gomplate
```

I'll get on that ASAP!

**Comment by mcarifio** [comment]
Does it take some time to propagate?

```bash
$ go get -u github.com/hairyhenderson/gomplate/v3/cmd/gomplate
package github.com/hairyhenderson/gomplate/v3/cmd/gomplate: cannot find package "github.com/hairyhenderson/gomplate/v3/cmd/gomplate" in any of:
	/snap/go/5365/src/github.com/hairyhenderson/gomplate/v3/cmd/gomplate (from $GOROOT)
	/home/mcarifio/go/src/github.com/hairyhenderson/gomplate/v3/cmd/gomplate (from $GOPATH)
```

In the longer run, if I start using `gomplate` more, then I probably want some mechanism to the tool up to date like `apt` or `snap` or `brew`. I'm not sure that `go get` does something simliar and I don't know if it should be preferred. It _would_ be nice to have some way to also "get the latest" without embedding the version (e.g. v3), perhaps something like `go get -u github.com/hairyhenderson/gomplate/latest/cmd/gomplate`. But that's above my pay grade. But if it's possible, then you don't have to churn the README.md.

Thanks for the fix.

**Comment by hairyhenderson** [comment]
@mcarifio strange... that should work! It may have something to do with _where_ you run the command from.

Unless you have some compelling reason to install it with `go get`, it's probably a better idea to just use one of the official binaries or packages. You can download binaries straight from GitHub releases, use the Docker images, `brew` for macOS, or `apk` if you're using Alpine Linux. There are also some unofficial packages (see https://repology.org/project/gomplate/versions, but _caveat emptor_!)

I haven't gotten around to providing deb or RPM packages (too complex to build an official package IMO), or NuGet/Chocolatey for Windows.

Personally I use `brew` on the desktop, which is kept up-to-date every time I make a release. Otherwise, I mostly use the Docker images (`docker run hairyhenderson/gomplate`).

See https://docs.gomplate.ca/installing/ for full details.

**Comment by hairyhenderson** [comment]
Oh, and it turns out it also works with `brew` on Linux:

```console
$ brew install gomplate
...
==> Installing gomplate
==> Pouring gomplate-3.7.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/gomplate/3.7.0: 6 files, 7.8MB
```

I'll update the docs to reflect this since it's not obvious (and was unknown to me, even though I created the original brew formula!)

**Comment by mcarifio** [comment]
TIL https://docs.brew.sh/Homebrew-on-Linux, ty

**Comment by oprekable** [comment]
@mcarifio your issue related with GO111MODULE i think : 

`GO111MODULE=on go get github.com/hairyhenderson/gomplate/v3/cmd/gomplate`

should work.
