### ISSUE TITLE
if (a and b) makes gomplate 3.7 sad 😞

### ISSUE THREAD

**Issue by kjedamzik** [hairyhenderson/gomplate#899]
This used to work fine with 3.6:
```bash
➜  ~ export FOO=1; export BAR=1

➜  ~ echo '{{if (getenv "FOO") and (getenv "BAR") }}omg why{{end}}' |gomplate_darwin-amd64-3.6.0
omg why
```

... but fails with 3.7:

```bash
➜  ~ echo '{{if (getenv "FOO") and (getenv "BAR") }}omg why{{end}}' |gomplate_darwin-amd64-3.7.0

10:15:22 FTL  error="template: -:1:5: executing \"-\" at <(getenv \"FOO\") and (getenv \"BAR\")>: can't give argument to non-function getenv \"FOO\""
```

**Comment by hairyhenderson** [comment]
Hi @kjedamzik, thanks for logging this!

I'm a bit uncertain why this would've worked in 3.6, as the syntax is incorrect.

`and` is a built-in function, and it expects arguments, and so can't be used in the middle of its two arguments.

Try this:

```console
$ export FOO=1; export BAR=1                                                       
$ echo '{{if and (getenv "FOO") (getenv "BAR") }}omg why{{end}}' | gomplate
omg why
```

It's probably also important to note that even though it doesn't fail in 3.6, the logic is actually wrong:

```console
$ docker run --rm -e FOO=1 hairyhenderson/gomplate:v3.6.0 -i '{{if (getenv "FOO") and (getenv "BAR") }}omg why{{end}}' 
omg why
```

I think what's going on here is the `if` action is taking two values, so this resolves down to something like `if "1" ""`. I feel like that would've been a bug in the version of Go that v3.6.0 was compiled with, but I can't find any evidence of such a bug with a cursory glance.

For reference, the `and` documentation is:

> Returns the boolean AND of its arguments by returning the first empty argument or the last argument, that is, "and x y" behaves as "if x then y else x". All the arguments are evaluated.

Either way, you can easily fix this by using the correct syntax!

**Comment by kjedamzik** [comment]
great, thank you
