### ISSUE TITLE
YAML merge keys cannot be merged

### ISSUE THREAD

**Issue by jstewmon** [hairyhenderson/gomplate#909]
Hi 👋 ,

I've found an issue using a YAML data source that contains anchors, aliases and merge keys. Specifically, it seems that merge keys may not be fully resolved / materialized to the anchor value once the YAML is loaded, which can cause problems working with other features.

For example, `merge` will not work with a mapping value which uses a merge key:

`alias.yaml`:
```yaml
foo: &foo
  bar: baz
qux:
    <<: *foo
    qux: bar
```

```
gomplate -d alias.yaml -i '{{ merge (dict "foo" "foo") (datasource "alias").qux }}'

16:49:00 FTL  error="template: <arg>:1:40: executing \"<arg>\" at <\"alias\">: wrong type for value; expected map[string]interface {}; got map[interface {}]interface {}"
```

I can coerce the alias to the anchor's value by round-tripping it to get the expected result:
```
gomplate -d alias.yaml -i '{{ merge (dict "foo" "foo") ((datasource "alias") | toYAML | yaml ).qux }}'
map[bar:baz foo:foo qux:bar]
```

The issue seems specific to using merge keys. We can use an alias without issue:

```yaml
foo: &foo
  bar: baz
qux: *foo
```

```
gomplate -d alias.yaml -i '{{ merge (dict "foo" "foo") ((datasource "alias") ).qux }}'
map[bar:baz foo:foo]
```

**Comment by hairyhenderson** [comment]
@jstewmon Hi, sorry for the late reply, and thanks for logging this! This looks to be a bug. I'll see if I can figure something out!

**Comment by hairyhenderson** [comment]
This turned out to be a bit more complicated than I expected, and I'm only just now getting back to it. This is an upstream bug in the YAML library I'm using: https://github.com/go-yaml/yaml/issues/139#issuecomment-566073291

Thankfully now I understand the problem and will be able to work around it 😉

**Comment by jstewmon** [comment]
Woot! Thank you for digging into the issue and providing a fix! 🙏
