### ISSUE TITLE
"too many open files" when using input-dir

### ISSUE THREAD

**Issue by Velyks** [hairyhenderson/gomplate#928]
Darwin Kernel Version 19.5.0
gomplate version 3.7.0

I'm running gomplate with `--input-dir` set to a folder with 600~ files in which is causing the following error:
`11:06:57 FTL  error="failed to open somedir/somefile.yaml\nopen somedir/somefile.yaml: too many open files"`

On OSX the default soft `ulimit -n` is 256. Is it possible for gomplate to respect the ulimit, or to have a configuration option to set the max concurrent open files?

**Comment by hairyhenderson** [comment]
Hi @Velyks - sorry for the slow response on this.

Yeah, it certainly seems like it _should_ be possible to respect the ulimit. I'll try to fix this.

**Comment by hairyhenderson** [comment]
Ok, I've found the bug - the input files are read one-by-one and closed right after the read is complete, however the output files are all opened at once. I've got an idea on how I can solve this with a minimum of effort, so I'll do that soon, and the fix will be in gomplate 3.8 🙂

**Comment by Velyks** [comment]
Thanks!
