### ISSUE TITLE
Allow setting log format

### ISSUE THREAD

**Issue by jamesgoodhouse** [hairyhenderson/gomplate#942]
It appears the log format is driven solely off of whether gomplate is being ran in a terminal or not. I'm currently running it within a Docker container and am receiving logs in JSON format when a more human readable format would be preferred.

**Comment by hairyhenderson** [comment]
@jamesgoodhouse true. Do you often have a need for the logs? They're meant primarily for troubleshooting, but I'm certainly interested to hear about your logging use-case!

As for what to do about this - does the JSON format have any value to you at all? Or does it make more sense to always output the more human-readable format?

If both formats are useful, I don't think it's a common-enough thing that it warrants a `--log-format=...` flag, but maybe a `GOMPLATE_LOG_FORMAT` environment variable would be enough?
