### ISSUE TITLE
Missing URLEncode/Decode/QueryEscape function out of the box

### ISSUE THREAD

**Issue by ysaakpr** [hairyhenderson/gomplate#947]
gomplate doesnt have the very usefull urlencode and decode utility support. Which is very handy at times to generate urls.

**Comment by hairyhenderson** [comment]
Hi @ysaakpr, thanks for taking the time to log this.

I'm not sure if it's what you're looking for, but the [`url.Parse`](https://docs.gomplate.ca/functions/conv/#conv-url) function may be useful to you. 

For escaping query strings, `urlquery` is available. It's one of the builtins - see [the syntax docs](https://docs.gomplate.ca/syntax/#functions).

Can you tell me a little more about your use-case?

**Comment by ysaakpr** [comment]
oh perfect, i totally missed that its an extension. THank you.
