### ISSUE TITLE
Windows file creation with read-only permissions

### ISSUE THREAD

**Issue by dawidpogorzelski** [hairyhenderson/gomplate#948]
Hello,
when a new file is created on windows via `gomplate -o C:/path/to/file` it will be created as a "read-only" file which means that any other call to `gomplate -o C:/path/to/file` will fail with: `failed to open output file 'C:/path/to/file' for writing: open C:/path/to/file: Access is denied."`

This can be most likely fixed via `Set-ItemProperty file.txt -name IsReadOnly -value $false` but not sure if that should be the default behaviour

**Comment by hairyhenderson** [comment]
Hi @dawidpogorzelski - sorry for the delay! I only have access to Windows through a rarely-updated VM so fixing these sorts of issues can take a while 😉

I have had problems with Windows file permissions in the past, and though I fixed some of them, I'm not surprised you're seeing issues. I'm firing up my VM now and will let you know if I can figure out the issue!

**Comment by hairyhenderson** [comment]
@dawidpogorzelski I'm not able to reproduce this - is it possible that there's an inherited read-only setting in your particular output directory? Or maybe your input file is read-only?

By default, gomplate will attempt to use the same permissions for the output file as the input file.

Have you tried using the [`--chmod`](https://docs.gomplate.ca/usage/#chmod) flag to set permissions?

In windows, only the owner portion of the mode, and only the read/write bits are supported. But something like this should work:

```console
gomplate.exe --chmod=0666 -f in.txt -o out.txt
```

Can you try this out and let me know how this works?

**Comment by dawidpogorzelski** [comment]
So i did a few tests and it seems like even
gomplate.exe -f in.txt -o out.txt OK
cat c:/tmp/in.txt | gomplate --chmod=0666 -o out.txt OK
cat c:/tmp/in.txt | gomplate -o out.txt Read-only attribute on the file

So for some reason when reading from stdin(powershell) and not adding a `--chmod=0666` sets the `Read-only` file attribute to true but your suggestion solves the problem so it's all good, thanks :)

**Comment by hairyhenderson** [comment]
Hmm... Thanks for doing the investigation @dawidpogorzelski! This is definitely a bug so I'll reopen it. The current behaviour on non-Windows OSes is to default to a mode of `0644` - see https://github.com/hairyhenderson/gomplate/blob/c75fa4aaaad4a9679b09cbfcb35c527d9a471d3b/internal/config/configfile.go#L476

Clearly, Windows interprets that as `0444` (i.e. read-only). The fix is actually fairly simple - to just default to a mode of `0666` when running on Windows.
