### ISSUE TITLE
Template to process from remote datasource (such as aws+ssm)

### ISSUE THREAD

**Issue by hongkongkiwi** [hairyhenderson/gomplate#963]
I read the documentation but couldn't quite figure the answer to my question.

What I would like to do is to store the complete template in AWS SSM Parameter Store. Inside the template is the datasources etc. This way I can use the standard gomplate docker and keep the template easily updatable.

The template is then output to an application specific config file.

Is there a way to dynamically grab the template itself? Then process the downloaded template.

**Comment by hongkongkiwi** [comment]
To answer my own question, I just saw that you can pass the template via stdin, so for now the way to accomplish my goal is to run gomplate to pull the template, then pass that to another instance of gomplate. e.g. gomplate...... | gomplate 

I think this way should work, but am I missing a flag that allows doing this with one instance of gomplate?

**Comment by hairyhenderson** [comment]
Hi @hongkongkiwi, thanks for logging this!

Interestingly, a similar idea came up [in Slack today](https://gophers.slack.com/archives/CGTR16RM2/p1602878677014000) 😉. This is also related to #589.

I'm definitely open to doing this, and this recent interest is good motivation to work on it soon 😉

You _could_ also work around this for now by treating the input template as a datasource instead, like this:

```console
$ gomplate -d mytemplate=aws+ssm://whatever... -i '{{ include "mytemplate" | tmpl.Inline }}'
```

See https://docs.gomplate.ca/functions/data/#include and https://docs.gomplate.ca/functions/tmpl/#tmpl-inline for the docs on those functions.

**Comment by hongkongkiwi** [comment]
That's a great workaround thank you.

**Comment by hairyhenderson** [comment]
No movement has happened here yet, but it's still valid. Once #1336 is completed, this will automatically be accomplished.
