### ISSUE TITLE
Feature request: --exclude-directory

### ISSUE THREAD

**Issue by hcsaustrup** [hairyhenderson/gomplate#977]
Hi!

I'd like to limit recursion by specifying an option like `--exclude-directory backup-*` (matching anything starting with `backup-`) or `--exclude-directory .*` (matching Unix style hidden directories).

I'm using this for mounted Kubernetes ConfigMaps, which is implemented with an interesting cocktail of symbolic links and hidden directories. An option like `--exclude-directory` would make this a lot easier and less messy to process.

Thanks,
HC

**Comment by hairyhenderson** [comment]
Hi @hcsaustrup, thanks for the feature request!

I think the existing `--exclude` option should work for this - see https://docs.gomplate.ca/usage/#exclude-and-include for the docs.

For example, I think this should work:

```console
$ gomplate --input-dir . --exclude backup-* --exclude .*
```

(though you may need to surround the arguments with quotes - `--exclude 'backup-*' --exclude '.*'` depending on your shell)

The argument is in gitignore style, so it's neither a regex nor a glob. The format is described [here](https://git-scm.com/docs/gitignore).

**Comment by hcsaustrup** [comment]
Amazing! I don't know how I managed **not** to try that! :grin: Thanks again for an awesome tool! :clap:

**Comment by hairyhenderson** [comment]
@hcsaustrup glad it worked for you, and thanks for the kind words! 🙇‍♂️
