### ISSUE TITLE
install docs: docker copy --from is wrong

### ISSUE THREAD

**Issue by doronaco** [hairyhenderson/gomplate#980]
It's 
`COPY --from=hairyhenderson/gomplate:3.7.0-slim /gomplate /bin/gomplate`
but should be
`COPY --from=hairyhenderson/gomplate:v3.7.0-slim /gomplate /bin/gomplate`

**Comment by hairyhenderson** [comment]
@doronaco thanks for pointing this out! I'll fix that right now.
