### ISSUE TITLE
gomplate.RunTemplates leaks file handles

### ISSUE THREAD

**Issue by rdriesner** [hairyhenderson/gomplate#995]
I´m running gomplate via RunTemplates twice in my code and have identified on windows that f.e. Rename or Delete of used files in the datasource or context are not accessible. I know that gomplate is designed to run as cli.
The problem can be fixed if the opened files are closed which are read at:
- datasource_file.go -> readFile()
- file.go -> Write()
- readers.go -> Read()

Closing the files at this methods solved the leaking, maybe there is a better way.
BR
Robert

**Comment by hairyhenderson** [comment]
Hi @rdriesner, thanks for logging this!

> I know that gomplate is designed to run as cli.

While true, I would like gomplate to be usable as a library as well - there's some history in #548 about that if you're interested!

I'll take a look at this soon.

**Comment by hairyhenderson** [comment]
Finally getting around to this 😅

> * readers.go -> Read()

This is the `LazyReadCloser`, so it can't be closed in the `Read` function - it must only be closed by the `Close` function (it's a `io.ReadCloser`). Ultimately, files opened lazily with this get closed once template execution is complete ([here](https://github.com/hairyhenderson/gomplate/blob/00b3ee192ebe9bc21eae3218c9d61f44d25b3910/gomplate.go#L48)).

The others can be easily closed!
