### ISSUE TITLE
sprig kindIs ?

### ISSUE THREAD

**Issue by bennythejudge** [hairyhenderson/gomplate#997]
Hi,
I hope the following makes sense - I am not sure it does to me as I am new to Golang, its templating and `gomplate`.
I just read https://github.com/hairyhenderson/gomplate/issues/283.
I am working on an existing code base with a lot of templates and I was looking at using `gomplate` but I found that I am missing `kindIs` which is used in this code base.
Is there something I could do to work around this?
I went through the doc and I don't see an equivalent function in gomplate.
Thanks.

**Comment by hairyhenderson** [comment]
Hi @bennythejudge,

The equivalent to sprig's `kindIs` is [`test.IsKind`](https://docs.gomplate.ca/functions/test/#test-iskind).

I'll close this now, but feel free to re-open if you have any issues with this!
